### ISSUE TITLE
Trying to setup USB mic as audio stream

### ISSUE THREAD

**Issue by nitaybz** [Sunoo/homebridge-camera-ffmpeg#1003]
Hey Guys,
I've been trying for hours to setup a stream on my raspberry pi that will include both video from a Raspberry Pi cam and audio from a USB mic. The video is working flawlessly but with no sound at all.
When I use ffmpeg directly to record to an MP4 file using the same parameters it records fine with audio included, but somehow in HomeKit I can't get any audio from the mic.
Please assist.

I'm using Rasberry Pi 2 flashed with homebridge image
OS | Raspbian GNU/Linux Buster (10) 
Homebridge v1.3.0-beta.32
Node.js Version | v14.15.1

this is my camera config:
```
    {
        "name": "test cam",
        "unbridge": true,
        "videoConfig": {
            "source": "-f video4linux2 -input_format h264 -video_size 1280x720 -thread_queue_size 8192 -framerate 30 -i /dev/video0 -f alsa -thread_queue_size 8192 -ac 1 -i hw:1,0",
            "stillImageSource": "-s 1280x720 -f video4linux2 -i /dev/video0",
            "maxStreams": 2,
            "vcodec": "copy",
            "audio": true,
            "debug": true
        }
```

I tried using a lot of different parameters in the source key, tried using "h264_omx" instead of copy, it just gives me bad video quality without sound as well.

Thanks in advance🙏

**Comment by Sunoo** [comment]
The Homebridge 1.3 betas have known issues with camera audio: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/974

**Comment by nitaybz** [comment]
Thank you so much!
I can't believe that after hours of trying different setups it was the Homebridge beta 🤦‍♂️
I'm just glad it is solved now 🙏
