### ISSUE TITLE
Camera Motion Sensor not being triggered

### ISSUE THREAD

**Issue by diego2021s** [Sunoo/homebridge-camera-ffmpeg#1011]
I've set up a few Truvision IP Cameras (Hikvision OEM) using the Homebridge Camera FFmpeg

The Cameras are showing up correct on Homekit now; however I tried using the Motion sensor built-in on the camera using the optional parameters and triggering with dummy switches.

No motion is being detected and I'm wondering if I should be setting something additional on the code in order to tie the camera's motion sensor to Homekit.

This is my config, I just can't find a way to get the notifications even after I added the automation on HomeKit with the switch turning on when motion is detected on the Camera sensor.

Any ideas on what I could be doing wrong or how I could start getting notifications?

The camera has motion and it is working fine with the native app.

This is the link of the Camera that I'm using [RS-3230](https://static.interlogix.com/library/1072881c-truvision-12-32-series-ip-camera-configuration-manual-en.pdf)

Just wondering if I should write any more code, add any other plugin, or try something on the camera's UI.

{
"bridge": {
"name": "Homebridge xxxx",
"username": "XX:XX:XX:XX:XX:XX",
"port": XXXXX,
"pin": "XXX-XX-XXX"
},
"accessories": [],
"platforms": [
{
"name": "Config",
"port": 8581,
"auth": "form",
"theme": "auto",
"tempUnits": "f",
"lang": "auto",
"platform": "config"
},
{
"name": "Camera FFmpeg",
"cameras": [
{
"name": "Camera",
"manufacturer": "Truvision",
"model": "RS-3230",
"firmwareRevision": "V1.1 FP4",
"motion": true,
"doorbell": false,
"switches": true,
"videoConfig": {
"source": "-i rtsp://user:password@192.168.1.XXX:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1",
"stillImageSource": "-i http://user:password@192.168.1.XXX:80/ISAPI/Streaming/channels/101/picture",
"vcodec": "copy",
"audio": true
}
},
}
],
"platform": "Camera-ffmpeg"
}
]
}

**Comment by Sunoo** [comment]
Looks like we got this sorted out over on Reddit. https://www.reddit.com/r/homebridge/comments/l5lw0r/motion_notifications_using_homebridge_camera/
