### ISSUE TITLE
Custom MQTT Topic for motion start and reset

### ISSUE THREAD

**Issue by theld07** [Sunoo/homebridge-camera-ffmpeg#1023]
I’ve been using this plug-in for a while.
In my setup there are 5 YI Home Camera (1080p). They all have custom firmware (YI Hack v4) installed. One of these is installed outside the door and acts as a doorbell camera. I tried to use it as a motion sensor, but I’m having problems with the “reset”.
I mean, I can’t make my “sensor” publish in “homebridge/motion/reset”.

For exemple, my camera can publish in topic “homebridge/motion” and message “motion_start” to trigger and message “motion_stop” to reset. 
The settings menu is like this:
![C66F7019-9E93-4756-8B78-B9E3190B90C9](https://user-images.githubusercontent.com/8177376/107155885-4ab1eb00-697b-11eb-8616-ff2df28d3bbc.jpeg)

It lets me define only the subtopic motion, but I can’t publish in “reset” subtopic.

Is it something you can consider? I don’t have the skills necessary to try doing it…

Thank you. 
Greetings from Italy! 🙂

**Comment by Sunoo** [comment]
I plan to completely rework MQTT support to handle this type of scenario, I just haven’t gotten to it yet.

It is already tracked in #877 so I’m going to close this one out.
