### ISSUE TITLE
Motion sensor not working

### ISSUE THREAD

**Issue by fmpmsilva** [Sunoo/homebridge-camera-ffmpeg#1029]
Hi there. I have a Tapo C200 installed. Works great but I can’t put the motion sensor to work. I can see it on HomeKit but not working. Any help?

**Comment by Sunoo** [comment]
What are you using to support the motion sensor?

**Comment by fmpmsilva** [comment]
Sorry but I’m new in this. I think it’s http.

**Comment by Sunoo** [comment]
https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

**Comment by fmpmsilva** [comment]
I’ve tried that but still no nothing. Router problems?

**Comment by Sunoo** [comment]
Tried what exactly?

**Comment by fmpmsilva** [comment]
The http option

**Comment by Sunoo** [comment]
And what are you using to call the HTTP service to trigger motion?

**Comment by fmpmsilva** [comment]
Nothing. Do I have to install another plugin?

**Comment by Sunoo** [comment]
If your camera doesn’t have the ability to make HTTP calls when motion is detected directly, yes.

**Comment by fmpmsilva** [comment]
"name": "Camera FFmpeg",
            "porthttp": 8080,
            "localhttp": false,
            "cameras": [
                {
                    "name": "NAME",
                    "manufacturer": "TP Link",
                    "model": "C200",
                    "motion": true,
                    "doorbell": false,
                    "switches": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:pass@ip/stream1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "forceMax": false,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": true,
                        "debug": true

**Comment by fmpmsilva** [comment]
this is what i have

**Comment by fmpmsilva** [comment]
I’m sorry but still no workaround for motion sensor trigger in my camera. Can you help with some guidance to do it, for instance thru http.

**Comment by Sunoo** [comment]
You need to configure something that actually triggers the motion alerts:
- HTTP or MQTT from the camera itself
- One of the helper plugins, such as the ones for FTP or SMTP
- Setting up the Motion application to watch the stream and determine when motion has occurred

**Comment by fmpmsilva** [comment]
Thanks. I will do some research about it.
