### ISSUE TITLE
high resolution video stream problem

### ISSUE THREAD

**Issue by djsomi** [Sunoo/homebridge-camera-ffmpeg#1031]
**Describe The Problem:**

I experience a buffer type of video image distortion with my high resolution cameras.
My devices are streaming 5M video with the resolution of 2592x1944px.
Please advice what to check or change in the config.

**Logs:**

Following error msg are visible in logs while streaming:

[error]  corrupted macroblock 152 52 (total_coeff=-1) [h264 @ 0x55c8892d5e40] 
[error]  error while decoding MB 152 52
[error]  out of range intra chroma pred mode

**Homebridge Config:**

Started with the default simple config, than tried to change some of the optional video config parameters (packetsize, bitrate, force resolution), but image always the same as below:

**Screenshots:**

![IMG_1321](https://user-images.githubusercontent.com/19391031/107507802-62b68400-6ba0-11eb-9987-3f3c110969e1.jpeg)

**Environment:**

* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.10
* **Homebridge Version**:1.2.5 
* **Homebridge Camera FFmpeg Version**: 3.0.3
* **Homebridge Config UI X Plugin Version**:4.38.0
* **Operating System**: docker (no resource problem)

**Comment by noenic** [comment]
Maybe try adding the argument "vcodec": "copy"  if you use h264

**Comment by djsomi** [comment]
Unfortunately its not helped, BUTI found that if if camera is in night mode the problem is not visible or just a little bit on the bottom of the image. Maybe this is related to bitrate.

**Comment by noenic** [comment]
> 
> 
> Unfortunately its not helped, BUTI found that if if camera is in night mode the problem is not visible or just a little bit on the bottom of the image. Maybe this is related to bitrate.


I'm sorry I can't help you more, I already have some weird problems with this plugin myself that I can't understand. But when I remember seeing a similar problem on a [YouTube tutorial](https://www.youtube.com/watch?v=LdcP0j9lyrw&t=782sl) around 12min35s from the capture you sent I would have assumed it was the same cause...
Did you test the stream with a lower resolution ?

**Comment by djsomi** [comment]
Hi Noenic,

Thanks for sending that video, its a nice tutorial and the solution for my problem was also there:

I had to add the transport definition in source:

**"source": "-rtsp_transport http -i rtsp://....**

and also added

**"vcodec": "copy"**

which solved the pixelated image problem.

Thanks again!
