### ISSUE TITLE
Camera disapears from the homekit app and take down my ledstrip

### ISSUE THREAD

**Issue by noenic** [Sunoo/homebridge-camera-ffmpeg#1032]
https://user-images.githubusercontent.com/75330764/107557475-f5bfe000-6bd9-11eb-89c3-e27beed2d3b9.mp4

When I tinker to much with the camera and motion sensor, the camera just disapear from the app and take down my ledstrips from yeelight (wich make actually no sense since i have also 2 light bulb from yeelight and they still work)

So i still dont know how to change the name or the room of the camera
**To Reproduce:**
It happen systematcally when i try to change the room of the camera 
and sometime while doing nothing 

I have to restart HB everytimes it happen
what actually annoys me is that in the accessory tab in the HB UI i can still control the ledstrip and can still see the camera feed in VLC 

**Logs:**
Nothing appears in the logs 

**Homebridge Config:**
{
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera",
                    "motion": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-i  *rtps link here*
                        "stillImageSource": "-i *png link here*,
                        "maxBitrate": 4096,
                        "maxPacketsize": 752
                    }
                }
            ]
        }

**Screenshots:**

* **Node.js Version**:  14.15.1
* **NPM Version**:  6.14.8
* **Homebridge Version**: 1.1.6
* **Homebridge Camera FFmpeg Version**: 3.0.3  
* **Homebridge Config UI X Plugin Version**: 4.34.0  
* **Operating System**: Windows 10

**Comment by Sunoo** [comment]
That’s odd, I can’t see why any of that would cause the problem. Homebridge doesn’t even have any way of knowing when you’ve changed the room a devices is assigned to or anything...

Please enable debug for the camera and share your logs. You could also try unbridge mode, would should hopefully isolate the problem from your other Homebridge devices.

**Comment by noenic** [comment]
> That’s odd, I can’t see why any of that would cause the problem. Homebridge doesn’t even have any way of knowing when you’ve changed the room a devices is assigned to or anything...
> 
> 
> 
> Please enable debug for the camera and share your logs. You could also try unbridge mode, would should hopefully isolate the problem from your other Homebridge devices.



I enabled debug mode in the camera camera config, didn't tell me anything else except the usual ffmpeg log 

nop, no error nothing that can explain that 

What do you mean by unbridge mode ? How do i do that ? 
thanks !

**Comment by Sunoo** [comment]
But there is nothing at all in your logs?

**Comment by noenic** [comment]
> 
> 
> But there is nothing at all in your logs?

nop nothing expect the usual ffmpeg log 

i found out how to put it in unbridge mode and I didn't see the camera diseapear again but the ledstrip still did am gonna try to reset the yeelight config, because this light is really glitchy i can't even change the icon without the light diseapearing, but for now the camera is working and i think it saved the settings, i will look further into it tomorrow

thanks again :)
