### ISSUE TITLE
Since few days no snapshot on Apple watch

### ISSUE THREAD

**Issue by fennec622** [Sunoo/homebridge-camera-ffmpeg#1037]
Hi

Since few day when i have motion on camera 

i have no snapshot on apple watch

i have push but no picture and i have picture on phone

And i can view live camera on watch so i think configuration is ok

I test on two watch same problem

Someone have same problem

Before all is ok, and with other app like Zmninja i have snapshot on watch 

Thanks for your help

**Comment by Sunoo** [comment]
There seems to be some sort of bug in the latest versions of watchOS that cause issues with snapshots. Hopefully Apple fixes it in the next release.

**Comment by fennec622** [comment]
Ok thanks

**Comment by fennec622** [comment]
Hi
Always no picture ...

Other option to add ?

With doorbell all is ok vidéo start immediately

**Comment by fennec622** [comment]
Yes I use stillimagesource 

It s jpg file 

Can you confirm me all is ok for you ? On watch

**Comment by Sunoo** [comment]
If snapshots aren’t loading, most likely your stillImageSource URL is bad.

**Comment by fennec622** [comment]
if it's ok for you 
I search where is the problem
thanks

**Comment by fennec622** [comment]
The size is not to big for watch ? 1280*720

`Jun  7 23:36:35 raspberrypiManager homebridge[19820]: [07/06/2021, 23:36:35] [Camera FFmpeg] [Camera Devant] Snapshot requested: 1280 x 720
Jun  7 23:36:35 raspberrypiManager homebridge[19820]: [07/06/2021, 23:36:35] [Camera FFmpeg] [Camera Devant] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://10.0.0.1/snapzm/devant.jpg -frames:v 1 -f image2 - -hide_banner -loglevel error
Jun  7 23:36:35 raspberrypiManager homebridge[19820]: [07/06/2021, 23:36:35] [Camera FFmpeg] [Camera Devant] Fetching snapshot took 0.145 seconds.
Jun  7 23:36:35 raspberrypiManager homebridge[19820]: [07/06/2021, 23:36:35] [Camera FFmpeg] [Camera Devant] Sending snapshot: 1280 x 720
Jun  7 23:36:35 raspberrypiManager homebridge[19820]: [07/06/2021, 23:36:35] [Camera FFmpeg] [Camera Devant] Resize command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -`

**Comment by Sunoo** [comment]
Looking at your log, it’s asking for a 1280x720 snapshot, and that is what my plugin is sending.

**Comment by fennec622** [comment]
Yes it's classic push

Plugin don't know if push is for watch or Iphone

Question is why classic push request 1280x720
And app home apple watch request 320x240

Snapshot send to iphone have all information for resize ? when display on watch

**Comment by Sunoo** [comment]
HomeKit requests a resolution, my plugin honors whatever request it receives. Typically for a push, each device will reach out and request whatever snapshot it wants at the same time.

**Comment by fennec622** [comment]
yes but i don't know why watch don't display on push but ok in app home

Do you change something in Resize command

Because before it's ok

**Comment by Sunoo** [comment]
Depends on when “before” was. I haven’t made any changes of any kind in probably 2 months or so now.

**Comment by fennec622** [comment]
My first post is from feb

so in start year i think

**Comment by Sunoo** [comment]
I believe 3.1.1 (on March 1) was when I changed that logic. Your issue doesn’t line up with the date of any release though.
