### ISSUE TITLE
D-Link DCS-1130

### ISSUE THREAD

**Issue by NicholasB60** [Sunoo/homebridge-camera-ffmpeg#1042]
**Manufacturer/Model:**
D-Link DCS-1130

**Homebridge Config:**

"name": "D-Link Camera",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://admin:password@localip:port/video/mjpg.cgi",
                        "stillImageSource": "-i http://admin:password@localip:port/image/jpeg.cgi",
                        "maxStreams": 2,
                        "maxWidth": 320,
                        "maxHeight": 240,
                        "maxFPS": 30

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/D-Link-DCS-1130.html
