### ISSUE TITLE
Post upgrade to 1.3.1 of Homebridge - "The image snapshot handler for the given accessory is slow to respond!" error

### ISSUE THREAD

**Issue by mikefoley** [Sunoo/homebridge-camera-ffmpeg#1047]
Hi,

I'm seeing the following log in my logs when trying to access my Wyse RTSP cameras. This showed up after the upgrade of Homebridge to 1.3.1.

[camera] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.

Thoughts?

thanks,
mike

**Comment by Sunoo** [comment]
Your camera is probably slow to start sending frames, not much can really be done about that. I’m guessing even before the update your snapshots in the Home app refreshed slower than every 10 seconds, there was just no warning about it in the logs.

**Comment by mikefoley** [comment]
Any way to adjust this to lessen the number of errors in the logs?

**Comment by Sunoo** [comment]
The only way I could stop the warnings from appearing is if I killed the attempt to get a snapshot before the warning appeared, but then your snapshot likely just wouldn't update at all.

**Comment by Sunoo** [comment]
Homebridge 1.3.2 now hides the slow warnings when the camera is operating in unbridge mode.

**Comment by scottleestrange** [comment]
Not true, the error still comes

**Comment by johnnygoodface** [comment]
scottleestrange is right. With this config I still get those warning every 10 sec

        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "WyzeCam",
                    "manufacturer": "Wyze",
                    "model": "WYZEC2",
                    "firmwareRevision": "4.28.4.49",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://Admin:password@192.168.1.155/live",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "vcodec": "copy",
                        "packetSize": 940,
                        "audio": true,
                        "debug": false
                    }
                }
            ]
        }

[17/06/2022, 13:52:03] [Camera-ffmpeg] [WyzeCam] Fetching snapshot took 5.34 seconds.
[WyzeCam 35E9] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.

**Comment by johnnygoodface** [comment]
Any follow up on this? Any way to set a "debug mode" to "silent" or else.. It's cluttering the log screen a lot.
![Capture d’écran, le 2022-07-25 à 12 08 01](https://user-images.githubusercontent.com/24813857/180824672-c3e4636a-f04f-4787-9a19-c56ca23fe849.jpg)

**Comment by Sunoo** [comment]
I put the message that starts with the plugin name in, because the other message is written by Homebridge itself. Their link says to contact the plugin author, but there is nothing I can do about cameras being slow to respond.

If you get Homebridge to offer some way to hide that message, I’d be willing to hide mine as well.
