### ISSUE TITLE
The image snapshot handler for the given accessory didn't respond at all! 

### ISSUE THREAD

**Issue by alexsalex** [Sunoo/homebridge-camera-ffmpeg#1049]
[Outside Garage 1577] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory didn't respond at all! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory didn't respond at all! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory didn't respond at all! See https://git.io/JtMGR for more info.
[Outside Garage 1577] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.

**Comment by Sunoo** [comment]
Please share your config and your logs with debug enabled for the camera.

Did this ever work or is this broken from the first time you set it up? Sounds like most likely your camera is incredibly slow to provide an image, in which case there is not much I can do.

**Comment by MikeDProducer** [comment]
Try testing from another device. My phone occasionally does this. Power off and then back on.

**Comment by llamafilm** [comment]
I have the same problem using Amcrest IP5M camera.  What is the timeout time period in homebridge?  Using ffmpeg on the command line it takes about 1.6 seconds to get a snapshot from this camera.

```
$ time ffmpeg -i "https://homebridge:xxxxxxxx@192.168.20.11/cgi-bin/snapshot.cgi" -y camera.jpeg
ffmpeg version git-2021-03-15-5282147 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libx264 --enable-openssl
  libavutil      56. 68.100 / 56. 68.100
  libavcodec     58.131.100 / 58.131.100
  libavformat    58. 74.100 / 58. 74.100
  libavdevice    58. 12.100 / 58. 12.100
  libavfilter     7.109.100 /  7.109.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[https @ 0x564712cf9280] Unable to parse 'secure; HttpOnly'
    Last message repeated 1 times
Input #0, jpeg_pipe, from 'https://homebridge:xxxxxxxxx@192.168.20.11/cgi-bin/snapshot.cgi':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 2592x1944 [SAR 118:118 DAR 4:3], 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'camera.jpeg':
  Metadata:
    encoder         : Lavf58.74.100
  Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown, progressive), 2592x1944 [SAR 118:118 DAR 4:3], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc58.131.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=10.4 size=N/A time=00:00:00.04 bitrate=N/A speed=1.33e+04xframe=    1 fps=0.0 q=10.4 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.143x    
video:324kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

real	0m1.561s
user	0m0.465s
sys	0m0.078s
```

**Comment by Sunoo** [comment]
Please share your log with debug enabled on the camera, as well as your config.

**Comment by llamafilm** [comment]
I tried, but after restarting Homebridge the problem went away!  I'll leave it in debug mode for now and see if it happens again.
