### ISSUE TITLE
Camera stops stream after about 3 minutes.

### ISSUE THREAD

**Issue by eliteladen** [Sunoo/homebridge-camera-ffmpeg#1060]
**Describe The Problem:**
When watching live feed from the cameras, they will work fine for a few minutes, but then will suddenly stop streaming and just show "no response" message. This happens when watching it as PIP or with the whole app open.

**To Reproduce:**
Simply wait for a few minutes and the stream will freeze

```
[05/03/2021, 11:11:23] [Camera FFmpeg] [Câmera da Sala 3] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[05/03/2021, 11:14:47] [Camera FFmpeg] [Câmera da Sala 3] Stopped video stream.
```

**Homebridge Config:**

 {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Câmera da Lara",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://...",
                        "maxStreams": 3,
                        "vcodec": "copy",
                        "audio": true
                    }
                },
                {
                    "name": "Câmera da Sala 3",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp:/...",
                        "maxStreams": 4,
                        "vcodec": "copy",
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Environment:**

* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.2
* **Homebridge Camera FFmpeg Version**: 3.1.1
* **Homebridge Config UI X Plugin Version**: 4.39.1
* **Operating System**: Raspabian

**Comment by Sunoo** [comment]
Can you enable debug on the config for that camera and share your log again? Given that it seems to take over 3 minutes to fail, there is no need to include the full 3 minutes worth of logging, just start from maybe 30 or so lines above "Stopped video stream".

**Comment by eliteladen** [comment]
For some reason, when I enabled debug, it won't freeze anymore. It ran for over 15 minutes without 1 freeze. However, the second I disable debug logs, it freezes again at around 3 minutes mark. So not sure how to show it to you. When using the debug, it keeps saying something along the lines of:
[05/03/2021, 12:05:03] [Camera FFmpeg] [Câmera da Lara] [libfdk_aac @ 0x3368670] 
[05/03/2021, 12:05:03] [Camera FFmpeg] [Câmera da Lara] [warning] 
[05/03/2021, 12:05:03] [Camera FFmpeg] [Câmera da Lara] Queue input is backward in time

But it just keeps going without fail. Without the debug option though. Fails consistently.

Something else that happens is that the stream simply won't work on Apple TV (it does work on every other device). When trying to open on Apple TV it shows "starting stream" and then nothing happens.

**Comment by Sunoo** [comment]
Yea, that warning is nothing to worry about, the audio encoder just likes to throw those a lot, but I've never seen any issues as a result. Trying to resolve the warning is on my to do list, but as it doesn't appear to cause problems, it is very far down the list.

I can't think of a reason why debug mode should change stability of the stream, the only thing that should change is how much gets logged. The next version of this plugin will always log errors from FFmpeg, even outside of debug mode, I hope to release that tonight, maybe that will help us see why it's closing like that.

And you're not the first person to report issues related to Apple TV, but I really haven't had a chance to look into that much yet. Hopefully I can look at it soon, but my current theory is that the Apple TV is pickier about what bitrate it accepts than other devices, for some reason. It seems that, at least in some cases, switching away from the copy vcodec gets it working. I'll open a new issue to track this soon.

**Comment by eliteladen** [comment]
Just to keep you updated, indeed I've been running a lot of tests for the last hour and debug mode does seem to fix the freeze completely. The second I turn it of, freeze after 3 minutes. I'll run the tests again after the next update you mentioned, so let's hope this fix it. Indeed a weird bug and it doesn't make much sense.

Thanks for your quick replies, let me know if you need me to do anything else.

**Comment by Sunoo** [comment]
Sounds like I just need to find some time to look deeper at the code to understand why that would happen. It really doesn't make any sense to me that debug should change that.

**Comment by Sunoo** [comment]
So I just watched a stream for ~40 minutes and it worked fine, however that was done on the currently unreleased v3.1.2, which did have some changes to debugging and such, so maybe I already fixed it?

I'll try to get a test done on v3.1.1 shortly to see if I can at least recreate the problem there though.

**Comment by Sunoo** [comment]
I was able to recreate on 3.1.1, however, I still cannot explain it. Either way, looks like it should be fixed when I push the next version.

**Comment by Sunoo** [comment]
3.1.2 was just published, please give it a shot and see if it resolves the issue for you.

**Comment by eliteladen** [comment]
Yes, this new update fixed it perfectly. Thank you!
