### ISSUE TITLE
Doorbell use only

### ISSUE THREAD

**Issue by fmpmsilva** [Sunoo/homebridge-camera-ffmpeg#1061]
**Describe The Problem:**
I would like to use the doorbell switch without the camera, or if it’s not possible I would like to know if it’s possible instead of stream live feed if it’s possible to have a gif file showing on video stream and a picture of someone ringing on the still images, booth stored on a IMac.

Thanks!

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
This plugin is based around cameras, so I don't plan to support not having a camera associated with the doorbell.

That said, you can definitely point the `source` at a static image, a gif, or even a video file, which it sounds like should meet your use case.
