### ISSUE TITLE
Flashforge Adventurer 3

### ISSUE THREAD

**Issue by dan-parker** [Sunoo/homebridge-camera-ffmpeg#1065]
**Manufacturer/Model:**
Flashforge Adventurer 3

**Homebridge Config:**
                {
                    "name": "Adventurer 3",
                    "manufacturer": "Flashforge",
                    "model": "Adventurer 3",
                    "serialNumber": "1234567890AB",
                    "firmwareRevision": "1.2.3",
                    "videoConfig": {
                        "source": "-f mjpeg -i http://example.com:8080/?action=stream",
                        "stillImageSource": "-f mjpeg -i http://example.com:8080/?action=stream -vframes 1 -r 1",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "debug": false
                    }
                }

**Additional Information:**
Likely the same for other Flashforge models with Cameras

**Comment by Sunoo** [comment]
This looks like Octoprint to me, does http://example.com:8080/?action=snapshot load a still image? If so, that’d be a better option for stillImageSource.

**Comment by dan-parker** [comment]
Doesn’t seem to load anything with that url. I can see the get request , but it times out with no data returned.
But you are right if that worked would be much cleaner

Thanks
Dan

**Comment by Sunoo** [comment]
Worth a shot. I’ll get this config added as soon as I can.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Flashforge-Adventurer-3.html
