### ISSUE TITLE
Dahua N41C2P2 NVR with N42BJ62 5MP Camera

### ISSUE THREAD

**Issue by jonsem2** [Sunoo/homebridge-camera-ffmpeg#1068]
** Dahua / N42BJ62 **

N42BJ62 camera on a POE NVR with it own isolated network

{
    "bridge": {
        "name": "Homebridge C4BC",
        "username": "xxxxxxxx",
        "port": xxxxx,
        "pin": "xxxxx",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "loginWallpaper": "/Users/Downloads/wall.jpg",
            "platform": "config"
        },
        {
            "email": "xx@gmail.com",
            "password": "password",
            "name": "Garage Door",
            "refreshInterval": 60,
            "activeRefreshInterval": 10,
            "activeRefreshDuration": 602,
            "platform": "myQ"
        },
        {
            "host": "192.168.1.47",
            "deviceType": "DSC",
            "password": "id",
            "pin": "XXXX",
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "partitions": [
                {
                    "name": "Home"
                }
            ],
            "zones": [
                {
                    "name": "SIDE DOOR",
                    "partition": 1,
                    "zoneNumber": 3,
                    "type": "door"
                },
                {
                    "name": "FRONT DOOR",
                    "partition": 1,
                    "zoneNumber": 1,
                    "type": "door"
                },
                {
                    "name": "FRONT MOTION",
                    "partition": 1,
                    "zoneNumber": 2,
                    "type": "motion"
                },
                {
                    "name": "DINING WINDOWS",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "window"
                },
                {
                    "name": "PATIO DOOR",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "door"
                },
                {
                    "name": "WINDOW KITCHEN FAMIL",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "window"
                },
                {
                    "name": "KITCHEN MOTION",
                    "partition": 1,
                    "zoneNumber": 7,
                    "type": "motion"
                },
                {
                    "name": "BASEMENT WINDOWS",
                    "partition": 1,
                    "zoneNumber": 8,
                    "type": "window"
                }
            ],
            "platform": "Envisalink"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "token",
                "cookies": "cookies",
                "apiKey": "key"
            },
            "platform": "Nest"
        },
        {
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung TV",
                    "ip": "192.168.1.161",
                    "mac": "xx:xx:xx:xx"
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Doorbell",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.61:554",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "maxBitrate": 0,
                        "audio": false
                    }
                },
                {
                    "name": "FrontDoor",
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0"
                    }
                },
                {
                    "name": "Backyard",
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=2&subtype=0"
                    }
                },
                {
                    "name": "Driveway",
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=3&subtype=0"
                    }
                },
                {
                    "name": "SideEntrance",
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=4&subtype=0"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Additional Information:**

These cameras are connected to a  Dahua POE NVR on a isolated network.  RTSP stream is being reached by going to NVR LAN address.

rtsp://<username>:<password>@<NVRipaddress>:<port>/cam/realmonitor?channel=1@subtype=0
channel:stream channel on NVR;subtype: Code-stream ty[pe, main stream 0, substream 1

rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=4&subtype=0

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Dahua-N41C2P2-NVR.html
