### ISSUE TITLE
Getting code: NULL and signal: SIGILL on Pi 0 with Blue Iris

### ISSUE THREAD

**Issue by Gr8hifi** [Sunoo/homebridge-camera-ffmpeg#1071]
**Describe The Problem:**
I have added a Blue Iris camera using recommended settings.  The Image works great.  The video will not come up at all. It will display a spinning wait before timing out on the iOS device.  I have uninstalled and reinstalled fresh to eliminate other plugins as the problem  This and Homebridge UI are the only two plugins running.   The Blue Iris camera is the only accessory I have installed.   I am attempting to run this on a Raspberry Pi 0 W.

**To Reproduce:**
Trying to view video from home app on iOS14 by tapping the image will cause it to timeout and fail. 

**Logs:**
Starting to advertise 'Cam 6 7047' using bonjour-hap backend!
[11/03/2021, 10:35:57] Cam 6 7047 is running on port 45973.
[11/03/2021, 10:35:57] Please add [Cam 6 7047] manually in Home app. Setup Code: 853-80-798
Starting to advertise 'Homebridge 2600 2E71' using bonjour-hap backend!
[11/03/2021, 10:35:57] Homebridge v1.3.3 (Homebridge 2600) is running on port 51464.
[11/03/2021, 10:37:40] [Camera FFmpeg] [Cam 6] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[11/03/2021, 10:37:46] [Camera FFmpeg] [Cam 6] FFmpeg exited with code: null and signal: SIGILL (Unexpected)
[11/03/2021, 10:38:10] [Camera FFmpeg] [Cam 6] Stopped video stream.

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

My config is:
{
    "bridge": {
        "name": "Homebridge 2600",
        "username": "0E:A6:6F:98:26:00",
        "port": 51464,
        "pin": "853-80-798"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Cam 6",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i http://user:pwd@IP:port/h264/Cam6/temp.ts",
                        "stillImageSource": "-i http://user:pwd@IP:port/image/Cam6?q=75"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: v7.6.2
* **Homebridge Version**: 1.3.3
* **Homebridge Camera FFmpeg Version**: v3.1.2
* **Homebridge Config UI X Plugin Version**: v4.40.0
* **Operating System**: Raspbian (assumed...)

**Comment by Sunoo** [comment]
Every time a user comes in with these SIGILL issues, they’re on a Pi 0. I’ve never been able to recreate it, but the problem does seem to somehow be related to ffmpeg-for-homebridge.

It looks like you aren’t using audio anyways, so you should be able to use the system version of FFmpeg. `sudo apt install ffmpeg` then set videoProcessor to ffmpeg

**Comment by Gr8hifi** [comment]
Thanks for the very quick reply.  I am running the install for FFMpeg now.  I am very tempted to move to a Pi3.  I just got the 0 a day or two ago and it has free returns.  This is all pretty new to me.  Was fretting the switch from Z-wave to Homekit due to my extensive installation when I came across homebridge.  Liked the size and simplicity of the Pi 0 but definitely not wed to any particular device yet.

**Comment by Sunoo** [comment]
To be clear, this SHOULD work on the Pi 0, and I’ve successfully run it myself on those devices. But some users somehow end up with these SIGILL issues I’ve never been able to reproduce in any of my testing.

That said, if you are going to be doing video transcoding (and not using the copy vcodec), you will likely be happier with a more powerful device than the 0.

**Comment by Gr8hifi** [comment]
Well, I have installed FFmpeg and (believe) I have set the video processor to the FFmpeg.  The video still errors out after about 5-10 seconds on the iPhone.  I get the same error as before.  For the config, it's the same as above but I put "videoProcessor": "FFmpeg" under "stillImageSource".  As for my use case, I would like to see five cameras via homekit.  I do not know how much transcoding is required to do this (not sure what homekit can accept).  I can change my settings at the cameras or in Blue Iris to output different video formats.  VLC is reporting the stream I'm trying to use currently as having the following characteristics (if it matters):  H264-MPEG-4 AVC (part 10) (h264).  1280x720 Frame Rate 1000 (not sure what that's about... camera is 30 fps).

**Comment by Sunoo** [comment]
Case matters in videoProcessor, it needs to be all lowercase. Also, it goes at the same level as the platform item, not under videoConfig,

If your camera is putting out h264 like VLC states, you could also try setting vcodec to copy.

**Comment by Gr8hifi** [comment]
SUCCESS!  below is my exact code where user/pwd/IP/Port/Camera Short Name are all filled in for my use case.  It's slow to open on the iPhone, but, after about 3 seconds, it will start streaming the video.  Thank you so much for your help!

        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "cam6",
                    "videoConfig": {
                        "source": "-i http://user:pwd@IP:port/h264/Camera Short Name/temp.ts",
                        "stillImageSource": "-i http://user:pwd@IP:port/image/Camera Short Name?q=75",
                        "vcodec": "copy"
                    }
                }
            ],
            "platform": "Camera-ffmpeg",
            "videoProcessor": "ffmpeg"
        }

**Comment by Sunoo** [comment]
Great, glad you got it working.
