### ISSUE TITLE
decode_slice_header error

### ISSUE THREAD

**Issue by mrfatboy** [Sunoo/homebridge-camera-ffmpeg#1072]
**Describe The Problem:**
I updated to v3.1.2 and am now seeing the errors in the log attached.  The cameras seem to work as they did before though.  I just wanted to report just in case there could be an underlying issue.

**To Reproduce:**
See normal log output

**Logs:**

![image](https://user-images.githubusercontent.com/3344008/110873385-7c71e680-8286-11eb-9655-6a039b1bd1ee.png)

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
I added more logging during snapshots to help troubleshoot, but apparently it’s particularly noisy for a lot of users. I’m re-evaluating this approach for the next version, and will either hide it by default or add an option to silence it. I am a bit annoyed that FFmpeg seems to consider a lot of things that don’t break anything to be errors though.

Long story short, if things are working as expected, just ignore these errors and v3.1.3 should do something about them.
