### ISSUE TITLE
`[Camera FFmpeg] [Camera11] [error] : Invalid argument Oliver 

### ISSUE THREAD

**Issue by oliverchapple** [Sunoo/homebridge-camera-ffmpeg#1074]
hi 

I keep getting this error  

`[Camera FFmpeg] [Camera11] [error] : Invalid argument
12/03/2021, 20:01:07 [Camera FFmpeg] [Camera11] FFmpeg exited with code: 1 and signal: null (Error)
12/03/2021, 20:01:07 [Camera FFmpeg] [Camera11] Stopped video stream.  and the cameras say no response 

but they show a picture.

thanks Oliver

**Comment by Sunoo** [comment]
Please post your full log and configuration.

**Comment by oliverchapple** [comment]
ok this is what it said so far 

2/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] t=0 0
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] m=video 0 RTP/AVP 96
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=control:trackID=0
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=rtpmap:96 H264/90000
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=x-dimensions:2560,1944
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=framerate:11
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=bitrate:6144
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=fmtp:96 packetization-mode=1;profile-level-id=420029;sprop-parameter-sets=Z2QAMq2EAQwgCGEAQwgCGEAQwgCEO1AUAHr8qA==,aO48sA==
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] a=recvonly
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] 
12/03/2021, 20:15:38 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [verbose] setting jitter buffer size to 500
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] max delay reached. need to consume packet
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] RTP: missed 72 packets
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] max delay reached. need to consume packet
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] RTP: missed 59 packets
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [h264 @ 0xaaab06c78190] [verbose] Reinit context to 2560x1952, pix_fmt: yuv420p
12/03/2021, 20:15:39 [Camera FFmpeg] [Camera11] [h264 @ 0xaaab06c78190] [info] concealing 9897 DC, 9897 AC, 9897 MV errors in I frame
12/03/2021, 20:15:40 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] max delay reached. need to consume packet
12/03/2021, 20:15:40 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] RTP: missed 127 packets
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] max delay reached. need to consume packet
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] RTP: missed 117 packets
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] max delay reached. need to consume packet
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaab06c75100] [warning] RTP: missed 14 packets
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [info] Input #0, rtsp, from 'rtsp://admin:oliver1994@192.168.1.150:554/ch1/0':
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [info]   Duration: N/A, start: 0.100000, bitrate: N/A
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [info]     Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(progressive), 2560x1944 (2560x1952), 20.08 tbr, 90k tbn, 180k tbc
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [NULL @ 0xaaab06cb6290] [error] Unable to find a suitable output format for ''
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] [error] : Invalid argument
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] FFmpeg exited with code: 1 and signal: null (Error)
12/03/2021, 20:15:41 [Camera FFmpeg] [Camera11] Stopped video stream.

**Comment by Sunoo** [comment]
And your config?

**Comment by oliverchapple** [comment]
![Screenshot 2021-03-12 at 20 26 02](https://user-images.githubusercontent.com/42448591/110994853-5c6b2180-8371-11eb-8126-537bd1a72373.png)


here's the config 

thanks Oliver

**Comment by Sunoo** [comment]
What is up with your mapvideo value?

**Comment by oliverchapple** [comment]
I don't know were to find that map video bit

**Comment by Sunoo** [comment]
It’s in the screenshot of your config.

**Comment by oliverchapple** [comment]
you mean the 0.1
bit

**Comment by Sunoo** [comment]
Then share your full logs, and the config you are actually using.

**Comment by oliverchapple** [comment]
this is the full log 12/03/2021, 20:39:19 [TuyaWebPlatform] [Switch 4 Macbook] Characteristic.On - [GET] true
12/03/2021, 20:39:28 [Camera FFmpeg] [Camera11] Snapshot requested: 1280 x 720
12/03/2021, 20:39:28 [Camera FFmpeg] [Camera11] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:oliver1994@192.168.1.150:554/ch1/0 -frames:v 1 -f image2 - -hide_banner -loglevel error
12/03/2021, 20:39:29 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaaea5498f0] error while decoding MB 38 58, bytestream -5
12/03/2021, 20:39:31 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaaea58cf00] error while decoding MB 38 58, bytestream -5
12/03/2021, 20:39:31 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.405 seconds.
12/03/2021, 20:39:31 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
12/03/2021, 20:39:31 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] Snapshot requested: 1280 x 720
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:oliver1994@192.168.1.150:554/ch1/0 -frames:v 1 -f image2 - -hide_banner -loglevel error
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] error while decoding MB 0 60, bytestream 53299
12/03/2021, 20:39:43 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] error while decoding MB 123 20, bytestream -5
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab00412a70] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab00412a70] error while decoding MB 0 60, bytestream 53299
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab006df480] error while decoding MB 123 20, bytestream -5
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.859 seconds.
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
12/03/2021, 20:40:04 [Camera FFmpeg] [Camera11] Snapshot requested: 1280 x 720
12/03/2021, 20:40:04 [Camera FFmpeg] [Camera11] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:oliver1994@192.168.1.150:554/ch1/0 -frames:v 1 -f image2 - -hide_banner -loglevel error
12/03/2021, 20:40:05 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad869a8f0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:40:05 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad869a8f0] error while decoding MB 0 54, bytestream 50615
12/03/2021, 20:40:07 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad8be44a0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:40:07 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad8be44a0] error while decoding MB 0 54, bytestream 50615
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.527 seconds.
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
![Screenshot 2021-03-12 at 20 42 49](https://user-images.githubusercontent.com/42448591/110996279-9fc68f80-8373-11eb-98a0-169ccc354b7d.png) and that is the config

**Comment by Sunoo** [comment]
You say snapshots are working? If it’s video that’s not working, please share logs that include an attempt to stream video.

**Comment by oliverchapple** [comment]
12/03/2021, 20:39:31 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] Snapshot requested: 1280 x 720
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:39:42 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] error while decoding MB 0 60, bytestream 53299
12/03/2021, 20:39:43 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab003228f0] error while decoding MB 123 20, bytestream -5
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab00412a70] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab00412a70] error while decoding MB 0 60, bytestream 53299
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaab006df480] error while decoding MB 123 20, bytestream -5
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.859 seconds.
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
12/03/2021, 20:39:45 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
12/03/2021, 20:40:04 [Camera FFmpeg] [Camera11] Snapshot requested: 1280 x 720
12/03/2021, 20:40:04 [Camera FFmpeg] [Camera11] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:oliver1994@192.168.1.150:554/ch1/0 -frames:v 1 -f image2 - -hide_banner -loglevel error
12/03/2021, 20:40:05 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad869a8f0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:40:05 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad869a8f0] error while decoding MB 0 54, bytestream 50615
12/03/2021, 20:40:07 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad8be44a0] left block unavailable for requested intra4x4 mode -1
12/03/2021, 20:40:07 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaad8be44a0] error while decoding MB 0 54, bytestream 50615
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.527 seconds.
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
12/03/2021, 20:40:08 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 - 

there are the logs for that

**Comment by Sunoo** [comment]
All of those logs are from snapshots, which you say are working as expected?

**Comment by oliverchapple** [comment]
nope just saids no response

**Comment by Sunoo** [comment]
You may need to force quit the Home app to get it to make another attempt.

**Comment by oliverchapple** [comment]
I did try that but did not help

**Comment by Sunoo** [comment]
It won’t fix the problem, but would likely get me meaningful logs.

**Comment by oliverchapple** [comment]
14/03/2021, 14:38:14 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaace1a08f0] error while decoding MB 98 44, bytestream -9
14/03/2021, 14:38:17 [Camera FFmpeg] [Camera11] [Snapshot] [h264 @ 0xaaaace1def00] error while decoding MB 98 44, bytestream -9
14/03/2021, 14:38:17 [Camera FFmpeg] [Camera11] Fetching snapshot took 3.63 seconds.
14/03/2021, 14:38:17 [Camera FFmpeg] [Camera11] Sending snapshot: 1280 x 720
14/03/2021, 14:38:17 [Camera FFmpeg] [Camera11] Resize command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
14/03/2021, 14:38:18 [Front Door] Snapshot request handler provided empty image buffer!
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] Video stream requested: 1280 x 720, 30 fps, 299 kbps
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] Starting video stream: 1280 x 720, 25 fps, 299 kbps
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] Stream command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -re -i mpeg -r 25 -f rawvideo -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 4967652 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libavutil      56. 51.100 / 56. 51.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libavcodec     58. 91.100 / 58. 91.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libavformat    58. 45.100 / 58. 45.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libavdevice    58. 10.100 / 58. 10.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libavfilter     7. 85.100 /  7. 85.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libswscale      5.  7.100 /  5.  7.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libswresample   3.  7.100 /  3.  7.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [info]   libpostproc    55.  7.100 / 55.  7.100
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [tcp @ 0xaaaae9215cc0] [verbose] Starting connection attempt to 192.168.1.150 port 554
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [tcp @ 0xaaaae9215cc0] [verbose] Successfully connected to 192.168.1.150 port 554
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [verbose] SDP:
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] v=0
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] t=0 0
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] m=video 0 RTP/AVP 96
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=control:trackID=0
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=rtpmap:96 H264/90000
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=x-dimensions:2560,1944
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=framerate:11
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=bitrate:6144
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=fmtp:96 packetization-mode=1;profile-level-id=420029;sprop-parameter-sets=Z2QAMq2EAQwgCGEAQwgCGEAQwgCEO1AUAHr8qA==,aO48sA==
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] a=recvonly
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] 
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [verbose] setting jitter buffer size to 500
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 28 packets
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 165 packets
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [verbose] Reinit context to 2560x1952, pix_fmt: yuv420p
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [error] left block unavailable for requested intra mode
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [error] error while decoding MB 0 46, bytestream 74210
14/03/2021, 14:38:22 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [info] concealing 12209 DC, 12209 AC, 12209 MV errors in I frame
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 17 packets
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [error] error while decoding MB 88 115, bytestream -5
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [info] concealing 1081 DC, 1081 AC, 1081 MV errors in P frame
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [h264 @ 0xaaaae9216e60] [warning] Increasing reorder buffer to 1
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 54 packets
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:23 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 142 packets
14/03/2021, 14:38:24 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:24 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 64 packets
14/03/2021, 14:38:24 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] max delay reached. need to consume packet
14/03/2021, 14:38:24 [Camera FFmpeg] [Camera11] [rtsp @ 0xaaaae9213ce0] [warning] RTP: missed 127 packets
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] [info] Input #0, rtsp, from 'rtsp://admin:oliver1994@192.168.1.150:554/ch1/0':
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] [info]   Duration: N/A, start: 0.050000, bitrate: N/A
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] [info]     Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(progressive), 2560x1944 (2560x1952), 20.08 tbr, 90k tbn, 180k tbc
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] [fatal] Stream map '0:1' matches no streams.
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] To ignore this, add a trailing '?' to the map.
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] FFmpeg exited with code: 1 and signal: null (Error)
14/03/2021, 14:38:25 [Camera FFmpeg] [Camera11] Stopped video stream.

that is the log I got of the camera. plugin 

thanks Oliver

**Comment by Sunoo** [comment]
`Stream map '0:1' matches no streams.`

There’s your problem. Your mapping is wrong. Not sure why you’re using maps instead of just letting the plugin figure it out? Your mapaudio seems to point at the video, and mapvideo points at nothing? From the logs, it looks like your camera might not even support audio?
