### ISSUE TITLE
Google Nest Hub via GSH

### ISSUE THREAD

**Issue by rasi-natbuild** [Sunoo/homebridge-camera-ffmpeg#1079]
Does this suppose to work with Google Home also?

I have successfully configured it in Hoobo and then it comes up in Apple HomeKit but not in Google Home.

**Comment by Sunoo** [comment]
I’m very confused as to what you’re asking. I assume “Hoobo” was just a typo of HOOBS, but both Homebridge and HOOBS are for bringing support for devices into Apple’s HomeKit.
