### ISSUE TITLE
TP-Link Tapo C310 - Motion sensor not working

### ISSUE THREAD

**Issue by IonutMindrescu** [Sunoo/homebridge-camera-ffmpeg#1080]
Hi,
I tested the Tapo C310 camera and it's working just fine. I had to use the 360p resolution for the RTSP to make it smooth. The issue is that the motion detection in the Tapo app is activated and the Homebridge option for the motion sensor too but it never triggers. Is there any custom config that I should create to make it work?

**Comment by Sunoo** [comment]
You need to configure something to trigger the motion in the plugin: https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

**Comment by IonutMindrescu** [comment]
Thanks @Sunoo , I managed to configure it and it's working just fine 👍

**Comment by Sunoo** [comment]
Great to hear!

**Comment by RMSTrebor** [comment]
@IonutMindrescu do you have your solution for me?
