### ISSUE TITLE
Seeing error messages in the log since upgrading to v3.1.2

### ISSUE THREAD

**Issue by mantorok1** [Sunoo/homebridge-camera-ffmpeg#1082]
**Describe The Problem:**
Since upgrading to v3.1.2 of the plugin I see error messages in the Homebridge logs for one of my cameras (HikVision Villa Door Station). The snapshots, live video & audio of the camera still work correctly in the Home app though. This camera does not have a still image store.

My other cameras do not show the error but they do have a still image store. Not sure if that has anything to do with it.

**To Reproduce:**
In the iOS Home app go to a room that has the "Intercom Cam" camera

**Logs:**
```
[3/20/2021, 8:19:16 PM] [Camera FFmpeg] [Intercom Cam] [Snapshot] [h264 @ 0x558fd1cab200] non-existing PPS 0 referenced
[3/20/2021, 8:19:16 PM] [Camera FFmpeg] [Intercom Cam] [Snapshot]     Last message repeated 1 times
[3/20/2021, 8:19:16 PM] [Camera FFmpeg] [Intercom Cam] [Snapshot] [h264 @ 0x558fd1cab200] decode_slice_header error
[3/20/2021, 8:19:16 PM] [Camera FFmpeg] [Intercom Cam] [Snapshot] [h264 @ 0x558fd1cab200] no frame!
```

**Homebridge Config:**

```json
        {
            "name": "Intercom Cam",
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://user:password@192.168.1.201:554/Streaming/Channels/101/",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "maxBitrate": 512,
                "audio": true
            }
        }
```

**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**: v1.3.4
* **Homebridge Camera FFmpeg Version**: v3.1.2
* **Homebridge Config UI X Plugin Version**: v4.40.0
* **Operating System**: Docker (Alpine Linux 3.11.6)

**Comment by Sunoo** [comment]
As long as the camera is still working, this can be safely ignored. I added additional logging to 3.1.2 to try to help point out issues, but apparently a lot of cameras generate a lot of errors while still working.

Whenever I have a chance to release the next version, it should have a setting to hide these messages.

**Comment by mantorok1** [comment]
Thanks @Sunoo, having that setting would be great.
