### ISSUE TITLE
Tested configuration for ihoumi AJCloud camera

### ISSUE THREAD

**Issue by albertoxamin** [Sunoo/homebridge-camera-ffmpeg#1086]
**Manufacturer/Model:**

(ihoumi) AJ Cloud camera, might also work for wansview cameras.
you have to enable rtsp from the AJcloud app where you will also find the credentials that you can also change.

**Homebridge Config:**

```json
{
  "name": "Cancello Ingresso",
  "unbridge": true,
  "videoConfig": {
    "source": "-rtsp_transport tcp -i rtsp://USERNAME:PASSWORD@IPADDRESS:554/live/ch1"
  }
}
```

**Additional Information:**

`/live/ch1` is for 720p
`/live/ch0` is for 1080p

I guess ihoumi is just a reseller for these cameras that use the app AJ Cloud

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/ihoumi-AJ-Cloud-camera.html
