### ISSUE TITLE
[Camera FFmpeg] [error] Error while decoding stream

### ISSUE THREAD

**Issue by Jer-emy** [Sunoo/homebridge-camera-ffmpeg#1091]
I have an error when I open the stream view as shown in the following log:

> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] Starting video stream: 640 x 480, 30 fps, 299 kbps
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] [mjpeg @ 0x4492c60] [fatal] No JPEG data found in image
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] [mjpeg @ 0x4495260] [fatal] No JPEG data found in image
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] [error] Error while decoding stream #0:0: Invalid data found when processing input
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] [error] Cannot determine format of input stream 0:0 after EOF
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] [fatal] Error marking filters as finished
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] FFmpeg exited with code: 1 and signal: null (Error)
> [25/03/2021, 21:33:26] [Camera FFmpeg] [Camera Animaux] Stopped video stream.

Below, configuration of plugin:

```
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera Animaux",
                    "videoConfig": {
                        "source": "-f mjpeg -i http://user:password@ip_adress:469/monitor.htm",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 30,
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
```

Did you already get this issue?

**Comment by Sunoo** [comment]
Looks like you most likely have the wrong URL for the stream from your camera.

**Comment by Jer-emy** [comment]
Thank you for your fast feedback,
However, I can see the video when I open this URL in web page.

**Comment by Sunoo** [comment]
A web page is not a video stream. You’ll need the URL to the stream, not the web page.

**Comment by Jer-emy** [comment]
Fine, I understand.
I tried to find it but my camera is not present in the list from ispyconnect.com 
Maybe you can help me to find the good one.
My camera is a ClipSonic X95PC

**Comment by Sunoo** [comment]
I do not see the URL for that in a quick search, and all the manufacturer’s documentation is in French, which I do not understand.

**Comment by Jer-emy** [comment]
you can find manufacturer's documentation here: http://cd.ipcam.so/T_PnP_en.html
