### ISSUE TITLE
No Stream from my cameras after updating from 3.1.0 to version 3.1.2

### ISSUE THREAD

**Issue by drheck** [Sunoo/homebridge-camera-ffmpeg#1092]
Hi,

after the update i get no video from my cameras.
Going back to 3.1.0 same error.
So i had to flash my raspberry with a backup...

Error in logfile. 
[27.3.2021, 16:33:24] [Camera FFmpeg] [Kamera Terrasse] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld)
[27.3.2021, 16:33:24] [Camera FFmpeg] [Kamera Terrasse] FFmpeg exited with code: 1 and signal: null (Error)
[27.3.2021, 16:33:24] [Camera FFmpeg] [Kamera Terrasse] Stopped video stream.

Thanks,
Peter

![image](https://user-images.githubusercontent.com/49845838/112726250-aa108e00-8f1c-11eb-96a2-c77916ad29c6.png)

"cameras": [
                {
                    "name": "Kamera Terrasse",
                    "manufacturer": "Hikam",
                    "model": "A72",
                    "motion": false,
                    "switches": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://admin:XXXXXX@192.168.113.36:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 960,
                        "maxFPS": 30,
                        "audio": true,
                        "debug": false
                    }
                },

**Comment by Sunoo** [comment]
I don’t think there was any significant change between 3.1.2 and 3.1.0 in terms of how video should work.

Unfortunately, your logs aren’t really enough to see what would have been the issue. You would need to enable debug on the camera in your config to get useful messages.

**Comment by drheck** [comment]
Hi Sunoo,
here the logfile (daemon.log) after the reboot with 3.1.2.
regards,
Peter
[afterreboot-daemon.log](https://github.com/Sunoo/homebridge-camera-ffmpeg/files/6216129/afterreboot-daemon.log)

**Comment by Sunoo** [comment]
You don’t have FFmpeg installed. What are you running this on?

**Comment by drheck** [comment]
Hm. What do you mean?
I have installed your plugin...
![image](https://user-images.githubusercontent.com/49845838/112730548-80faf800-8f32-11eb-8cfb-69ba91b90560.png)

**Comment by Sunoo** [comment]
If you don’t answer my question, I can’t begin to provide assistance. What are you running this on? A Raspberry Pi? A MacBook? A Windows PC? Some NAS system?

**Comment by drheck** [comment]
Sorry. Raspberry Pi.
![image](https://user-images.githubusercontent.com/49845838/112730722-683f1200-8f33-11eb-8465-4dd462b1ae1d.png)

**Comment by Sunoo** [comment]
FFmpeg should have been installed automatically, not sure why it wasn’t. You can install it manually by following these instructions: https://github.com/homebridge/ffmpeg-for-homebridge#raspbian-linux

**Comment by drheck** [comment]
Hi David,

thanks a lot. This workaround was good.
I will see what happens with the next update….

Regards,
Peter

Mit freundlichen Grüßen
   Dr.-Ing. Peter Heck
________________________________
Dr.-Ing. Peter Heck
Beethovenstraße 5
67685 Weilerbach
Telefon: +49 6374 993322
Mobiltelefon: +49 172 6124786


Von: David Maher ***@***.***>
Gesendet: Samstag, 27. März 2021 19:37
An: Sunoo/homebridge-camera-ffmpeg ***@***.***>
Cc: drheck ***@***.***>; Author ***@***.***>
Betreff: Re: [Sunoo/homebridge-camera-ffmpeg] No Stream from my cameras after updating from 3.1.0 to version 3.1.2 (#1092)


FFmpeg should have been installed automatically, not sure why it wasn’t. You can install it manually by following these instructions: https://github.com/homebridge/ffmpeg-for-homebridge#raspbian-linux
