### ISSUE TITLE
videoConfig section is missing from the config

### ISSUE THREAD

**Issue by pravinkv** [Sunoo/homebridge-camera-ffmpeg#1094]
**Describe The Problem:**
One of your cameras has no name configured. This camera will be skipped.
videoConfig section is missing from the config. 

Is there anything wrong in the below;

[
    {
        "platform": "Camera-ffmpeg",
        "cameras": [
            {
                "name": "abc",
                "videoConfig": {
                    "source": "-i rtsp://admin:xxxxx@192.168.1.250:554/Streaming/Channels/101",
                    "stillImageSource": "-i http://example.com/still_image.jpg",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 30
                }
            }
        ]
    }
]

This is the error I am getting, any help appreciated.

Thankyou

**To Reproduce:**

**Logs:**
30/03/2021, 13:46:23 Loaded plugin 'homebridge-camera-ffmpeg'
30/03/2021, 13:46:23 [3/30/2021, 2:16:23 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
30/03/2021, 13:46:23 Loading 1 platforms...
30/03/2021, 13:46:23 [cam1] Initializing Camera-ffmpeg platform...
30/03/2021, 13:46:23 [cam1] One of your cameras has no name configured. This camera will be skipped.
30/03/2021, 13:46:23 [cam1] The videoConfig section is missing from the config. This camera will be skipped.
30/03/2021, 13:46:23 Preparing Advertiser for 'HOOBS A559' using bonjour-hap backend!
30/03/2021, 13:46:23 Starting to advertise 'HOOBS A559' using bonjour-hap backend!
30/03/2021, 13:46:23 Bridge is running on port 51826.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
I’m guessing that there is something wrong with your config.json as a whole. Please share the full file.
