### ISSUE TITLE
able to load snapshot, but not stream

### ISSUE THREAD

**Issue by shieldsmicah** [Sunoo/homebridge-camera-ffmpeg#1100]
**Describe The Problem:**

Snapshot shows up in home app, but stream does not load. Log says "ffmpeg exited with code 1 and signal null (error)" instantly when the video feed is clicked.

**To Reproduce:**

Fresh install of centos 7, installed homebridge-camera-ffmpeg with homebridge UI. Trying to connect to a camera in zoneminder.

**Logs:**

Shown in Screenshots below
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**
{
    "bridge": {
        "name": "Homebridge 6F2B",
        "username": "0E:52:69:41:6F:2B",
        "port": 51086,
        "pin": "114-08-864"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "en",
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "redacted",
                "cookies": redacted"
            },
            "platform": "Nest"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "LivingRoomCam",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-re -i https://zoneminder.redacted.com/cgi-bin-zm/nph-zms?mode=jpeg&monitor=2&scale=100&maxfps=15&buffer=1000&user=redacted&pass=redacted",
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}
```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/50371267/113660160-831b3000-9671-11eb-8069-b30ff2dd1a40.png)

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: v6.14.11
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg Version**: v3.1.2
* **Homebridge Config UI X Plugin Version**: v4.41.0
* **Operating System**: Centos7

**Comment by shieldsmicah** [comment]
Also forgot to mention - not sure if this is normal, but after installing, nothing worked at all. I needed to install ffmpeg via epel and so I'm using ffmpeg version 3.4.8.

**Comment by Sunoo** [comment]
You appear to be using a rather old version of FFmpeg, if you use a more recent version, it should work. You won’t have audio support unless you compile it yourself though.

**Comment by shieldsmicah** [comment]
@Sunoo Thanks so much for the reply. That is the latest version in the epel repo. I’ll try to learn tomorrow how to compile the latest version myself and give it a try. Thanks again for all you do!

**Comment by Sunoo** [comment]
Try pulling down the FFmpeg for Homebridge project and running the build-ffmpeg script.

https://github.com/homebridge/ffmpeg-for-homebridge

**Comment by shieldsmicah** [comment]
Thanks! I had some issues installing that on centos7 .. so I installed a static one from https://johnvansickle.com/ffmpeg/

**Comment by Sunoo** [comment]
Great, glad this was resolved.
