### ISSUE TITLE
Wyze Cam v2 and Pan on Hoobs 3/4

### ISSUE THREAD

**Issue by recoi1er** [Sunoo/homebridge-camera-ffmpeg#1114]
**Manufacturer/Model:**
Wyze Cam v2 and Pan

**Homebridge Config:**
Hoobs 3-3.3.5
Hoobs 4 (beta)
```json
{
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "CAMERA NAME",
                    "manufacturer": "Wyze",
                    "model": "Wyze Cam v2 OR Pan",
                    "serialNumber": "SERIAL#",
                    "firmwareRevision": "VERSION#",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://USER:PASS@IP/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://USER:PASS@IP/live -vframes 1 -r 1",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxStreams": 2,
                        "audio": true,
                        "vcodec": "copy",
                        "motion": true
                    }
                }
            ],
            "videoProcessor": "ffmpeg"
        }
```

**Additional Information:**

"unbridge" is recommend in the plugin configuration but I could get not any camera to appear in HomeKit until I after I set it to false (or removed it from config), I tested it on bare bones where I removed most of the settings listed above to make sure none of them were in conflict.

If you would like to add more cameras, this is what you config would need to look like:

```json
{
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "CAMERA NAME",
                    "manufacturer": "Wyze",
                    "model": "Wyze Cam v2 OR Pan",
                    "serialNumber": "SERIAL#",
                    "firmwareRevision": "VERSION#",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://USER:PASS@IP/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://USER:PASS@IP/live -vframes 1 -r 1",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxStreams": 2,
                        "audio": true,
                        "vcodec": "copy",
                        "motion": true
                    }
                },
{
                    "name": "CAMERA NAME2",
                    "manufacturer": "Wyze",
                    "model": "Wyze Cam v2 OR Pan",
                    "serialNumber": "SERIAL#2",
                    "firmwareRevision": "VERSION#2",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://USER2:PASS2@IP2/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://USER2:PASS2@IP2/live -vframes 1 -r 1",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxStreams": 2,
                        "audio": true,
                        "vcodec": "copy",
                        "motion": true
                    }
                }
            ],
            "videoProcessor": "ffmpeg"
        }
```

**Comment by jakemauer** [comment]
I can't get them to appear when unbridged either.

**Comment by recoi1er** [comment]
> I can't get them to appear when unbridged either.

The hoobs dev has his unbridge=true and it works for him which is truly bizarre, I even tried a mix of ones with it true and false and only the false ones show up.

**Comment by jakemauer** [comment]
Do you have the child bridge enabled?

**Comment by recoi1er** [comment]
> Do you have the child bridge enabled?

What is that?

**Comment by jakemauer** [comment]
Duh sorry I’m using this in a homebridge context not hoobs, so that may not apply.

**Comment by Sunoo** [comment]
I have a potential fix incoming for the issue soon. In the meantime, if you are unable to see the camera in unbridge mode go to Config UI and then Homebridge Settings -> Unpair Bridges / Cameras / TVs / External Accessories, then hit the trash can next to the name of your cameras and restart Homebridge.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Wyze-Cam-v2-and-Pan.html

**Comment by jakemauer** [comment]
> I have a potential fix incoming for the issue soon. In the meantime, if you are unable to see the camera in unbridge mode go to Config UI and then Homebridge Settings -> Unpair Bridges / Cameras / TVs / External Accessories, then hit the trash can next to the name of your cameras and restart Homebridge.

Hey @Sunoo is there any update on this fix?

**Comment by Sunoo** [comment]
I'm going to be pushing a new version tonight or tomorrow, and this fix is not in it, since the way I had implemented it was a big more fragile than expected. I really hope to have it in the next version though. In the meantime, manually unpairing from the UI should work.
