### ISSUE TITLE
Add logging for Doorbell Pressed

### ISSUE THREAD

**Issue by jsiegenthaler** [Sunoo/homebridge-camera-ffmpeg#1122]
**Is your feature request related to a problem? Please describe:**

I'd like to have a log entry for Doorbell Pressed in my Homebridge logs

**Describe the solution you'd like:**

A log entry that says "Doorbell button pressed"

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Sunoo** [comment]
If you enable debug logging, it should record that sort of information in the logs.

**Comment by jsiegenthaler** [comment]
Yeah but I don't want debug logging running all the time, it floods the logs with gadzillions of log entries from other plugins.
I want to quickly review the log when I think I have a doorbell issue (I use my doorbell a lot with some automation)

**Comment by Sunoo** [comment]
I’ve been toying with the idea of replacing debug with a loglevel, that would possibly solve your issue. I’d have to think about it. It wouldn’t be a high priority if I do it though, I have a bunch of functional fixes and tweaks that I want to get in first.

**Comment by jsiegenthaler** [comment]
OK. Sometimes ffmpeg logs too much... but not what I want ;)

**Comment by Sunoo** [comment]
If you run Homebridge in debug mode, but set debug to false in the plugin config, you’ll get far less logging.

**Comment by jsiegenthaler** [comment]
No, not really. Setting Homebridge Debug on applies to all installed plugins. Some of them log lots and lots of messages in debug mode. So that doesn't help me.

**Comment by Sunoo** [comment]
If you run it with those setting combinations, is the logging just for this plugin acceptable? That should be a fairly easy mix for me to support with a config setting, if the logging amount solves your needs.

**Comment by jsiegenthaler** [comment]
Not all plugins support a per-plugin debug mode.  Mine does. others do not.
I have 14 plugins. 
Some of them flood the logs very heavily when Homebridge is in debug mode. 
Thus running Homebridge in debug mode continuously is not an option.

**Comment by Sunoo** [comment]
That’s all well and good but that’s not what I asked.

If you run Homebridge in debug mode but set debug to false in this plugin’s config, does the amount of logging _**coming from this plugin and this plugin only**_ suit your needs?
