### ISSUE TITLE
Add support for persistent snapshot by using custom characteristic support by Home+ app

### ISSUE THREAD

**Issue by nanosonde** [Sunoo/homebridge-camera-ffmpeg#1125]
The [Home+ app](https://apps.apple.com/de/app/home-5/id995994352) sold in the app store has support for persistent snapshots of camera pictures.
See details here: https://github.com/brutella/hkcam/blob/master/SNAPSHOTS.md
It is realized by a custom HomeKit characteristic. 

The snapshots are stored locally on the camera. And the Home+ app provides a way of showing a list of those snapshots.
See the description of the feature here on this page: https://hochgatterer.me/hkcam/

Would it be possible to implement support for this custom HomeKit characteristic into this plugin as well?
It is somehow a good alternative to Homekit Secure Video as everything is stored locally.
Maybe one could convince other app developers to support this characteristic too. (ok, maybe not Apple themselves.)

**Comment by Sunoo** [comment]
I’ll give this some thought. It’d definitely be possible, but the primary goal of this was to bring camera support to Apple’s Home app, which is unlikely to ever support such a feature.

If I do implement this, it’d be a bit, as there are some fixes I need to get in place before I even look into adding this.

**Comment by Sunoo** [comment]
Jeez, looks like Home+ is $15 too, not sure how many people would even be willing to pay that much for such an app. I certainly don’t feel great about having to spend that just to be able to write support for their app.

**Comment by nanosonde** [comment]
Yes, you are right. The price is quite high. Especially if you also consider that 3rd-party Homekit do not have access to TV or HomePod equipment.

It was just an idea…

I also contacted the author of another app: Controller for Homekit. I am interested in his point of view, too.

**Comment by Sunoo** [comment]
I spoke briefly with SeydX, developer of the Camera UI plugin, and he seems interested in potentially adding it to that. In my mind, it’s a better fit there than here anyways.

**Comment by nanosonde** [comment]
Ok. Thanks for considering.
