### ISSUE TITLE
Camera's not working - Stays on initializing Camera-ffmpeg platform....

### ISSUE THREAD

**Issue by M0untainD3w** [Sunoo/homebridge-camera-ffmpeg#1126]
**Describe The Problem:**
To start off and be completely open: I am very new to this so my apologies in advance if I ask/say anything stupid.

I am trying to get the plugin to work on HOOBS but whatever configuration I try, the plugin won't start. And the log shows initializing Camera-ffmpeg platform.

No matter what, the logs freezes at:

15/05/2021, 12:53:52 [Camera FFmpeg] Initializing Camera-ffmpeg platform...

**To Reproduce:**

I have tried two different camera's, Foscam C1 and a EZVIZ C1C and both do not work. Both work fine with the RTSP stream on VLC but if I use the example config (in the instructions) or the known config to work (for the EZVIZ), it just does not work.
It stays on initializing....

I have also installed ffmpeg with: wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -

But no luck.

**Logs:**

It only says this (and service does not start):

15/05/2021, 12:53:52 [Camera FFmpeg] Initializing Camera-ffmpeg platform...

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

{
    "platform": "Camera-ffmpeg",
    "cameras": [
        {
            "name": "TST01",
            "videoConfig": {
                "source": "-re -i rtsp://admin:mypassword@192.168.0.5:554/h264_stream",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "vcodec": "h264_omx"
            }
        }
    ]
}

<img width="853" alt="image" src="https://user-images.githubusercontent.com/83986814/118358174-f15ee680-b57d-11eb-9b81-9b858822c194.png">

**Screenshots:**

**Environment:**

* **Node.js Version**: 14.16.0
* **NPM Version**: ??
* **Homebridge Version**: HOOBS 3.3.5
* **Homebridge Camera FFmpeg Version**: 3.1.2
* **Homebridge Config UI X Plugin Version**: N/A
* **Operating System**: HOOBS

**Comment by mkellsy** [comment]
Try turning on un-bridged for the camera.

**Comment by M0untainD3w** [comment]
Ok, I am an idiot :-)
Being new on this I did not understood the way to use the config file like opening with [ and closing with ]

That being said, after I got this working, I ran into some other issues:

- vcodec on copy worked well, only not on my iPads
- with vcodec on h264_omx, it worked on all devices but the quality was terrible. I also noticed the quality stayed bad, no matter what I used in the Width and Height Section OR bitrate. Reason was that it adjusted to whatever homekit was asking. Using "forceMax" solved this issues. This forces the stream to be on the quality I want.

The below config works like a charm, fluent video, no stuttering. Image quality good and working on all devices.

{
        "name": "Camera name",
        "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://username:password@ip_address:554/h264_stream",
            "stillImageSource": "-re -i rtsp://username:password@ip_address:554/h264_stream -vframes 1 -r 1",
            "maxStreams": 8,
            "maxWidth": 1920,
            "maxHeight": 1080,
            "forceMax": true,
            "maxFPS": 15,
            "vcodec": "h264_omx",
            "maxBitrate": 1500,
            "packetSize": 752,
            "videoFilter": "none",
            "audio": true,
            "debug": false
        }

**Comment by Sunoo** [comment]
Great, glad you got it working!
