### ISSUE TITLE
iPCamera - High-End NetworkCam

### ISSUE THREAD

**Issue by kalebakeits** [Sunoo/homebridge-camera-ffmpeg#1127]
**iPCamera - High-End NetworkCam:**

iPCamera - High-End NetworkCam (iOS App)

**Homebridge Config:**

```json
{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Bedroom View",
                    "videoConfig": {
                        "source": "-i http://10.211.xxx.xxx/live",
                        "stillImageSource": "-i http://10.211.xxx.xxx/live",
                        "maxStreams": 2,
                        "maxWidth": 480,
                        "maxHeight": 360,
                        "maxFPS": 30
                    }
                }
            ]
        }
```

**Additional Information:**

You don't need to specify a port for this camera just http://{camera ip}/live. I am using mine without a password at the moment so I cannot advise on that. I know it is risky.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/iPCamera.html
