### ISSUE TITLE
D-link DCS-942L

### ISSUE THREAD

**Issue by WaldperlachFabi** [Sunoo/homebridge-camera-ffmpeg#1129]
Its for D-link DCS-942L.
You can yeah the sound from the camera and you can see the image.

**Homebridge Config:**

```json
 {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "D-link",
                    "motionDoorbell": true,
                    "doorbell": true,
                    "switches": true,
                    "videoConfig": {
                        "stillImageSource": "-i https://xxx.xxx.xxx.xx/image/jpeg.cgi",
                        "source": "-i rtsp://xxx.xxx.xxx.xx/play1.sdp",
                        "maxWidth": 640,
                        "audio": true,
                        "maxHeight": 480
                    },
                    "motion": true
                }
            ]
        }
```

xxx.xxx.xxx.xx is the IP address from your camera..

**Additional Information:**

Please set up in the camera settings that you dont need a passwort for rtsp stream and the photo.

Sorry that the photos are in German. But I think you can see what you have to adjust.

![IMG_2303](https://user-images.githubusercontent.com/80318133/118520280-3c255d80-b73a-11eb-992c-6726d5436fa1.jpeg)

![IMG_2304](https://user-images.githubusercontent.com/80318133/118520313-42b3d500-b73a-11eb-957b-07f7fa8943b1.jpeg)

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/D-Link-DCS-942L.html
