### ISSUE TITLE
raspberry pi camera noir can't be flipped

### ISSUE THREAD

**Issue by tenpn** [Sunoo/homebridge-camera-ffmpeg#1131]
I have a pi running homebridge, with a camera noir attached. because of the way it's mounted I need to flip the image vertically. 

I added `"vlip": true` to no effect. I added `-vf vflip` to the end of both stillImageSource and source -- it flipped the still image but not the video feed. 

any idea how to set this up to vertically flip?

**Homebridge Config:**

```json
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "camnoir",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-re -f video4linux2 -i /dev/video0",
                        "stillImageSource": "-f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxBitrate": 2048,
                        "forceMax": true,
                        "vcodec": "h264_omx",
                        "encoderOptions": "-preset ultrafast -tune zerolatency"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
```

**Environment:**

* **Node.js Version**: v14.16.1 
* **NPM Version**: v7.11.1 
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg Version**: v3.1.2 
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
To clarify, you’re trying to flip like a mirror, not rotate the image 180 degrees, right?

**Comment by tenpn** [comment]
@Sunoo it's just that the camera is mounted upside down - I think rotating 180 would be much more fitting! I just latched on to flip because that's what I noticed in the code. is rotating possible, then?

**Comment by Sunoo** [comment]
It’s possible. It’s been a minute, but I believe you need to set videoFilter to `transpose=2,transpose=2`.

**Comment by tenpn** [comment]
Ah "videoFilter": "rotate=PI" did it! Apologies for going down the wrong rabbit hole. Thanks for your help!

**Comment by Sunoo** [comment]
No worries, glad it was resolved.
