### ISSUE TITLE
One of your cameras has no name configured

### ISSUE THREAD

**Issue by jmpedron** [Sunoo/homebridge-camera-ffmpeg#1135]
6/9/2021, 11:25:27 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
6/9/2021, 11:25:27 PM [Camera FFmpeg] One of your cameras has no name configured. This camera will be skipped.
6/9/2021, 11:25:27 PM [Camera FFmpeg] The videoConfig section is missing from the config. This camera will be skipped.

```json
[
    {
        "platform": "Camera-ffmpeg",
        "cameras": [
            {
                "name": "Test",
                "videoConfig": {
                    "source": "-re -i rtsp://192.168.4.8:554/live0",
                    "maxStreams": 2,
                    "maxWidth": 1920,
                    "maxHeight": 1080,
                    "videoFilter": "scale=1280:720"
                }
            }
        ]
    }
]
```

**Comment by Sunoo** [comment]
I don't see anything obviously wrong with this section, perhaps it is in the wrong place in your config? Would it be possible to share your entire config.json?

Also, while not the problem you're here about, your videoConfig section is confusing. Why are you forcing a filter to resize to 1280x720 but then also setting the max resolution to 1920x1080?

**Comment by jmpedron** [comment]
I checked out the config.json. I got it to work by changing it to:

[
    {
        "name": "Test",
        "videoConfig": {
            "source": "-re -i rtsp://192.168.4.8:554/live0",
            "maxStreams": 2,
            "maxWidth": 1920,
            "maxHeight": 1080,
            "videoFilter": "scale=1280:720",
            "debug": true
        }
    }
]

Just copied the eufy cam config but it's not working.

6/10/2021, 12:14:32 AM [Camera FFmpeg] [Test] Video stream requested: 1280 x 720, 30 fps, 299 kbps
6/10/2021, 12:14:32 AM [Camera FFmpeg] [Test] Starting video stream: 1280 x 720, 30 fps, 299 kbps
6/10/2021, 12:14:32 AM [Camera FFmpeg] [Test] Stopped video stream.
