### ISSUE TITLE
[homebridge-camera-ui] ENOENT: no such file or directory, open '/usr/lib/node_modules/homebridge-camera-ui/homebridge-ui/public/index.html'

### ISSUE THREAD

**Issue by Jacksonbm1** [Sunoo/homebridge-camera-ffmpeg#1139]
**Describe The Problem:**
Uninstalled and reinstalled the plugin and now I'm getting a weird error (see logs)

**To Reproduce:**
See my config

```
**Logs:**
[homebridge-camera-ui] ENOENT: no such file or directory, open '/usr/lib/node_modules/homebridge-camera-ui/homebridge-ui/public/index.html'
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
           "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "AC camera",
                    "unbridge": true,
                    "debug": true,
                    "videoConfig": {
                        "source": "-i rtsp://<I HAVE AN IP THAT WORKS>/mjpeg/1",
                        "maxFPS": 0,
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
```

**Screenshots:**
null

**Environment:**

* **Node.js Version**: v14.17.0
* **NPM Version**: 7.17.0
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg Version**: 3.1.2
* **Homebridge Config UI X Plugin Version**: 4.41.1
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
I’m confused, are you using homebridge-camera-ui or homebridge-camera-ffmpeg?

**Comment by Jacksonbm1** [comment]
ffmpeg. Why? does my config imply UI? I briefly tried it and removed it. Maybe it didn't uninstall properly?

**Comment by Sunoo** [comment]
Yes, the error is mentioning homebridge-camera-ui. If you can’t uninstall it, I guess try installing and removing that again?

**Comment by Jacksonbm1** [comment]
Very weird, I tried doing that and now it's still giving me the weird error. I also tried using npm uninstall homebridge-camera-ui

which resulted in 
```
removed 100 packages, and audited 1 package in 2s

found 0 vulnerabilities
```

I'm going to try to see if I can revert my config to earlier

**Comment by Jacksonbm1** [comment]
bizarre, still no go.

**Comment by Jacksonbm1** [comment]
But the error doesn't seem to cause any problems either... So i guess it's not a huge deal, just annoying.

**Comment by Sunoo** [comment]
Might be worth opening an issue on the Camera UI project, see if SeydX has seen anything like it.
