### ISSUE TITLE
homebridge-camera-ffmpeg in standalone mode

### ISSUE THREAD

**Issue by alexwala** [Sunoo/homebridge-camera-ffmpeg#1143]
Having a raspberry pi (zero) which should act as a HomeKit camera only.
Is it possible to use homebridge-camera-ffmpeg in standalone mode, eg like homebridge-camera-rpi, without installing full Homebridge ?

**Comment by Sunoo** [comment]
I’m not sure I understand what the benefit of that would be?

**Comment by alexwala** [comment]
To minimize memory consumption...

**Comment by Sunoo** [comment]
I can’t think of a scenario where you’d be so memory constrained that just running HAP-NodeJS instead of Homebridge would make any sort of difference. Especially given that the system would have to still be powerful enough (and have enough memory) to process the video stream from the camera.

**Comment by NorthernMan54** [comment]
@alexwala I believe oznu has already answered this in https://github.com/homebridge/homebridge/issues/2944#issuecomment-868255669

**Comment by alexwala** [comment]
thanks a lot !
