### ISSUE TITLE
FFmpeg process creation failed: spawn FFmpeg ENOENT

### ISSUE THREAD

**Issue by paholme** [Sunoo/homebridge-camera-ffmpeg#1144]
Not sure what im doing wrong but im getting the following error while trying to add a Samsung Smart Cam.

FFmpeg process creation failed: spawn FFmpeg ENOENT

I used this configuration.
```json
[
    {
        "platform": "Camera-ffmpeg",
        "name": "Garage Cam",
        "videoConfig": {
            "source": "-re -i rtsp://192.168.1.11:554/profile1/media.smp",
            "maxStreams": 2,
            "maxWidth": 1920,
            "maxHeight": 1080,
            "videoFilter": "scale=1280:720",
            "debug": true
        }
    }
]


Im using Hoobs

Any assistance would be appreciated

**Comment by Sunoo** [comment]
Looks like you don’t have FFmpeg for some reason. What system are you running HOOBS on?

**Comment by paholme** [comment]
It’s on Linux. 

I did reinstall Ffmpeg but I’m still getting the same error.

**Comment by Sunoo** [comment]
Linux on what?

**Comment by paholme** [comment]
Its on a raspberry pi.

**Comment by Sunoo** [comment]
Odd, the Raspberry Pis should all be supported by ffmpeg-for-homebridge, so it should be automatically pulled in. You could try installing FFmpeg from apt and setting videoProcessor to “ffmpeg”, but that won’t support audio.

**Comment by sravich1** [comment]
Hi,
I am a trying to run the rpos code in Rasppi4 ..when I run the rpos.js I am getting following error
rtspServer error: Error: spawn ./bin/rtspServer ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./bin/rtspServer',
  path: './bin/rtspServer',
  spawnargs: [Array]
}

looks like rtsp server is unable to start...need to know what changes need to be made in addition to all the installation done.
Kindly let me know .
Thanks
Ravi
