### ISSUE TITLE
Suspend Motion Sensor

### ISSUE THREAD

**Issue by tkffaul** [Sunoo/homebridge-camera-ffmpeg#1146]
@Sunoo, This might be a Pull Request, but I wanted to know if there was a way to suspend the dummy switches so when I'm outside my house I can suspend notifications from the cameras? I know I can make a dummy switch and add a timer, but I cant seem to find anything on how to make it work with the dummy switches hooked into camera-ffmpeg. My ideal situation would be to flip a switch and have it stop notifications for say an hour and have the switch auto reset back to on. Is there a way to do this in the software?

**Comment by Sunoo** [comment]
Is there a reason you couldn’t set notifications to only fire when you’re away? Or am I misunderstanding your request?

**Comment by tkffaul** [comment]
If I'm home but lets say asleep... or I leave but my wife is there doing something in the basement... we still want notifications... but if we decide to hang out on the deck, I'd like to turn then off. These are really automation options... (there are no conditional options). So I thought having a switch somewhere in the home app (driven by Homebridge) to just say no notifications from camera "x" for a set time would be nice (almost like a disable mqtt for an hour). I'm thinking timer because the kids, being kids, will forget to turn it back on if they're hanging out outside.

**Comment by NorthernMan54** [comment]
@tkffaul One potential approach is to leverage node-red and create a dummy switch their to gate the flow from your motion sensors to the dummy motion switches on the camera.

motion sensor --> gate --> camera dummy switches

And control the gate with an additional dummy switch

This is the gate control for node-red

https://flows.nodered.org/node/node-red-contrib-simple-gate

**Comment by tkffaul** [comment]
I used node-red as suggested and it works great! A little tricky learning it the first time, but once you pick it up its pretty easy to configure.
