### ISSUE TITLE
Cameras appear zoomed in randomly

### ISSUE THREAD

**Issue by Christofo** [Sunoo/homebridge-camera-ffmpeg#1149]
**Describe The Problem:**

My camera outputs 2560x1920. Sometimes when viewing the cameras, they are "cut off". They appear zoomed in. The problem seems to happen on snapshot and video. 

**To Reproduce:**

Setup a 2560x1920 camera using my settings below, and view them several times. 

**Logs:**

```
N/A
```

**Homebridge Config:**

I know a videoFilter should do nothing here, but without it the cameras always appear to be zoomed in rather than being intermittent.

```json
            "videoConfig": {
                "source": "-rtsp_transport tcp -i rtsp://<>:554/Sms=2.unicast",
                "stillImageSource": "-i http://<>cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=&password=",
                "maxWidth": 1920,
                "maxHeight": 1080,
                "forceMax": true,
                "preserveRatio": true,
                "vcodec": "copy",
                "videoFilter": "scale=1920:1080",
                "audio": true
            }
```

**Screenshots:**

Displaying wrong:
<img width="385" alt="Screen Shot 2021-06-30 at 6 48 48 PM" src="https://user-images.githubusercontent.com/3227962/124040903-d16f6f00-d9d3-11eb-80d1-4e9b60080935.png">

Displaying correctly:
<img width="383" alt="Screen Shot 2021-06-30 at 6 56 18 PM" src="https://user-images.githubusercontent.com/3227962/124041453-dc76cf00-d9d4-11eb-94b9-4b9dfd564686.png">

**Environment:**

* **Node.js Version**: v14.17.1
* **NPM Version**: v6.14.13
* **Homebridge Version**: v1.3.4 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: Docker

**Comment by Sunoo** [comment]
That’s an odd one, I haven’t seen that myself, but I haven’t done too much testing with resolutions above 1080p. I have recently acquired a camera that runs at that resolution, so I’ll see if I can reproduce it when I have a chance.

I do see you’re using the copy vcodec setting though, which causes my plugin to completely ignore many of the settings you have in your config (maxWidth, maxHeight, forceMax, and videoFilter). That makes it even stranger that you say setting videoFilter seems to clear the issue. Also, preserveRatio was removed in version 3.0.0 and is now the default.
