### ISSUE TITLE
Cannot open audio device

### ISSUE THREAD

**Issue by madcat-nl** [Sunoo/homebridge-camera-ffmpeg#1150]
First of all, thank you very much for this amazing 'Baby cam' :)
I have a logitech C925e camera with mic connected to a raspberry pi
just video works fine, but i cannot get audio working, which would kinda a nice feature for a baby cam :)

arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: C925e [Logitech Webcam **C925e**], device **0**: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

unname -a
Linux rpi6 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux

configuration with video and audio via alsa, i'm trying
-i /dev/video0 -f alsa -ac 2 -i hw:CARD=C925e,DEV=0

but it gives me this error:
7/4/2021, 1:35:56 PM] Homebridge v1.3.4 (Homebridge 5410) is running on port 51468.
[7/4/2021, 1:36:02 PM] [Camera FFmpeg] [Baby] Starting video stream: 1920 x 1080, 30 fps, 2000 kbps
[7/4/2021, 1:36:03 PM] [Camera FFmpeg] [Baby] **[alsa @ 0x316a5a0] [error] cannot open audio device hw:CARD=C925e,DEV=0 (No such file or directory)**
[7/4/2021, 1:36:03 PM] [Camera FFmpeg] [Baby] [error] **hw:CARD=C925e,DEV=0: Input/output error**
[7/4/2021, 1:36:03 PM] [Camera FFmpeg] [Baby] FFmpeg exited with code: 1 and signal: null (Error)

when just use video, it works fine:
-i /dev/video0 -f alsa -ac 2 
[7/4/2021, 1:42:30 PM] [Camera FFmpeg] [Baby] Starting video stream: 1920 x 1080, 30 fps, 2000 kbps
[7/4/2021, 1:42:45 PM] [Camera FFmpeg] [Baby] Stopped video stream.

the mic works just fine when i try to record via the command line:
ffmpeg -f alsa -ac 2 -i hw:CARD=C925e,DEV=0 test.wav

Input #0, alsa, from 'hw:**CARD=C925e,DEV=0**':
  Duration: N/A, start: 1625400333.175356, bitrate: 1024 kb/s
    Stream #0:0: Audio: pcm_s16le, 32000 Hz, stereo, s16, 1024 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'testing.wav':
  Metadata:
    ISFT            : Lavf58.20.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 32000 Hz, stereo, s16, 1024 kb/s
    Metadata:
      encoder         : Lavc58.35.100 pcm_s16le
size=    1804kB time=00:00:14.43 bitrate=1024.0kbits/s speed=1x    

using:
homebridge-camera-ffmpeg v3.1.2 
Node.js Versie  v14.17.2
Npm  | v6.14.13
HAP-NodeJS v0.9.4...
homebridge 1.3.4
homebridge-config-ui-x v4.41.1 
ffmpeg version 4.1.6-1~deb10u1+rpt2  the FFmpeg developers built with gcc 8 (Raspbian 8.3.0-6+rpi1)

config:
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Baby",
                    "manufacturer": "Logitech",
                    "model": "C925e",
                    "serialNumber": "0",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-i /dev/video0 -f alsa -ac 2 **-i hw:CARD=C925e,DEV=0**",
                        "stillImageSource": "-f video4linux2 -input_format mjpeg -video_size 1280x720 -i /dev/video0 -frames:v 1",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxBitrate": 2000,
                        "forceMax": true,
                        "vcodec": "h264_omx",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

Is there something extra i need to configure in python to give access to the mic?

**Comment by madcat-nl** [comment]
i see this in the logging:
[7/7/2021, 7:51:56 PM] [Camera FFmpeg] [Baby] ALSA lib conf.c:3683:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (**/build/workspace/lib/alsa-lib/**libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
[7/7/2021, 7:51:56 PM] [Camera FFmpeg] [Baby] ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM hw:CARD=C925e,DEV=0
[7/7/2021, 7:51:56 PM] [Camera FFmpeg] [Baby] [alsa @ 0x40db650] [error] cannot open audio device hw:CARD=C925e,DEV=0 (No such file or directory)
[7/7/2021, 7:51:56 PM] [Camera FFmpeg] [Baby] [error] hw:CARD=C925e,DEV=0: Input/output error
[7/7/2021, 7:51:56 PM] [Camera FFmpeg] [Baby] FFmpeg exited with code: 1 and signal: null (Error)


It looks like it is looking in the wrong directory, because it's here:
/usr/lib/arm-linux-gnueabihf/alsa-lib $ ls libasound_module_conf*
libasound_module_conf_pulse.so

How can i configure Camera FFmpeg so it looks in the correct plugin directory?

Thanks in advance

**Comment by madcat-nl** [comment]
i "solved" it my making an ugly softlink to the correct location:
/build/workspace/lib $ ls -l
total 0
lrwxrwxrwx 1 pi pi 38 Jul  7 20:12 alsa-lib -> /usr/lib/arm-linux-gnueabihf/alsa-lib/

but hey it works, maybe it can help others who encounter the same issue

**Comment by Sunoo** [comment]
What OS and system are you running on? I’m using ALSA on one of my personal setups and didn’t need to do any symlinking.

**Comment by madcat-nl** [comment]
Latest Rasberry pi OS

https://downloads.raspberrypi.org/raspios_full_armhf/release_notes.txt

**Comment by Sunoo** [comment]
That’s what I’m running on my setup. I’ll try to find time to poke around and see if I can spot what’s up after work.

Which model Pi are you running?

**Comment by madcat-nl** [comment]
Raspberry pi 3B (it's a few years old)

**Comment by Sunoo** [comment]
Cool, my setup using ALSA is on a 3A+, which should be pretty close.

**Comment by madcat-nl** [comment]
what i did try is build ffmpeg from scratch but that failed, maybe it created some of these libraries
but these folders are not from a few days ago

/usr/lib/arm-linux-gnueabihf $ ls -l
total 615444
drwxr-xr-x  2 root root     4096 May  7 16:48 alsa-lib

**Comment by Sunoo** [comment]
So after poking at my setup, I couldn’t find any issues.

My best guess at this point is that maybe you have some stuff a bit wonky from when you tried to compile yourself?

**Comment by madcat-nl** [comment]
i had the issue before, but not had debug logging on; so i had no idea why to failed to initialize 
i thought that ffmpeg was broken so i tried to recompile it to solve the issue
then when debugging it i saw that it was pointing in the wrong directory.
for now it's solved and in a few weeks i will forget that it was an ugly fix ;)

for any future visitor: turn on debugging when you have a fresh install to see why it fails to open the device
