### ISSUE TITLE
RTSP works in VLC player but 'No route to host' error in bridge

### ISSUE THREAD

**Issue by praveentcom** [Sunoo/homebridge-camera-ffmpeg#1151]
My RTSP URL is rtsp://praveen:tapocamera@192.168.0.111:554/stream1

I use a Tapo C200 camera and followed the config as suggested by the repo. The stream works flawlessly in the VLC player when tested but is throwing errors in the Homebridge console. Attaching the screenshots of the error and the config. Please correct me if I am using any parameters wrongly.

<img width="1345" alt="Screenshot 2021-07-09 at 5 48 55 PM" src="https://user-images.githubusercontent.com/82172535/125077004-3ca8f780-e0de-11eb-8437-368d78432b53.png">

<img width="738" alt="Screenshot 2021-07-09 at 5 51 24 PM" src="https://user-images.githubusercontent.com/82172535/125077063-4af71380-e0de-11eb-9b16-d93187026e09.png">'

This is from the VLC player:

<img width="1904" alt="Screenshot 2021-07-09 at 5 52 19 PM" src="https://user-images.githubusercontent.com/82172535/125077175-6bbf6900-e0de-11eb-84b7-c7cd471f9cc7.png">

**Comment by praveentcom** [comment]
@Sunoo can look into the issue once you are available?

**Comment by Sunoo** [comment]
If you connect to wherever you are running Homebridge, are you able to `ping 192.168.0.111`?

**Comment by praveentcom** [comment]
It seems like the IP was changed to 192.168.0.110 in the router. I changed it in the homebridge plugin setup, and now it works like a charm! ❤️

![image](https://user-images.githubusercontent.com/82172535/125985892-a32ec919-d814-43a8-8fcc-acb464452b60.jpeg)

**Comment by Sunoo** [comment]
Fantastic, glad you were able to sort it out.

**Comment by fratinize** [comment]
Having the same error from a camera that has worked fine up until a few months ago. It's a Wyze Cam with rstp firmware. 9 cameras In Total, all work fine except one. I can ping from the homebridge server (pi) the Wyze app sees this camera fine. Not sure where else to look ty for any direction

**Comment by Sunoo** [comment]
@fratinize Can you ping the camera from your Homebridge server?

**Comment by fratinize** [comment]
Yes

**Comment by fratinize** [comment]
I
Must apologized I swore I saw a reply no I can not destination Host unreachable 

But why are all other cameras fine?

**Comment by fratinize** [comment]
Third Times the Charm, Sorry (

I can Ping this Camera! 100%

***@***.***:~ $ ping 192.168.1.126
PING 192.168.1.126 (192.168.1.126) 56(84) bytes of data.
64 bytes from 192.168.1.126: icmp_seq=1 ttl=64 time=108 ms
64 bytes from 192.168.1.126: icmp_seq=2 ttl=64 time=23.2 ms
64 bytes from 192.168.1.126: icmp_seq=3 ttl=64 time=1.68 ms
64 bytes from 192.168.1.126: icmp_seq=4 ttl=64 time=4.26 ms
64 bytes from 192.168.1.126: icmp_seq=5 ttl=64 time=4.40 ms
64 bytes from 192.168.1.126: icmp_seq=6 ttl=64 time=2.63 ms
64 bytes from 192.168.1.126: icmp_seq=7 ttl=64 time=3.16 ms
64 bytes from 192.168.1.126: icmp_seq=8 ttl=64 time=3.10 ms
64 bytes from 192.168.1.126: icmp_seq=9 ttl=64 time=4.26 ms
64 bytes from 192.168.1.126: icmp_seq=10 ttl=64 time=7.98 ms
64 bytes from 192.168.1.126: icmp_seq=11 ttl=64 time=6.09 ms
64 bytes from 192.168.1.126: icmp_seq=12 ttl=64 time=8.83 ms
64 bytes from 192.168.1.126: icmp_seq=13 ttl=64 time=3.50 ms

**Comment by fratinize** [comment]
Sorry Found a typo from a Previously restored backup. 
Sorry log it as a
ID10t problem

Enjoy your weekend
