### ISSUE TITLE
macos bigsur screen

### ISSUE THREAD

**Issue by crbyxwpzfl** [Sunoo/homebridge-camera-ffmpeg#1153]
**Manufacturer/Model:**

not a camera I am streaming the macos bigsur screen

**Homebridge Config:**
```json
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "test",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f avfoundation -i 0",
                        "maxStreams": 2,
                        "encoderOptions": "-preset ultrafast",
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Additional Information:**

tested with homebridge on macos bigsur.<br>
for some reason the stream does not work with
 ``"encoderOptions": "-preset ultrafast -tune zerolatency",``<br>
everything except the stream works with this default encoder options even the debug output looks the same just the stream never starts.<br>
has anyone a clue why?

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/macOS-Screen.html
