### ISSUE TITLE
Hikvision DS-2CD2423G0-IW

### ISSUE THREAD

**Issue by guzi2007** [Sunoo/homebridge-camera-ffmpeg#1155]
Hikvision DS-2CD2423G0-IW

"name": "Camera IP",
            "model": "DS-2CD2423G0-IW",
            "serialNumber": "XXX:YYY",
            "firmwareRevision": "V5.5.83 build 190221",
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp://username:password@ipaddress:554",
                "maxStreams": 2,
                "maxWidth": 800,
                "maxHeight": 600,
                "maxFPS": 25,
                "audio": true

maxWidth:800, maxHeight:600, maxPFS:25. If maxWidth or maxHeight is set for more than 800 and 600 respectively or not set at all, the camera does not show the live view.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2423G0-IW.html
