### ISSUE TITLE
LOREX 4K 8 camera system that i am trying to get to show up in Homebridge

### ISSUE THREAD

**Issue by Tesla-P100FX** [Sunoo/homebridge-camera-ffmpeg#1156]
**Describe The Problem:**
I have a LOREX 4K  8 camera system that i am trying to get to show up in Homebridge.  Config is valid but no cameras show up. Am i missing somehing in the config or is the fromat of my cameras wrong?  Does Lorex not support this?    

**Logs:**
```
Show the Homebridge logs here.
Remove any sensitive information.
```
{
    "accessories": [],
    "platforms": [],
    "platform": "Camera-ffmpeg",
    "name": "Camera FFmpeg",
    "porthttp": 8088,
    "localhttp": true,
    "cameras": [
        {
            "name": "Driveway",
            "motion": true,
            "motionTimeout": 0,
            "videoConfig": {
                "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Porch",
            "motion": true,
            "motionTimeout": 0,
            "videoConfig": {
                "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=2&subtype=1"
            }
        },
        {
            "name": "Backdoor",
            "motion": true,
            "motionTimeout": 0,
            "videoConfig": {
                "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=3&subtype=1"
            }
        }
    ]
}
**Screenshots:**

**Environment:**

* **Node.js Version**:  14.17.2
* **NPM Version**: 
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg  3.1.2 
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
I don’t see anything obviously wrong. Are you getting anything in your log?

**Comment by Tesla-P100FX** [comment]
Nope just this 👍 


7/19/2021, 12:03:42 PMCamera FFmpeg Bridge starting
7/19/2021, 12:03:46 PMCamera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
7/19/2021, 12:03:46 PMCamera FFmpeg BridgeBridge is running on port 57826.

**Comment by Sunoo** [comment]
Looking at your confit again, it looks like you have your config in the wrong place:

```json
{
	"accessories": [],
	"platforms": [{
		"platform": "Camera-ffmpeg",
		"name": "Camera FFmpeg",
		"porthttp": 8088,
		"localhttp": true,
		"cameras": [{
				"name": "Driveway",
				"motion": true,
				"motionTimeout": 0,
				"videoConfig": {
					"source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1"
				}
			},
			{
				"name": "Porch",
				"motion": true,
				"motionTimeout": 0,
				"videoConfig": {
					"source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=2&subtype=1"
				}
			},
			{
				"name": "Backdoor",
				"motion": true,
				"motionTimeout": 0,
				"videoConfig": {
					"source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=3&subtype=1"
				}
			}
		]
	}]
}
```

**Comment by Tesla-P100FX** [comment]
Can you be more specific of what i need to change?

**Comment by Sunoo** [comment]
Make what you shared look like what I posted. The config for this plugin needs to be nested under the 'platforms' element.

**Comment by Tesla-P100FX** [comment]
Ha, Yup that was it Thank you!!!!!   Working now

**Comment by Sunoo** [comment]
Fantastic.

**Comment by Tesla-P100FX** [comment]
You did such a great job With this worked great for the last two months.   Last week these Lorex Cameras took a firmware update and now they no longer connect.  I will get some logs and send them?    Have you heard this from anyone else?

**Comment by Sunoo** [comment]
I have not heard that from anyone else yet. Has Lorex provided any information about changed RTSP endpoints or security?

**Comment by Tesla-P100FX** [comment]
I will find out what they changed….


Thanks

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by Tesla-P100FX** [comment]
Sorry my mistake after the firmware update my router assigned it a new IP address .   Working now!  Question however it takes about 15 seconds HomeKit to get a live view.   Anything can do to reduce that time?

**Comment by Sunoo** [comment]
Fantastic, glad it was an easy thing.

You can try adding `-probesize 32 -analyzeduration 0` to the start of your config line, but it may break things. You can also try other values for those two options, something might work for you.

**Comment by Tesla-P100FX** [comment]
Can you show me that within the context of a config.json

**Comment by Sunoo** [comment]
`"source": "-probesize 32 -analyzeduration 0 -i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1"`

**Comment by Tesla-P100FX** [comment]
Thanks I will give it a shot🤣


Thanks

Rich

Sent from my Phone 📞, please excuse typos and amusing  autocorrects


On Sep 10, 2021, at 6:31 PM, David Maher ***@***.***> wrote:

﻿

"source": "-probesize 32 -analyzeduration 0 -i ***@***.***:554/cam/realmonitor?channel=1&subtype=1"

**Comment by FRoss-UA** [comment]
> You can try adding `-probesize 32 -analyzeduration 0` to the start of your config line, but it may break things. You can also try other values for those two options, something might work for you.

Super! Thanks so much for this trick. Now, my 2 Dahua cams starts live video (1080p/20fps) on Homekit like rockets, exactly 1 sec. With standart config opts it was 5-6secs...

**Comment by claudeguillemette** [comment]
> **Describe The Problem:** I have a LOREX 4K 8 camera system that i am trying to get to show up in Homebridge. Config is valid but no cameras show up. Am i missing somehing in the config or is the fromat of my cameras wrong? Does Lorex not support this?
> 
> **Logs:**
> 
> ```
> Show the Homebridge logs here.
> Remove any sensitive information.
> ```
> 
> { "accessories": [], "platforms": [], "platform": "Camera-ffmpeg", "name": "Camera FFmpeg", "porthttp": 8088, "localhttp": true, "cameras": [ { "name": "Driveway", "motion": true, "motionTimeout": 0, "videoConfig": { "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1" } }, { "name": "Porch", "motion": true, "motionTimeout": 0, "videoConfig": { "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=2&subtype=1" } }, { "name": "Backdoor", "motion": true, "motionTimeout": 0, "videoConfig": { "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=3&subtype=1" } } ] } **Screenshots:**
> 
> **Environment:**
> 
> * **Node.js Version**:  14.17.2
> * **NPM Version**:
> * **Homebridge Version**: 1.3.4
> * **Homebridge Camera FFmpeg  3.1.2
> * **Homebridge Config UI X Plugin Version**:
> * **Operating System**:

juste a question for you , the ip address is your nvr address not your camera , asking because my nvr camera are on separate private address .
