### ISSUE TITLE
Turn Picture 90°

### ISSUE THREAD

**Issue by TheMDcraft** [Sunoo/homebridge-camera-ffmpeg#1159]
**The Problem:**
I have an old phone and I‘d like to use it as an IPcamera. I’ve already installed the App “[IPcamera Lite](https://apps.apple.com/de/app/ip-camera-lite/id1013455241)” and it works perfectly! The only thing is, that I want to use it in vertical orientation. I can’t change it to vertical orientation in the App. Can anyone help me, how to change it to vertical orientation via the plugin?

**Homebridge Config:**

```
…
{
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera",
                    "manufacturer": "MD Inc.",
                    "model": "iPhone 7 Plus",
                    "serialNumber": "1234567890",
                    "firmwareRevision": "14.7",
                    "doorbell": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://***.***.***.**:8554/live",
                        "stillImageSource": "-i http://***.***.***.**:8081/video",
                        "maxWidth": 3860,
                        "maxHeight": 3860,
                        "maxFPS": 0,
                        "audio": true,
                        "debug": true,
                        "vcodec": "copy",
                        "forceMax": true,
                        "maxBitrate": "51000",
                        "preserveRatio": false
                    }
                }
            ]
        }
…
```

**Environment:**

* **Node.js Version**: 14.17.2
* **NPM Version**: 6.14.13
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg Version**: 3.1.2
* **Operating System**: HOOBS Core (Raspbian Buster)

Greats 
TheMDcraft

**Comment by Sunoo** [comment]
Set videoFilter to either `transpose=1` or `transpose=2` depending if you you clockwise or counterclockwise. You will also need to stop using the copy vcodec for it to work.
