### ISSUE TITLE
A videoFilter is defined, but the copy vcodec is being used. This will be ignored.

### ISSUE THREAD

**Issue by maisun** [Sunoo/homebridge-camera-ffmpeg#1162]
**Describe The Problem:**

I have defined a videofilter to change the scale to 16:9, the codec is set to copy to improve the performance. My hikvision camera only gives 640X480 as 2nd stream, and it needs to be converted to 640X360 to have proper display. This used to work in the older version of the plugin, and I'd like to avoid transcoding if possible
**To Reproduce:**

When vcodec is set to "copy" and videofilter is set to "scale=640:360"
            {
                    "name": "Kitchen Camera",
                    "motion": true,
                    "motionTimeout": 10,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxxxxxxx@192.168.1.25:554/Streaming/Channels/102/",
                        "stillImageSource": "-i http://admin:xxxxxxxx@192.168.1.25:80/Streaming/Channels/1/picture",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "packetSize": 188,
                        "videoFilter": "scale=640:360",
                        "audio": true,
                        "debug": false
                    }
                }
**Logs:**

WARNING: A videoFilter is defined, but the copy vcodec is being used. This will be ignored.
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**
            {
                    "name": "Kitchen Camera",
                    "motion": true,
                    "motionTimeout": 10,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:xxxxxxxx@192.168.1.25:554/Streaming/Channels/102/",
                        "stillImageSource": "-i http://admin:xxxxxxxx@192.168.1.25:80/Streaming/Channels/1/picture",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "packetSize": 188,
                        "videoFilter": "scale=640:360",
                        "audio": true,
                        "debug": false
                    }
                }
```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 14.17.1
* **NPM Version**: 6.14.13
* **Homebridge Version**: 1.3.4
* **Homebridge Camera FFmpeg Version**: 3.1.2
* **Homebridge Config UI X Plugin Version**: 4.41.2
* **Operating System**: Docker

**Comment by Sunoo** [comment]
When vcodec was set to copy, videoFilter was always ignored. The only recent change was to warn users that was happening instead of just doing it silently.

**Comment by maisun** [comment]
> When vcodec was set to copy, videoFilter was always ignored. The only recent change was to warn users that was happening instead of just doing it silently.

Hi @Sunoo, thanks, maybe my memory is bad but I recall this used to work in an older version of plugin. But I looked into ffmpeg and looks like it was never supported. I now removed the vcodec and it works with transcoding w/o issue.

**Comment by Sunoo** [comment]
Great, glad you’re working.
