### ISSUE TITLE
Firewall rules for video with Home app on different VLAN than homebridge

### ISSUE THREAD

**Issue by ekobres** [Sunoo/homebridge-camera-ffmpeg#1169]
**Describe The Problem:**

I have my IoT devices, including homebridge, segregated to their own VLAN. I have a multicast-relay agent running on my router, and some firewall rules to allow access from my home network to the IoT network and everything works great - except video. Snapshots work. I can get video to work by creating a firewall rule that accepts traffic from the homebridge IP address to my trusted home network - but that pretty much defeats the purpose of isolating the homebridge machine in the IoT network.

Really I just want to know how to create a firewall rule to restrict this traffic without opening up a range of ~16000 ports.

By turning on logging for this firewall rule, I can see that homebridge starts sending UDP traffic in a really wide port range - and netstat from the homebridge machine shows a number of connections open on ports ranging from  ~49000-65500.

**To Reproduce:**

Connect an IOS device with the home app to LAN0 (192.168.0.0/24)
Setup homebridge with this plugin on a LAN11 (192.168.11.0/24) with a supported camera.
Enable mDNS relay between the LANs.
Set firewall rules to accept traffic from LAN0 to LAN11.
Set firewall rules to accept established and related traffic in both directions.
Verify IOS device can see snapshot from camera on LAN11 while connected to LAN0.
Attempt to stream from camera.
Connection Fails.
Create firewall rule to accept all UDP traffic from homebridge IP destined to IOS device on LAN0.
Connection succeeds.

example netstat from homebridge machine (192.168.11.46) to iPhone (192.168.0.105):

```
pi@homebridge:/ $ sudo netstat -nputw | grep 192.168.0.105
tcp6       0      0 192.168.11.46:52108     192.168.0.105:49187     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:41081     192.168.0.105:49179     ESTABLISHED 22644/homebridge: h 
tcp6       0      0 192.168.11.46:52101     192.168.0.105:49176     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:54006     192.168.0.105:49180     ESTABLISHED 22643/homebridge: h 
tcp6       0      0 192.168.11.46:52103     192.168.0.105:49182     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:52102     192.168.0.105:49177     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:52105     192.168.0.105:49184     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:52106     192.168.0.105:49185     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:51826     192.168.0.105:49188     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:52107     192.168.0.105:49186     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:54075     192.168.0.105:49181     ESTABLISHED 22656/homebridge: h 
tcp6       0      0 192.168.11.46:52100     192.168.0.105:49175     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:52104     192.168.0.105:49183     ESTABLISHED 22590/homebridge    
tcp6       0      0 192.168.11.46:55295     192.168.0.105:49178     ESTABLISHED 22650/homebridge: h 
```
**Logs:**

Show the Homebridge logs here.
Remove any sensitive information.

```
[10/08/2021, 17:28:55] [Camera ffmpeg] [SecuritySpy Test] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld)
[10/08/2021, 17:29:04] [Camera ffmpeg] [SecuritySpy Test] Stopped video stream.
**Homebridge Config:**
```
                {
                    "name": "SecuritySpy Test",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://XXX:XXX@192.168.0.142:8080/++video?cameraNum=0",
                        "stillImageSource": "-i http://XXX:XXX@192.168.0.142:8080/++image?cameraNum=0",
                        "audio": true
                    }
                 }
```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* v14.17.4
* **NPM Version**: 
* 7.20.3
* **Homebridge Version**: 
* Initializing HAP-NodeJS v0.9.4...
1.3.4
* **Homebridge Camera FFmpeg Version**:
* v3.1.2
* **Homebridge Config UI X Plugin Version**:
*  v4.41.2
* **Operating System**: 
Raspbian Buster

**Comment by Ewarren7** [comment]
I have similar setup and had to make firewall rule to allow homebridg UPD on 49152-65535 from HB t the other VLAN. 
The reason is bc it is not a single transaction that can be tracked statefully. From what I recall basically Homebridge is responding back to a push request with a new connection. 

Maybe some firewalls could temporarily allow this in response to the request to homebridge. almost like port knocking. But at the same time I don't consider homebridge's ability to send UDP packets on high port ranges to a trusted vlan too big of an exposure. I tend to instead block homebridge from the internet unless I am updating or adding plugins.

**Comment by Sunoo** [comment]
I believe I should be able to add the ability to configure a port range for this plugin to use, I'd have to do some testing to ensure that doesn't upset HomeKit.

Would that resolve the concerns you guys have?

**Comment by ekobres** [comment]
It would definitely be appreciated - especially if we can get the range down to a double-digit number, or at least some deterministic number of ports based on the number of cameras or streams. (Like, maybe 2 open ports for each configured camera - 1 for snapshot and another for video?) 

A range of over 16000 ports really makes you think hard and swallow as you're entering it into a firewall rule.

In reality, the firewall code probably doesn't actually have to work any harder to accept a range versus a single port. 

It may also turn out that the return port could be determined by the firewall someday with SPI, but that since HAP is a fairly new protocol, none of the firewalls understand the frames well enough to add the return ports as "related."

Either way, being able to document a sensible port range would be really handy for anyone like me trying to segment their Homekit node onto a restricted IoT subnet.

Thanks!

**Comment by Sunoo** [comment]
Yea, no real point in having a firewall if you have to open every port.

I believe the most ports you should need is 3 per stream, depending on what functions you have enabled. You would likely want to set a range a bit bigger than you need though, since this doesn’t reserve ports, so some other process could grab a port in the range.

**Comment by ekobres** [comment]
Yeah, I think a lot of what’s possible depends on the iOS, TVOS and MacOS home apps and how much control the accessory bridge has over which ports to use. Since this is a request from the home app for the accessory to push frames to a listening port on the Apple device, the Apple device is the server and it would would be reasonable for it to assume it can use whatever ephemeral ports it wants.

What would be nice would be if Apple could do that in a way that signals a related connection to a firewall.

**Comment by Sunoo** [comment]
Okay, based on my testing, I can't actually influence those ports. I had gotten confused with a different part of the code, since it had been a little bit since I touched that part. I'm stuck using whatever port HomeKit asks for. Sorry about that.

**Comment by ekobres** [comment]
Thanks. I had a feeling the home app would be determining the ports.

I think I at least have the most restrictive rules that are possible at this point. 

It might be nice to have a firewall rules section in the wiki to make this easier for others.

**Comment by Sunoo** [comment]
Documentation is always the hard part. :P

I do need to get an FAQ sort of thing together eventually (hopefully soon) though. I’ll try to write something up for this when I do.
