### ISSUE TITLE
Raspberry Pi with HQ Camera attachment

### ISSUE THREAD

**Issue by hylkefaber** [Sunoo/homebridge-camera-ffmpeg#1172]
**Manufacturer/Model:**
Raspberry Pi HQ Camera  (https://www.raspberrypi.org/products/raspberry-pi-high-quality-camera/) with a Logitech C525 attached (for sound only)

**Homebridge Config:**

"name": "HQ cam",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-re -f video4linux2 -input_format mjpeg -i /dev/video2 -f alsa -ac 1 -i hw:CARD=C525,DEV=0",
                        "stillImageSource": "-f video4linux2 -ss 0.9 -i /dev/video2 -vframes 1",
                        "maxStreams": 3,
                        "maxFPS": 30,
                        "forceMax": false,
                        "encoderOptions": "-preset ultrafast -tune zerolatency",
                        "audio": true,
                        "debug": false
                    }

**Additional Information:**

Adding the C525 changes the address of the HQ cam from /dev/video0 to /dev/video2, so keep that in mind! Also, you need to install ffmpeg-for-homebridge (https://github.com/homebridge/ffmpeg-for-homebridge) to get libfdk-aac support. I did a write-up on Reddit (https://www.reddit.com/r/homebridge/comments/p45wb5/making_a_baby_cam_with_the_raspberry_pi_hq_cam/)

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Raspberry-Pi-HQ-Camera.html

**Comment by merchantzain** [comment]
How does this work without the Logitech C525? I'm having some trouble connecting it with the HQ Camera module alone.

**Comment by hylkefaber** [comment]
I've described my process here, hope this helps you out (https://www.reddit.com/r/homebridge/comments/p45wb5/making_a_baby_cam_with_the_raspberry_pi_hq_cam/). If you don't have a webcam or external mic connected, there's no sound, the HQ cam module doesn't have sound by itself.

**Comment by merchantzain** [comment]
The Reddit post seems to have been removed.

**Comment by hylkefaber** [comment]
Wow, no idea why they did that, anyway here you go: https://imgur.com/a/ljLKJYV

**Comment by merchantzain** [comment]
Following that guide for just the "Part 1: First Steps", I am unable to get a video up and running on my system. Using a Raspberry Pi 4 with Rasbian Buster. I get the following message from Homebridge:

```
[22/11/2021, 22:58:45] [Camera FFmpeg] [HQ Camera] Failed to fetch snapshot.
[22/11/2021, 22:58:48] [Camera FFmpeg] [HQ Camera] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[22/11/2021, 22:58:48] [Camera FFmpeg] [HQ Camera] FFmpeg exited with code: 1 and signal: null (Error)
[22/11/2021, 22:58:48] [Camera FFmpeg] [HQ Camera] Stopped video stream.
```

**Comment by hylkefaber** [comment]
This is why you need the v4l2rtspserver service running. By default, the stream can only be captured by a single process (not sure why). v4l2rtspserver captures this stream and restreams it in a way that allows multiple processes to access the stream, so you have have both snapshots and a live video stream, or even watch the same stream on multiple devices. I've covered the part in the Reddit post at part III.
