### ISSUE TITLE
Amcrest IP5M Motion Detection

### ISSUE THREAD

**Issue by ebowcock** [Sunoo/homebridge-camera-ffmpeg#1177]
**Describe The Problem:**
Unable to get motion detection through the IP5M camera. When enabled, nothing triggers the motion in homebridge.

**Homebridge Config:**

{
            "name": "Camera FFmpeg",
            "porthttp": 8080,
            "cameras": [
                {
                    "name": "Back Deck",
                    "motion": true,
                    "motionTimeout": 600,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://ipandcredentials:554/cam/realmonitor?channel=1&subtype=0",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "vcodec": "copy",
                        "audio": true
                    }
                },

**Comment by Sunoo** [comment]
What are you using to trigger the motion? I assume something that hooks into the HTTP API from your config, but I'd need more information.

**Comment by ebowcock** [comment]
What you see is all I have. I thought the motion option was to detect motion from the camera's built in motion detection. But no additional configurations have been set.
The camera's only built in option for external motion alerting is to send an email.

**Comment by Sunoo** [comment]
> The camera's only built in option for external motion alerting is to send an email.

https://www.npmjs.com/package/homebridge-smtp-motion

**Comment by ebowcock** [comment]
Thank you so much for clarifying that. This explains a lot.
