### ISSUE TITLE
iPhone 5C with app AirBeam

### ISSUE THREAD

**Issue by lazymoose5** [Sunoo/homebridge-camera-ffmpeg#1178]
**Manufacturer/Model:**

Apple 5C running iOS 10.33
iOS app AirBeam

**Homebridge Config:**
{
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "iphone5",
            "manufacturer": "Apple",
            "model": "iPhone 5C",
            "videoConfig": {
                "source": "-i http://192.168.3.8/service/camera/video.mjpeg",
                "maxStreams": 2,
                "maxWidth": 0,
                "maxHeight": 0,
                "maxFPS": 0,
                "audio": false,
                "debug": true
            }
        }
    ],
    "_bridge": {
        "username": "MAC address here",
        "port": 41395
    },
    "platform": "Camera-ffmpeg"
}

**Additional Information:**

Video framerate and quality are set in the Air Beam app. I am using the Homebridge plugin in TrueNAS 12. Installation of ffmpeg through the shell made it work - as it was not available in the jail by default. Use _pkg install ffmpeg_

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/AirBeam.html

**Comment by jotzet79** [comment]
Hi @Sunoo / David,

I got a question regarding split video and audio streams. AirBeam provides 2 Streams: 

1. Video -> service/camera/video.mjpeg
2. Audio -> service/camera/audio.aac

```
                  {
                    "name": "AirBeam Cam",
                    "model": "AirBeam on iPhone 4S / iOS 9.3",
                    "serialNumber": "0123456789",
                    "motion": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i http://IPADDRESS/service/camera/video.mjpeg -i http://IPADDRESS/service/camera/audio.aac",
                        "maxWidth": 1728,
                        "maxHeight": 972,
                        "maxFPS": 30,
                        "vcodec": "copy",
                        "packetSize": 752,
                        "mapvideo": "0:0",
                        "mapaudio": "1:0",
                        "audio": true,
                        "debug": true
                    }
```

Unfortunately Output is then quite slow and audio output is lagging behind.

Are there any hints how to deal with this situation?

Thanks,
Joachim

**Comment by lazymoose5** [comment]
Hi Joachim

I have not come across this delay. In my case the wifi link of my setup was slow and weak - the iPhone was away in my backyard. I had to set the refresh rate at 5 fps in the AirBeam settings to have a reliable video link. The audio was choppy but it was not important to me.

Matthieu

**Comment by jotzet79** [comment]
Hi @lazymoose5 / Matthieu, 
Thanks for the feedback - I think I got it finally working. Posting results to #1189.
BTW: Your hint regarding fps was also helpful, thx!
Regards, Joachim
