### ISSUE TITLE
Amcrest IP3M-943B Working with Motion and MotionDoorbell

### ISSUE THREAD

**Issue by magic7s** [Sunoo/homebridge-camera-ffmpeg#1183]
**Manufacturer/Model:**
Amcrest IP3M-943B

**Homebridge Config:**

```json
{
  "platforms": [
    {
            "name": "Front Door Camera",
            "manufacturer": "Amcrest",
            "model": "IP3M-943B",
            "motion": true,
            "doorbell": true,
            "motionTimeout": 0,
            "motionDoorbell": true,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp://admin:admin@192.168.128.123/cam/realmonitor?channel=1&subtype=0",
                "stillImageSource": "-i http://admin:admin@192.168.128.123/cgi-bin/snapshot.cgi?chan=1",
                "maxWidth": 0,
                "maxHeight": 0,
                "maxFPS": 0,
                "maxBitrate": 2048,
                "forceMax": true,
                "vcodec": "copy",
                "audio": false,
                "debug": false
            }
        }
      ],
      "platform": "Camera-ffmpeg"
    },
    {
      "homebridgeCameraFfmpegHttpPort": 8080,
      "useHttp": true,
      "cameras": [
        {
          "index": 0,
          "cameraName": "Front Door Camera",
          "cameraCredentials": {
            "host": "192.168.128.123",
            "user": "admin",
            "pass": "admin",
            "useHttp": true
          }
        }
      ],
      "platform": "dahua-alerts"
    }
  ]
}
```

**Additional Information:**

`dahua-alerts` reaches out to each camera at `/cgi-bin/eventManager.cgi?action=attach&codes=[VideoMotion]'` and the camera will send a notification when motion is detected. `dahua-alerts` will then send an http post to the http motion detection for `Camera-ffmpeg`

I'm even getting Doorbell alerts on my Apple TV. So Cool!!

FYI - there is a scrolling error in the logs that I have not figured out yet. `[dahua-alerts] Error Received (for more info enable debug logging)` Homebridge debug is not very helpful. 

edit: Updated the config to provide a speeder experience. Also the errors from the motion alerts are from a bug in the camera firmware that does not release the session properly.

**Comment by Sunoo** [comment]
You'll likely need to reach out to the developer for dahua-alerts to understand why that error is occurring. I'm not personally familiar with that plugin at all.

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Amcrest-IP3M-943B.html
