### ISSUE TITLE
Plugin Site Unavailable

### ISSUE THREAD

**Issue by cinaali** [Sunoo/homebridge-camera-ffmpeg#1188]
**Describe The Problem:**
"Plugin site unavailable" on attempt to install all plugins. New Hoobs box just received last week. Can't update node without error.

* **Node.js Version**: 14.17.5
* **NPM Version**: 
* **Homebridge Version**: 4.0.100

* **Operating System**: Mac Big Sur

**Comment by Sunoo** [comment]
You’ll need to reach out to HOOBS support for issues with their software: https://support.hoobs.org/

**Comment by cinaali** [comment]
Apologizes…I thought that where I was posting.  When I go to the Hoobs support website and clock Hoobs issues it takes me to this message board.
