### ISSUE TITLE
Setup plugins that worked for me

### ISSUE THREAD

**Issue by albilia** [Sunoo/homebridge-camera-ffmpeg#1190]
{
     "name": "Camera FFmpeg",
     "cameras": [
         {
             "name": "Hikvision",
             "model": "DS-2CD2542FWD-I",
             "serialNumber": "DS-2CD2542FWD-I20180319BBWRC10320726",
             "firmwareRevision": "V5.5.5 build 180111",
             "unbridge": false,
             "videoConfig": {
                 "source": "-i rtsp: // admin: hvi12345@192.168.1.188: 554"
             }
         }
     ],
     "platform": "Camera-ffmpeg"
}

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2542FWD-I.html
