### ISSUE TITLE
Option for transcoding from h.265 HEVC to H.264 ?

### ISSUE THREAD

**Issue by AssetBurned** [Sunoo/homebridge-camera-ffmpeg#1192]
Hi,

Looks like there are people out there who hit a wall when it comes to cameras with H.265 RTSP streams.

Looking at https://www.raspberrypi.org/forums/viewtopic.php?t=293536 ffmpeg is able to do the transcoding reasonable fast on an RP3, up to 25 fps in 1920x1080.

Another look at https://github.com/Supereg/secure-video-specification indicates an support for H.265 but that isn't the normal HomeKit part.

The question is if the homebridge plugin could be modified to deal with the transcoding?

CU AssetBurned ;-)

**Comment by Sunoo** [comment]
I'm not sure I understand what you're asking for.

This plugin's default behavior is to transcode to h264, though there it can be configured (by setting vcodec to copy) to pass the video through untouched, if your camera happens to spit out video in a format that HomeKit is happy with.

**Comment by AssetBurned** [comment]
Hmmm... *facepalm* Ok classical case of PEBKAC.

I was under the impression that getting the stream from h265 to h264 required some extra parameters that need to entered, and the main purpose was for rescaling/changing the frame rates things like that.
Should have tried the easy approach first and not following some online threads. :-/

Sorry for the ticket!

**Comment by Sunoo** [comment]
No worries!
