### ISSUE TITLE
Annke C800 and Apple TV

### ISSUE THREAD

**Issue by Vaifranz** [Sunoo/homebridge-camera-ffmpeg#1202]
Hello everyone, I have a question to submit to you, hardware premise: I installed the plugin and it works great, tested on eufy 2K (all OK) and on Annke C800 with Hikvision firmware, just because it solves some problems, plus the camera has only codecs H265 or H265 + (which I am using with Surveillance Station on Synology without problems), the question is this, in the homekit, the C800, I see it very well with iPhone XS Max and iPad Pro 11 (all with iOS 15), as well as with macOS , with Apple TV 4 (HD) with the latest release I see it for just over 10 seconds then the image freezes. I know pligin only works with H264 ... or at least I think ... In the settings the video codec is "libix264". I had the same problem with a Hikvision with H264 codec. Any idea!? Thanks.

**Comment by Sunoo** [comment]
Can you share your config and your log please?

**Comment by Vaifranz** [comment]
This is my config:

```
                    "name": "CAM 04",
                    "manufacturer": "Annke - Hikvision",
                    "model": "C800 - DS-2CD1383G0-IU",
                    "serialNumber": "I91BM",
                    "firmwareRevision": "V5.5.801 build 210727",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://xxx:xxx@xxx.xxx.xxx.xxx:554/Streaming/Channels/101",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 20,
                        "maxBitrate": 1024,
                        "forceMax": true,
                        "audio": true`
```

This is the log on Homebridge, I'm using Synology

```
[9/27/2021, 6:32:03 PM] [Camera FFmpeg] [CAM 04] Starting video stream: 1920 x 1080, 20 fps, 1024 kbps (AAC-eld)
[9/27/2021, 6:32:29 PM] [Camera FFmpeg] [CAM 04] Stopped video stream.
```

The problem It's only Apple TV, maybe for H265...

**Comment by Sunoo** [comment]
Giving Apple TV anything other than what it explicitly asks for tends to cause problems. I’m guessing if you remove forceMax it’ll work.

**Comment by Vaifranz** [comment]
Hi, thanks for the advice, but nothing has changed, I have this warning in the log:

```
[CAM 04] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[9/27/2021, 7:21:21 PM] [Camera FFmpeg] [CAM 04] Fetching snapshot took 5.311 seconds.
```

**Comment by sebastiaan88** [comment]
Hi, first it’s better to enable substream in the hikvision and use that with less resolution and fps, i myself use 512kbs 640x360 10fps and same settings when adding the cam! Then change the url after channel/ 101 in 102 in the url for substream (101 is main 102 is sub)
