### ISSUE TITLE
Wyze Cam v2/v3/pan/doorbell/outdoor on docker-wyze-bridge

### ISSUE THREAD

**Issue by mrlt8** [Sunoo/homebridge-camera-ffmpeg#1206]
**Manufacturer/Model:**

- Wyzecam V2 (WYZEC1-JZ)
- Wyzecam V3 (WYZE_CAKP2JFUS)
- Wyzecam Pan (WYZECP1_JEF)
- Wyzecam Doorbell (WYZEDB3)
- Wyzecam Outdoor (WVOD1)

**Homebridge Config:**

```json
{
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "CAM_NAME",
            "manufacturer": "WyzeCam",
            "model": "WYZE_CAKP2JFUS",
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp://<docker-wyze-bridge-ip>:8554/cam-name",
                "vcodec": "copy"
            }
        }
    ],
    "platform": "Camera-ffmpeg"
}
```

**Additional Information:**
docker-wyze-bridge does not support audio at this time.

**Doorbell rotation in homebridge:**
Depending on your config, you may want to rotate the doorbell cam in homebridge with hardware acceleration, which can be done by specifying your `vcodec` of choice and setting `videoFilter` to `transpose=1`:
```json
"videoConfig": {
    "source": "-i rtsp://10.0.0.10:8554/front",
    "vcodec": "libx264",
    "videoFilter": "transpose=1"
}
```

**Comment by holocronology** [comment]
What does the `"vcodec": "copy"` do in this?

**Comment by Sunoo** [comment]
The copy vcodec setting prevents transcoding of the video and just copies it to HomeKit. This improves video quality and lowers CPU load, but can cause compatibility issues.

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/WyzeCam.html
