### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by Stetocasa** [Sunoo/homebridge-camera-ffmpeg#1212]
Hello, I bougth a video doorbell wifi that works in Smart Life app

Camera FFMPEG plugin just works with RTSP?

**Comment by Sunoo** [comment]
And HTTP, HLS, etc. If your camera supports anything other than just the native app, it most likely will work with this.

**Comment by Stetocasa** [comment]
Inside Smart Life I just can see the IP address

This is the camera
https://www.amazon.it/gp/product/B08W56WMWR/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
