### ISSUE TITLE
TP Link Tapo C200 with motion detection

### ISSUE THREAD

**Issue by mihailescu2m** [Sunoo/homebridge-camera-ffmpeg#1213]
**Manufacturer/Model:**
TP Link Tapo C200

**Homebridge Config:**

```json
{
            "name": "Camera FFmpeg",
            "mqtt": "[MQQT.IP]",
            "cameras": [
                {
                    "name": "Tapo-1",
                    "manufacturer": "Tp-Link",
                    "model": "C200",
                    "serialNumber": "2001",
                    "unbridge": true,
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://[USER]:[PASS]@[CAM.IP]:554/stream2",
                        "stillImageSource": "-i rtsp://[USER]:[PASS]@[CAM.IP]:554/stream2",
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 15,
                        "maxBitrate": 384,
                        "forceMax": true,
                        "vcodec": "copy",
                        "audio": true
                    },
                    "mqtt": {
                        "motionTopic": "onvif2mqtt/Tapo-1/motion",
                        "motionMessage": "ON",
                        "motionResetTopic": "onvif2mqtt/Tapo-1/motion",
                        "motionResetMessage": "OFF"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Additional Information:**
Motion detection set up using onvif2mqtt.
~3s delay for the 640x480 stream (stream2).
In the debug info, `Getting the first frames took` usually shows ~3s.

**Comment by ricbacca** [comment]
Can you please explain how to enable this possibility ?
After installing Onvif2mqtt on a docker and enabling mqtt and motion sensor on Homebridge camera FFMPEG.
Thanks

**Comment by ricbacca** [comment]
Could you maybe share the onvif2mqtt config and mqtt config for the camera? I am really interested in this but I cannot seem to find how to set up these new plugins I only have the ffmpeg plugin running. Thanks

**Comment by ricbacca** [comment]
Also, have you installed specific mqtt plugin inside homebridge ?
Or you use mqtt functionalities inside Homebridge camera FFMPEG plugin ?

**Comment by fate8383** [comment]
There are no plugins you will install to homebridge other than this one, but make sure you installed mosquito (MQTT) broker to your server where homebridge is running, assuming you already installed onvif2mqtt node, then use the onvif2mqtt conf file to set up your camera, tp link is using port 2020 so adjust your onvif conf file. Add config to ffmpeg plugin motion settings. Run the Onvif node that's all. Make sure you turn on notification on in HomeKit for the camera. And on the camera tp link app make sure you turn on motion detection high/medium whatever you want. Share the config so I can help further if you get stuck somewhere.

**Comment by kopiro** [comment]
I'm testing a new ONVIF implementation right now: https://github.com/kopiro/homebridge-tapo-camera/pull/12; if everything's ok I'm gonna release it soon :)

**Comment by fate8383** [comment]
> I'm testing a new ONVIF implementation right now: https://github.com/kopiro/homebridge-tapo-camera/pull/12; if everything's ok I'm gonna release it soon :)

This is very nice, do we still need ffmpeg plugin? I have configured all with onvif2mqtt by making system service on rpi, logrotate and all, as it creates 40mb of logs a day. I would not mind trying something simpler. If you can add also HKSV then you will be golden :)

**Comment by kopiro** [comment]
No, this plugin integrates everything; you don't need the `homebridge-ffmpeg-plugin` or `onvit2mqtt`

**Comment by ricbacca** [comment]
> I'm testing a new ONVIF implementation right now: [kopiro/homebridge-tapo-camera#12](https://github.com/kopiro/homebridge-tapo-camera/pull/12); if everything's ok I'm gonna release it soon :)

Very nice, thanks for the info !

**Comment by kopiro** [comment]
The testing is done and implementation is correct! Give it a try :)

**Comment by cicciovo** [comment]
@fate8383 can you help me? 😅 can you give me the config.yml file and the script for run it? I use the tapo camera c200 ad you. Because the plugin of kopiro doesn’t work in remote..

**Comment by kopiro** [comment]
@cicciovo if you have an HomePod or an iPad configured as bridge you are able to see the stream remotely, otherwise it's not possible to do it afaik with any plugin

**Comment by fate8383** [comment]
> @fate8383 can you help me? 😅 can you give me the config.yml file and the script for run it? I use the tapo camera c200 ad you. Because the plugin of kopiro doesn’t work in remote..

I cannot give you my config file :) but I can help you with yours. Also I can help you to create your own script to run it as a service. But without home hub, HomePod, Apple TV or iPad it will never work from remote.

**Comment by cicciovo** [comment]
Sure! Of curse! I’ve an Appletv 4 gen. Unfortunately I haven’t so much time to study. With my little son and the work i can not dedicate time for it! Ihad write some plugin for me a lot time ago. But now it’s impossible. Now: for the scrit isn’t a problem. For the yml configuration file yes. I have installed mosquitto as a server. My tapo camera must be comunicate with the broker (onvif2mqtt) it’s ok? If i run onvif the error is this: home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:79:15)","type":"Error","v":1}

**Comment by cicciovo** [comment]
> @cicciovo if you have an HomePod or an iPad configured as bridge you are able to see the stream remotely, otherwise it's not possible to do it afaik with any plugin

With homebridge-ffmpeg-camera i’m able To see streaming video in remote. With your no. Maybe because i cannot choose packet size and other configuration..

**Comment by fate8383** [comment]
> Sure! Of curse! I’ve an Appletv 4 gen. Unfortunately I haven’t so much time to study. With my little son and the work i can not dedicate time for it! Ihad write some plugin for me a lot time ago. But now it’s impossible. Now: for the scrit isn’t a problem. For the yml configuration file yes. I have installed mosquitto as a server. My tapo camera must be comunicate with the broker (onvif2mqtt) it’s ok? If i run onvif the error is this: home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:79:15)","type":"Error","v":1}

Ok create a script to run this thing, as it creates crazy amount of log, it is best to run it on background. I created a service, enabled for systemctl and logging with pod rotate...this is all up to you

Keep all the files where you cloned onvif2mqtt together. My simple script is this

#!/bin/bash
cd /home/pi/onvif2mqtt/
CONFIG_PATH=/home/pi/onvif2mqtt/config.dev.yml
npm run start

I use the dev.yml adjust the path and names according to your files.

Yml file is this, please adjust according to your set up

mqtt:
  host: 127.0.0.1
  port: 1883
onvif:
  - name: given name, will be used in ffmpeg 
    hostname: IP
    port: 2020
    username: xxxx (created in Tapo app)
    password: xxxx (created in Tapo app)

Let me know if you get error again

**Comment by cicciovo** [comment]
My config file was/is as you write up! I rename the file in .bak but the error is the same. Tomorrow i try with the script maybe change sometinks..

**Comment by fate8383** [comment]
> My config file was/is as you write up! I rename the file in .bak but the error is the same. Tomorrow i will try with the script maybe change sometinks..

Not sure the script will change this error, check with mqtt conf or file permissions. check mqtt if you allowed any connection or use your username and password, also check onvif2mqtt file permissions.

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/TP-Link-Tapo-C200.html
