### ISSUE TITLE
Toadi Automatic Mower

### ISSUE THREAD

**Issue by GusMuche** [Sunoo/homebridge-camera-ffmpeg#1216]
**Manufacturer/Model:**
Toadi Mower

**Homebridge Config:**

```json
"name": "Toadi2",
"motion": false,
"switches": false,
"unbridge": true,
"videoConfig": {
    "source": "-re -loop 1 -i http://IPfromControlPanel:8080/image/front/img.jpg?timestamp=21439115",
    "stillImageSource": "-i http://IPfromControlPanel::8080/image/front/img.jpg?timestamp=21439115",
    "maxStreams": 1,
    "maxWidth": 640,
    "maxHeight": 480,
    "maxFPS": 1,
    "debug": false
}
```

**Additional Information:**
Maybe the frame rate can be shorter. Just play with the parameters.

The link to the image can be found with a right click on the image stream from the control panel and paste in the navigation bar.

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Toadi-Automatic-Mower.html
