### ISSUE TITLE
ThomView DSC-725S

### ISSUE THREAD

**Issue by SebastienMrc** [Sunoo/homebridge-camera-ffmpeg#1217]
**Manufacturer/Model:**
ThomView DSC-725S

**Homebridge Config:**
 "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera",
                    "manufacturer": "ThomView",
                    "model": "DSC-725S",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-i rtsp://username:password@XX.XXX.XXX.XXX:port/videoMain",
                        "vcodec": "copy",
                        "packetSize": 188,
                        "audio": false

**Additional Information:**
"vcodec": "libx264" -> OK
"packetSize": 1316 -> OK

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/ThomView-DSC-725S.html
