### ISSUE TITLE
Dahua imou camera problem

### ISSUE THREAD

**Issue by SzilagyiR** [Sunoo/homebridge-camera-ffmpeg#1221]
Hi!

I have two Dahua imou Bullet 2 cameras. I tried many settings but still have a problem.
May cameras have two RTSP stream:
1. 2560x1440 25fps H265
2. 640x480 15 fps H264

If I implement the first stream to my homebrige with "vcodec": "copy" but, noting show in the Home app, because the 2k resolution, I think. The second stream works fine, but 640x480 is very very low quality.

If I use "vcodec": "libx264 -preset ultrafast" or "h264_omx" works, but picture quality is low because my Pi 3 reencoding the stream, witch is cause high CPU usage. If I show two streams the Pi 3 is rebooting because the overload.

Can someone suggest a vcodec option, or any other solution to show first strem in Home app with quality picture?

Thanks!

**Comment by brancooo1** [comment]
I’ve found [this list of URLs](https://www.ispyconnect.com/camera/imou) , if someone tries to use Imou cameras with ffmpeg
