### ISSUE TITLE
Child bridge vs unbridged

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Sunoo/homebridge-camera-ffmpeg#1228]
Does using both child bridge & unbridged help?
Where are the unbridged instructions? I eventually located the thread and resultant pull request but can’t locate the instructions. 

**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
I don’t understand your question.

**Comment by TeslaOwnerTips** [comment]
Usually creating a child bridge speeds up homebridge or put another way a plugin placed in a child bridge prevents it from blocking other plugins. 

So is placing the plugin in a child bridge AND using the unbridged option when adding cameras helpful? Is it sufficient to just use a child bridge?

**Comment by Sunoo** [comment]
The recommended use of this plugin would be to run in on your main bridge with the cameras in unbridge mode. I would expect you to see no benefit from also running this in a child bridge.
