### ISSUE TITLE
Aspect ratio 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Sunoo/homebridge-camera-ffmpeg#1229]
**Describe The Problem:**

The video aspect ratio is 16:9 but displays 4:3 in the home app. 
How do I fix it?

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

   {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Intersection ",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://x:c@1.1.1.1:554/cam/realmonitor?channel=1&subtype=1",
                        "stillImageSource": "-i http://x:x@1.1.1.1/cgi-bin/snapshot.cgi?channel=1",
                        "encoderOptions": "-aspect 16/9"
                    }
                }
            ],
            "_bridge": {
                "username": "0E:71:5A:F0:A0:67",
                "port": 33820
            },
            "platform": "Camera-ffmpeg"
        }

**Screenshots:**

![ED4F0529-0D8C-4D03-9569-4CDD53A1497D](https://user-images.githubusercontent.com/78335749/144353293-c6ff12fc-ec72-400a-b1d7-16217bdb8db0.jpeg)
![8F3FDC55-72DC-4ED5-AB63-B2B26CC582EF](https://user-images.githubusercontent.com/78335749/144353295-6e0fa9a9-4dc2-4dbf-82c4-029a91110d7a.jpeg)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
The only option I can think of is to use videoFilter to rescale the video to the correct aspect ratio.
