### ISSUE TITLE
Reolink 4k Direct Streaming

### ISSUE THREAD

**Issue by bobat-h** [Sunoo/homebridge-camera-ffmpeg#1232]
**Manufacturer/Model:**
Reolink

**Homebridge Config:**

```-rtsp_transport tcp -i rtsp://user:password@192.168.X.X:554//h265Preview_01_main```

**Additional Information:**
This config will enable 4k direct streaming preventing local encoding. You will need to set maximum values on the video output setting page, from the settings on your camera. This can be found in the Reolink app in the quality setting page. The setting I use are Maximum Width:3840, Maximum Hight: 2160, Maximum Frame Rate: 25, Maximum Bitrate: 8192. Also ensure the Force  Maximums box is ticked.

**Comment by bert-willekens** [comment]
This still gives me ~ 30 % CPU usage. I see no change over excluding -rtsp_transport tcp.

```
                {
                    "name": "Cam",
                    "manufacturer": "Reolink",
                    "model": "RLC-511",
                    "serialNumber": "952700027RLUI72O",
                    "firmwareRevision": "v3.0.0.142_20121803",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://homebridge:homebrdige@192.168.2.5:554/h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.2.5/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=homebridge&password=homebridge",
                        "maxWidth": 2560,
                        "maxHeight": 1920,
                        "maxFPS": 30,
                        "maxBitrate": 6144,
                        "audio": true,
                        "forceMax": true
                    }
```
