### ISSUE TITLE
H.View HV-E800A

### ISSUE THREAD

**Issue by MA72E** [Sunoo/homebridge-camera-ffmpeg#1234]
**Manufacturer/Model:**
H.View HV-E800A

**Homebridge Config:**

"name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "name",
                    "serialNumber": "original serialNumber",
                    "firmwareRevision": "IPCAM_V4.04.40.210303",
                    "motion": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://user:password@ipadress:554/live/main",
                        "maxWidth": 800,
                        "maxHeight": 600,
                        "maxFPS": 25
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Additional Information:**

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/H.View-HV-E800A.html
