### ISSUE TITLE
Very Slow Performance RPi 3b using Buster

### ISSUE THREAD

**Issue by madmacks59** [Sunoo/homebridge-camera-ffmpeg#1251]
**Describe The Problem:**

Just installed HomeBridge on a RPi 3b+ running Buster and am getting very slow performance using ffmpeg to connect with my Amcrest cameras.

I'm wondering if I need to update FFMPEG to a newer version (currently using the built in Buster version), or would buying a RPi 4B with more memory be a better idea. Or, is there some plugin config change be made?

**Config**

I've done a simple configuration as follows:

                {
                    "name": "Cabin-South",
                    "manufacturer": "Amcrest",
                    "model": "IP8M_T2599EW",
                    "serialNumber": "D96539",
                    "firmwareRevision": "1.0",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://XXXX:XXXXX@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0",
                        "maxWidth": 3840,
                        "maxHeight": 2160,
                        "maxFPS": 15,
                        "maxBitrate": 8192,
                        "forceMax": true
                    }
                },
                {
                    "name": "Cabin-PTZ",
                    "manufacturer": "Amcrest",
                    "model": "PTZ",
                    "serialNumber": "132AC9",
                    "firmwareRevision": "1.0",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://XXXX:XXXX@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0",
                        "maxWidth": 2304,
                        "maxHeight": 1296,
                        "maxFPS": 20,
                        "maxBitrate": 4096,
                        "forceMax": true
                    }
                }
            ],

**Logs:**

[1/10/2022, 11:13:58 AM] [Camera FFmpeg] [Cabin-PTZ] Fetching snapshot took 18.463 seconds.
[Cabin-South EF42] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[1/10/2022, 11:14:06 AM] [Camera FFmpeg] [Cabin-PTZ] Starting video stream: 2304 x 1296, 20 fps, 4096 kbps
[1/10/2022, 11:14:12 AM] [Camera FFmpeg] [Cabin-PTZ] Getting the first frames took 6.569 seconds.
[Cabin-South EF42] The image snapshot handler for the given accessory didn't respond at all! See https://git.io/JtMGR for more info.
[1/10/2022, 11:14:22 AM] [Camera FFmpeg] [Cabin-South] Fetching snapshot took 23.131 seconds. The request has timed out and the snapshot has not been refreshed in HomeKit.
[1/10/2022, 11:14:35 AM] [Camera FFmpeg] [Cabin-PTZ] Stopped video stream.

**Environment:**

homebridge-config-ui-x v4.41.5
NPM 8.3.0
Node v16.13.1
homebridge-camera-ffmpeg v3.1.4
ffmpeg version 4.1.8-0+deb10u1+rpt1

**Comment by riiveraluis** [comment]
https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1257#issue-1117567700
