### ISSUE TITLE
Additional parameters to improve the start of the video

### ISSUE THREAD

**Issue by riiveraluis** [Sunoo/homebridge-camera-ffmpeg#1257]
**Manufacturer/Model:**

Lorex D871A8

**Additional Information:**

In the discord forum about the plugin, several parameters in the video source address came up that can be used to reduce the waiting time when starting a video. The arguments were taken from the link https://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg

The format would be as follows:

-probesize 32 -analyzeduration 0 -i rtsp://(Your camera RTSP LINK)

Where:

-probesize 32 sets the probing size in bytes (i.e. the size of the data to analyze to get stream information). A higher value will enable detecting more information in case it is dispersed into the stream, but will increase latency. Must be an integer not less than 32. It is 5000000 by default.

analyzeduration 0 specifies how many microseconds are analyzed to probe the input. A higher value will enable detecting more accurate information, but will increase latency. It defaults to 5000000 microseconds (5 seconds).

I think it should be useful to include them in the plugin guidelines as in my case it helped to lower the start time of the streaming to two seconds.

**Comment by riiveraluis** [comment]
Also recommended by you some time ago, but no -re I wonder why. 
https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1156#issuecomment-915695719

**Comment by Sunoo** [comment]
@riiveraluis I have been advising people not the `-re` option for ages, because the FFmpeg documentation explicitly says not to use it for this use case:

> Read input at the native frame rate. Mainly used to simulate a grab device, or live input stream (e.g. when reading from a file). Should not be used with actual grab devices or live input streams (where it can cause packet loss). By default ffmpeg attempts to read the input(s) as fast as possible.

An IP camera would absolutely count as a live input stream.

**Comment by riiveraluis** [comment]
To fix my mistake, I will edit my original comment to remove references of -re. The other parameters I think will benefit some cases, as low values of probesize and analyzeduration might not work for all configurations. Thanks!

**Comment by california444** [comment]
@riiveraluis 
Your discussion motivated me to play again with my own camera settings...
Setting probesize to 32 does not work for my Foscam cameras, but by increasing it just a bit, the camera stream started working again. With 1000 I got a stream sometimes, with 2000 always.
I finally changed my parameters to the following and with that the stream now starts nearly immediately, max. 1s to wait.
Maybe other users find this helpful...

-fflags nobuffer -flags low_delay -fflags discardcorrupt -analyzeduration 0 -probesize 2000 -rtsp_transport tcp -i rtsp://

**Comment by riiveraluis** [comment]
@california444 

Do you want to add on the different parameters you have there before rtsp url? 

Will definitely look into your flags and transport settings since I don’t have those. If you have a resource or knowledge please share so I can add more to my original post. 

I want the read me of this plugin gets the most accurate and useful information to speed up streaming.

**Comment by california444** [comment]
I followed your linke above: https://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg. I added them before the rtsp input url...


**-fflags nobuffer** 
This format flag reduces the latency introduced by buffering during initial input streams analysis. This command will reduce noticeable the delay and will not introduce audio glitches.

**-flags low_delay**
this codec generic flag will force low delay.

**-fflags discardcorrupt**
 to discard corrupted packets

**-rtsp_transport tcp**
force using tcp instead of udp

**Comment by Tesla-P100FX** [comment]
> -fflags nobuffer -flags low_delay -fflags discardcorrupt -analyzeduration 0 -probesize 2000 

I was so hopeful after reading your post that this would work for me. I have Lorax cameras and they take between 30 to 45 seconds to load. I used the above and messed with the probesize but could not get it to make a difference

**Comment by riiveraluis** [comment]
> > -fflags nobuffer -flags low_delay -fflags discardcorrupt -analyzeduration 0 -probesize 2000
> 
> I was so hopeful after reading your post that this would work for me. I have Lorax cameras and they take between 30 to 45 seconds to load. I used the above and messed with the probesize but could not get it to make a difference

Please post your setup. Where are you running the plugin and is wired or wireless. Same questions for the camera.

**Comment by Tesla-P100FX** [comment]
> > > -fflags nobuffer -flags low_delay -fflags discardcorrupt -analyzeduration 0 -probesize 2000
> 
> > 
> 
> > I was so hopeful after reading your post that this would work for me. I have Lorax cameras and they take between 30 to 45 seconds to load. I used the above and messed with the probesize but could not get it to make a difference
> 
> 
> 
> Please post your setup. Where are you running the plugin and is wired or wireless. Same questions for the camera. 

This is a Lorex 8 channel Hardwired DVR with 4K cameras
 
 
{
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Driveway",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxxx@10.0.0.155:554/cam/realmonitor?channel=1&subtype=1"
                    },
                    "doorbell": false,
                    "motionDoorbell": false
                }
Hoobs on RasberryPi 4.0.104
Node 16.13.2
Homebridge 1.3.4
FFMPEG Bridge 3.1.4
