### ISSUE TITLE
Light sensor 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Sunoo/homebridge-camera-ffmpeg#1261]
**Is your feature request related to a problem? Please describe:**

Lights on during the day when not needed but needed when it is cloudy
**Describe the solution you'd like:**

A Lights sensor  that could be configured as a switch. It doesn’t have to be accurate we just play with some numbers say from 0 to 100% decide when it goes on and off. It could just be a simple adding up of all the pixels to get a brightness value.
**Describe alternatives you've considered:**

**Additional context:**

**Comment by TeslaOwnerTips** [comment]
In the winter some days are brighter with no clouds and snow on the ground reflecting light. Other days it is cloudy and gloomy. Or both in the same day.

**Comment by TeslaOwnerTips** [comment]
I tried the lux sensor that comes with the circle camera but I could never get it to work to trigger anything. Having a simple switch I think would be more reliable. We could either set a percentage in the config file or may be a light switch with a percentage of slider.

**Comment by Sunoo** [comment]
I really don’t think that’s a good fit for this plug-in at this time. The biggest issue is that my code never directly even sees the stream flowing through it currently (that is all handled by ffmpeg), so I have no real opportunity to examine the pixels. However, even if I had that ability, I expect you’d find the results fairly useless, as most cameras have some amount of auto exposure control that would constantly skew the output.
