### ISSUE TITLE
Live view very slow

### ISSUE THREAD

**Issue by Kydix** [Sunoo/homebridge-camera-ffmpeg#1262]
Hi, 

I currently test an old Sony SNC-XM632. 

Everything work fine except one thing. When I open the live in Homekit, the video is very very lagy and pixelised.

When I open the RTPS link in VLC, I have no problem. 

I'm running the last version of Homebridge on a raspberry pi 3 with buster. 

Last version of the FFmpeg plugin,

Any help ?

**Comment by Sunoo** [comment]
Please share your config.

**Comment by Kydix** [comment]
"name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Sony IP CAM",
                    "manufacturer": "Sony",
                    "model": "SNC-XM632",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://IPADRESS/media/video1",
                        "maxStreams": 1,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "maxBitrate": 124000,
                        "forceMax": false,
                        "vcodec": "libx264"

**Comment by Kydix** [comment]
I notice that the live stream start every time with the bitrate @ 299kbps no matter the value I put in "max bitrate"

**Comment by Sunoo** [comment]
Yes, the way this works is that maxBitrate sets the maximum bitrate, so it sets the highest value that it will allow HomeKit to ask for. If you want to ignore HomeKit’s requests and go above that, you need to set forceMax.

Another option, depending on your camera, would be to try the copy vcodec setting, which will just ignore all those other options and send exactly the video feed that comes from your camera. This may cause issues or potentially not work at all though.
