### ISSUE TITLE
No ffmpeg signal

### ISSUE THREAD

**Issue by lucamancusodev** [Sunoo/homebridge-camera-ffmpeg#1265]
**Manufacturer/Model:**
Weewooday/IR-Cut Webcam

**Homebridge Config:**

```json
{
            "platform": "Camera-ffmpeg",
       
            "cameras": [
                {
                    "name": "Telecamera Sala",
                    "uploader": false,
                    "videoConfig": {
                        "source": "-re -f video4linux2 -i /dev/video0",
                        "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "vcodec": "h264",
                        "audio": false,
                        "debug": false
                    }
                }
            ]
        }
```

This is the log errors when I try to open live stream, however if i do `ffmepg -re -f video4linux2 -i /dev/video0 test.mp4` I can see video.

![image](https://user-images.githubusercontent.com/41821623/153954027-1b863929-e628-4aba-8157-24562cfff424.jpeg)

**Comment by Sunoo** [comment]
Please set debug to true and try again. I’m guessing you’re probably hitting a permissions issue.

**Comment by lucamancusodev** [comment]
You right!
Now I got `(video4linux2, v412 @ 0x55a
f29cda0] [error] Cannot open video device
/dev/video0: Permission denied`

What can I do, I've already added my user to video group.

**Comment by Sunoo** [comment]
I’m not sure how you’ve set Homebridge up, but it’s usually running under the `homebridge` user, not the account you log in as. Make sure that’s in the video group.

**Comment by lucamancusodev** [comment]
Never mind!

Thank you.
