### ISSUE TITLE
Camera FFmpeg process creation failed: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by superhardi** [Sunoo/homebridge-camera-ffmpeg#1271]
Current Situation
I install plugins TAPO camera^ but see this error in logs FFmpeg process creation failed: spawn ffmpeg ENOENT
What me need doing, for resolve this situation?

Logs
FFmpeg process creation failed: spawn ffmpeg ENOENT
Configuration
Mac Mini M1
Environment
Last MACos and last homebridge

**Comment by Sunoo** [comment]
FFmpeg is not on your system. Looks like the precompiled version I use isn’t available for M1 yet: https://github.com/homebridge/ffmpeg-for-homebridge

You could install it yourself, I believe Homebrew is the way some people have used, but I have no experience with it myself.

**Comment by superhardi** [comment]
thanks for help

**Comment by jandreaucodes** [comment]
I am running into the same issue.

I have ffmpeg installed via homebrew, but it's installed in a different location on M1 chips: /opt/homebrew/bin/ffmpeg

Is it possible to edit the plugin to use ffmpeg from that location and not the standard on non-M1 chips?
