### ISSUE TITLE
Still Image Only Option

### ISSUE THREAD

**Issue by holocronology** [Sunoo/homebridge-camera-ffmpeg#1276]
I have several cameras that are in a poor wifi zone, so it is difficult to pull live RTSP video off them. However I am able to pull still images without issue.

The plug-in is currently configured to REQUIRE the RSTP feed video source URL.

Could you add an option to not require this and only use the StillImage source?

For example, I am using the docker-wyze-bridge to generate the RTSP feeds to select Wyze Cams. I'm also having docker-wyze-bridge generate an updated still image on my NAS every 30 seconds. For the poor WiFi cams, I'd like to only use the auto-updating still image as the "feed."

I realize there is at least one plugin that claims to do an image-to-camera, but it just doesn't seem to work and I'd rather have fewer plugins to deal with. Since the functionality is here already but just needs to be tweaked.

**Comment by Sunoo** [comment]
I suppose I could automatically support that without much effort, so I may consider adding it. It’s definitely a weird edge case though.

I’m not entirely sure what your expectation is for behavior when you try to load the video feed though. It seems that this does provide a live feed, so why not use it? The stillImageSource would still be used for the snapshots.

Im guessing you may want to have the video feed just show a still image though? In that case, try copying your stillImageSource to source and adding `-loop 1` in front of it. You can probably set maxFPS down to 1 as well.

**Comment by Sunoo** [comment]
Actually, now that I think about it, that may try to pull new stills every time. You may want to use `-stream_loop -1` instead if you actually want the video to not update while playing.

**Comment by holocronology** [comment]
> I’m not entirely sure what your expectation is for behavior when you try to load the video feed though. It seems that this does provide a live feed, so why not use it? The stillImageSource would still be used for the snapshots.

My thinking/expectation would be that if the "live feed" failed--for whatever reason--it would revert to the still image and reload the still image on a repeating cycle. In this case, it would be a failover in the live view.  Alternatively, it would be a optional "live view" in that it would completely replace it, but basically have a frame rate of 30 seconds or something like that.

Follow up Q: Is the still image the image that's displayed on the view on Favorites, for example, before you click on the camera to go to a "live" view?

> Im guessing you may want to have the video feed just show a still image though? In that case, try copying your stillImageSource to source and adding -loop 1 in front of it. You can probably set maxFPS down to 1 as well.
Actually, now that I think about it, that may try to pull new stills every time. You may want to use -stream_loop -1 instead if you actually want the video to not update while playing.

For the above, I'm assuming that gets put in the RTSP feed field?

**Comment by Sunoo** [comment]
At the time the live feed fails, it’s most likely too late for me to start sending something else to HomeKit, and I’m not sure that makes sense to do anyways? I would imagine for most situations and most users, if the video won’t load, the stills won’t either.

And correct, it would go where the video feed would be expected to be if you wanted to use that.

**Comment by Sunoo** [comment]
Question though, is there a reason you aren’t using Wyze’s RTSP firmware?

**Comment by holocronology** [comment]
> Actually, now that I think about it, that may try to pull new stills every time. You may want to use -stream_loop -1 instead if you actually want the video to not update while playing.

Just so I'm not being stupid, so would this be some thing like` -i Http://STILLIMAGEURL -stream-loop -1`?

> Question though, is there a reason you aren’t using Wyze’s RTSP firmware?

Good question...The docker-wyze-bridge doesn't require changing/updating the firmware on the cameras. A couple of these cameras are in difficult to reach locations, so I don't want to have to update the firmware to their not-really-supported RTSP firmware. Also, the docker-wyze-bridge grabs the stills, even for the cams with poor WiFi and which even the Wyze RTSP firmware would be not ideal. I've tested this still image view in a Hubitat dashbaord, which allows me to make a tile that links to a an image. Bascially, I'm trying to do that in HomeKit, which I prefer to use as my central home automation location.

**Comment by Sunoo** [comment]
`-stream_loop -1 -i Http://STILLIMAGEURL`

And that’s fair. I use a combination of Dafang Hacks and Wyze RTSP on my Wyze cameras (depending on support), but it’s definitely got downsides. I have not played with docker-wyze-bridge, but I should at some point, if I find some free time ever.

**Comment by holocronology** [comment]
It was relatively painless to set up. Threw of docker-compose into a Portainer Stack and away you go...
https://github.com/mrlt8/docker-wyze-bridge
