### ISSUE TITLE
Support of "Motion activity zone"

### ISSUE THREAD

**Issue by sy6sy2** [Sunoo/homebridge-camera-ffmpeg#1279]
**Is your feature request related to a problem? Please describe:**
Just discover that official HomeKit camera can use a motion detection based on activity zone (see picture above).
I understand that this plugin can trigger a notification on motion detection thanks to https://sunoo.github.io/homebridge-camera-ffmpeg/automation/motion.html but I am unable to find here if the plugin allow to have this activity zone feature, can someone tell me if it's possible?

Thank you!

![image](https://user-images.githubusercontent.com/11562279/161596417-035d0053-6ed9-4526-86f4-9e8d3fb2ff75.png)

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Sunoo** [comment]
You should be able to do anything you’d typically do in Motion. I haven’t used it myself, another user wrote up that guide.

**Comment by sy6sy2** [comment]
Thank you for your answer.
I just investigated about this feature and I found that it's related to HomeKit Secure Video.
And if I understand correctly you are still on the road (https://github.com/Sunoo/homebridge-camera-ffmpeg/pull/1200) 😉
