### ISSUE TITLE
Motion detection not being realized in HomeKit

### ISSUE THREAD

**Issue by fratinize** [Sunoo/homebridge-camera-ffmpeg#1281]
**Describe The Problem:**
 I checked the box to use the motion of my Wyze v2 cam. HomeKit never shows motion is detected 

**To Reproduce:**
 cause motion by camera Wyze app detects and send me the video, but home kit had no clue anything happened.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.

[05/04/2022, 16:09:48] [Camera ffmpeg] [Equipment Cam] Sending snapshot: 640 x 360
[05/04/2022, 16:09:48] [Camera ffmpeg] [Equipment Cam] Resize command: /usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease -f image2 -


[05/04/2022, 16:09:48] [Camera ffmpeg] [Equipment Cam] Fetching snapshot took 2.32 seconds.
[05/04/2022, 16:09:48] [Camera ffmpeg] [Equipment Cam] Sending snapshot: 640 x 360
[05/04/2022, 16:09:48] [Camera ffmpeg] [Equipment Cam] Resize command: /usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease -f image2 -


**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.

name": "Equipment Cam",
                    "manufacturer": "Wyze",
                    "model": "V2",
                    "serialNumber": "06769885",
                    "firmwareRevision": "4.28.4.41",
                    "motion": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://username:password@192.168.1.121/live",
                        "stillImageSource": "-i rtsp://username:password@192.168.1.121/live",
                        "audio": true,
                        "debug": true
                    }
                },

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: <!-- node -v -->16.14.2
* **NPM Version**: <!-- npm -v -->8.5.0
* **Homebridge Version**: <!-- homebridge -V -->1.4.0
* **Homebridge Camera FFmpeg Version**: 3.1.4
* **Homebridge Config UI X Plugin Version**:4.42.0
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker -->raspbian homebridge image in a pi4



<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by fratinize** [comment]
Btw hope you have recovered from your recent challenge

**Comment by Sunoo** [comment]
What method are you using to pass motion through to the plugin, I don’t see it in your logs or config?

And thanks, rebuild finally starts Thursday, which will probably result in even more distraction from hobby work.

**Comment by fratinize** [comment]
Not sure I can answer that.
In the ui I check the box under automation that says detect motion. 
In my config I do have motion : true
But I also do not see any logs that say it’s being captured.

**Comment by fratinize** [comment]
So I Looked at the mqtt and Add that to my Config, and All it seemed to do was to add a Motion Trigger Switch to hk. I still get no notification that my Camera detected any motion. Not Sure What I am Missing. Thanx when ever u get some time.

**Comment by Sunoo** [comment]
My plugin doesn't include anything in itself to detect motion, it needs to either be connected up with the camera's motion sensor, or you can use the Motion software to do the detection yourself. There is information on the various ways of doing that at: https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

**Comment by fratinize** [comment]
Thanx for the direction. I think I am a Little more confused now. So the camera (I am Using a Wyze v2 RTSP), it detects motion, will send alerts from App. This Camera Plugin gives me the option to Show the Motion Detector, but I need to do something else for it to actually Tell HomeKit it detected motion?

**Comment by fratinize** [comment]
So The Cameras Motion Sensor Does Not publish mqtt topics? I can get it to React if I manually Publish the Topic, but the camera never publishes? Do I understand this Correctly? So Why Use the "Motion Sensor"? What am I missing? 
Thanx for any further direction
 Just a Quick Recap, I have a Camera that detects motion, I have added the Mention Sensor and hope to have that motion it detects to turn on a light in HomeKit.
Thanx again

**Comment by Sunoo** [comment]
Nothing in this plugin detects motion on its own, it relies on outside triggers (usually from your camera) to trip the motion sensor attached to the camera in HomeKit.

**Comment by fratinize** [comment]
I am still missing Something, please dumb down
So the Plug in itself does not detection “motion”, but the camera itself does, but…
What is the Trigger, isn’t that what a motion sensor does? 
Sorry I am Confused

**Comment by Sunoo** [comment]
The camera detects motion, but requires some channel to pass the motion alert to this plugin, those methods are HTTP, MQTT, or with a helper plugin, FTP or SMTP. Once the plugin gets notification of motion via one of those methods, it marks the motion sensor in HomeKit as being active.

**Comment by fratinize** [comment]
Ok, I think I got that as I was able to mosquito_pub and it triggered my scene with the topic
So, ii guess what I am not understanding is how to pass. Adding mqtt to the config, I thought that would publish my topic.

**Comment by fratinize** [comment]
Found sometime to revisit this, from what I have Learned and understand is that his plug in subscribes to my topic and When I publish "on" through a command line or in node red, it activates my automation!, I am Still struggling to pass this topic from my Waze cam...
