### ISSUE TITLE
Having trouble after reinstalling plugin to HOOBS 

### ISSUE THREAD

**Issue by nfstange** [Sunoo/homebridge-camera-ffmpeg#1296]
**Describe The Problem:**
My HOOBS device was acting up and when trying to fix it, I lost all my plugins. I reinstalled Cameraffmpeg and got my Wyze camera to work but for some reason my Lorex IP cameras are not wanting to work. I had all 4 Lorex cameras working prior and pasted the same config after reinstalling the plugin. I pasted the rstp in VLC and camera loads feed without issue. 

**Logs:**
5/18/2022, 7:34:24 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] [rtsp @ 0x3996280] method OPTIONS failed: 401 Unauthorized
5/18/2022, 7:34:24 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] rtsp://username:password:@ipaddress:554/cam/realmonitor?channel=1&subtype=0: Server returned 401 Unauthorized (authorization failed)
5/18/2022, 7:34:24 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] Failed to fetch snapshot.
5/18/2022, 7:34:24 PMCamera FFmpeg BridgeERROR[Outdoor] Snapshot request handler provided empty image buffer!
5/18/2022, 7:34:24 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Snapshot requested: 640 x 360
5/18/2022, 7:34:27 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Sending snapshot: 640 x 360
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Video stream requested: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Starting video stream: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info] ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavutil      57. 17.100 / 57. 17.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavcodec     59. 18.100 / 59. 18.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavformat    59. 16.100 / 59. 16.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavdevice    59.  4.100 / 59.  4.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavfilter     8. 24.100 /  8. 24.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswscale      6.  4.100 /  6.  4.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswresample   4.  3.100 /  4.  3.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libpostproc    56.  3.100 / 56.  3.100
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [tcp @ 0x27c2230] [verbose] Starting connection attempt to 192.168.1.2 port 554
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [tcp @ 0x27c2230] [verbose] Successfully connected to 192.168.1.2 port 554
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [rtsp @ 0x27bf950] [error] method OPTIONS failed: 401 Unauthorized
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [error] rtsp://username:password:@ipaddress:554/cam/realmonitor?channel=1&subtype=0: Server returned 401 Unauthorized (authorization failed)
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] FFmpeg exited with code: 1 and signal: null (Error)
5/18/2022, 7:34:28 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Stopped video stream.

**Homebridge Config:**

{
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Indoor Cam",
                    "manufacturer": "Wyze",
                    "model": "Wyze Cam Pan",
                    "firmwareRevision": "4.29.4.41",
                    "videoConfig": {
                        "source": "-i rtsp://user:password@ip/live",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "audio": true,
                        "forceMax": false,
                        "preserveRatio": false,
                        "debug": true
                    },
                    "doorbell": true,
                    "motion": true,
                    "switches": true
                },
                {
                    "name": "Outdoor",
                    "videoConfig": {
                        "source": "-i rtsp://username:password:@ipaddress:554/cam/realmonitor?channel=1&subtype=0",
                        "audio": false,
                        "debug": true,
                        "forceMax": false
                    },
                    "manufacturer": "Lorex Technology",
                    "model": "LNE9292B"
                }
            ]
        }
    ]
}

**Environment:**

* **Node.js Version**: 16.15.0

* **Homebridge Version**: 1.4.1

* **Homebridge Camera FFmpeg Version**: 3.1.4

* **Operating System**: HOOBS

**Comment by Sunoo** [comment]
From the logs it’s an authentication error. Are you sure your username and password to the camera are correct?

**Comment by nfstange** [comment]
> From the logs it’s an authentication error. Are you sure your username and password to the camera are correct?

Yes verified with VLC camera feed loads no problem

**Comment by nfstange** [comment]
> 

If I remove the -I as that's how it was before I reinstalled plugin this is the log I get which doesn't mention authentication error

5/18/2022, 8:09:42 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Configuring cached bridged accessory...
5/18/2022, 8:09:42 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Configuring cached bridged accessory...
5/18/2022, 8:09:42 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Configuring cached bridged accessory...
5/18/2022, 8:09:42 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Configuring cached bridged accessory...
5/18/2022, 8:09:42 PMCamera FFmpeg BridgeBridge is running on port 51886.
5/18/2022, 8:09:42 PMCamera FFmpeg BridgeBridge is running on port 51886.
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Snapshot requested: 640 x 360
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Snapshot requested: 640 x 360
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] [NULL @ 0x31d0310] Unable to find a suitable output format for 'rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0'
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] [NULL @ 0x31d0310] Unable to find a suitable output format for 'rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0'
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0: Invalid argument
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [Snapshot] rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0: Invalid argument
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] Failed to fetch snapshot.
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] Failed to fetch snapshot.
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeERROR[Outdoor] Snapshot request handler provided empty image buffer!
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeERROR[Outdoor] Snapshot request handler provided empty image buffer!
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Snapshot requested: 640 x 360
5/18/2022, 8:09:51 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Snapshot requested: 640 x 360
5/18/2022, 8:09:53 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Sending snapshot: 640 x 360
5/18/2022, 8:09:53 PMCamera FFmpeg BridgeCamera FFmpeg[Indoor Cam] Sending snapshot: 640 x 360
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Video stream requested: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Video stream requested: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Starting video stream: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Starting video stream: 1280 x 720, 30 fps, 299 kbps
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info] ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info] ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavutil      57. 17.100 / 57. 17.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavutil      57. 17.100 / 57. 17.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavcodec     59. 18.100 / 59. 18.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavcodec     59. 18.100 / 59. 18.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavformat    59. 16.100 / 59. 16.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavformat    59. 16.100 / 59. 16.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavdevice    59.  4.100 / 59.  4.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavdevice    59.  4.100 / 59.  4.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavfilter     8. 24.100 /  8. 24.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libavfilter     8. 24.100 /  8. 24.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswscale      6.  4.100 /  6.  4.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswscale      6.  4.100 /  6.  4.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswresample   4.  3.100 /  4.  3.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libswresample   4.  3.100 /  4.  3.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libpostproc    56.  3.100 / 56.  3.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] [info]   libpostproc    56.  3.100 / 56.  3.100
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [NULL @ 0x380fa10] [error] Unable to find a suitable output format for 'rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0'
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [NULL @ 0x380fa10] [error] Unable to find a suitable output format for 'rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0'
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [error] rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0: Invalid argument
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] [error] rtsp://user:password:@ip:554/cam/realmonitor?channel=1&subtype=0: Invalid argument
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] FFmpeg exited with code: 1 and signal: null (Error)
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpegERROR[Outdoor] FFmpeg exited with code: 1 and signal: null (Error)
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Stopped video stream.
5/18/2022, 8:09:54 PMCamera FFmpeg BridgeCamera FFmpeg[Outdoor] Stopped video stream.

**Comment by Sunoo** [comment]
It’ll never have worked without `-i`.

**Comment by nfstange** [comment]
Ok so any suggestions to try. Like I stated this had worked before the reinstall and has been fine since initial setup. 

Thanks

**Comment by Sunoo** [comment]
The only thing in your logs is authentication failed, which points to bad username and password.

**Comment by nfstange** [comment]
Ok so would you know how it works in VLC and not this plug-in?

**Comment by Sunoo** [comment]
Not a clue, maybe you have a typo in the config.
