### ISSUE TITLE
homebridge-camera-ffmpeg + Zoneminder

### ISSUE THREAD

**Issue by mfauvain** [Sunoo/homebridge-camera-ffmpeg#1305]
Hi, thx for the great plugin. In order to integrate fully with Zoneminder it would be great to have
- MQTT payload parsing. For example another plugin (MQQTthing plugin : https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#jsonpath) uses jsonpath and it works perfect using a MQTT topic like zoneminder/1$.state where zoneminder/1 is the monitor number 1. 

- With the parsing available, it would great to be able to include an mqtt payload in the still image source, so one could use something like zoneminder/1$.eventid in the still image direction to get the alarmed image like so : 
"zmserverip:port/index.php?view=image&eid=" + **zoneminder/1$.eventid** + "&fid=objdetect&width=600&token=..."

**Comment by Sunoo** [comment]
JSONPath is on my todo list already, not sure when it’ll be implemented.

I’m not sure I understand your second request though.

**Comment by mfauvain** [comment]
The second one is the ability to add a mqtt payload to the still image url string. In this case inserting the eventid (received from mqtt topic zoneminder/1$.eventid) so that the still image is a specific still image from zoneminder and not the last available from the camera.

**Comment by Sunoo** [comment]
I have some longer term plans to support some things along those lines (pre-loading specific images into the snaoshot cache), but I haven’t really come up with how that should work yet.

**Comment by mfauvain** [comment]
thx

**Comment by mfauvain** [comment]
Hi, for the first point, using [https://github.com/jpmens/mqtt-launcher](url) and a small python script that parse the initial payload, it works perfect.

For the second one, any chance to allow an MQTT topic instead of a fixed http direction? Like below?
![220627-174158](https://user-images.githubusercontent.com/14844435/176049335-3fca22c9-de44-4534-9781-0dc491ce587c.jpg)

Thx

**Comment by Sunoo** [comment]
The problem with using MQTT for the URL is what happens when HomeKit calls for a snapshot some time besides a motion alert?

**Comment by mfauvain** [comment]
I see.. we would need a Still Image Source, and a Motion Image Source then...

**Comment by mfauvain** [comment]
What could work is overriding Still Image Source when a motion event is detected and reverting to the original setting after a a given time..
