### ISSUE TITLE
Live View Very Slow

### ISSUE THREAD

**Issue by zzack01** [Sunoo/homebridge-camera-ffmpeg#1311]
Hello,

Can you please help me help others, I am helping people with thier insteon systems and the cameras are view slow live view, even though someone walks past the camera and back past it it only shows up for a second of the person in the middle. Any recommendations on how to get a faster live view?

**Comment by Sunoo** [comment]
You can try fiddling with probesize and analyzeduration, you can put them at the start of your source. The lowest possible values are `-probesize 32 -analyzeduration 0`, but that can cause sporadic issues with some cameras, so you may want to try raising them until things work consistently.
