### ISSUE TITLE
Image blurry and green

### ISSUE THREAD

**Issue by zzack1** [Sunoo/homebridge-camera-ffmpeg#1312]
Hello,

Can you help me figure out why my camera look like this? In there native app they all work perfectly 

![Screen Shot 2022-06-18 at 3 36 05 PM](https://user-images.githubusercontent.com/105042156/174459140-83c0ee46-bce2-46cc-8586-daf3ab4cecd3.png)
![Screen Shot 2022-06-18 at 3 36 05 PM](https://user-images.githubusercontent.com/105042156/174459154-538fe4c3-edaf-4450-95f3-9c1cd1f07ac3.png)

**Comment by Sunoo** [comment]
Is it bad in live video too, or just the snapshots?

**Comment by zzack1** [comment]
in both

**Comment by zzack1** [comment]
also is there a way to pull all the cameras from a nvr?

**Comment by Sunoo** [comment]
You would have to add each one separately.

**Comment by zzack1** [comment]
any way to get a better picture?

**Comment by zzack1** [comment]
Also if my router only shows one ip address for my nvr, and my nvr shows another ip address for the camera how would I config that? ex router shows ip address of nvr at 192.168.1.15 and the nvr shows the camera ip address at 10.0.0.56

**Comment by Sunoo** [comment]
Each camera should have a different RTSP URL. I would expect you should be able to find it somewhere in the NVR.
