### ISSUE TITLE
Getting the following error: FFmpeg process creation failed

### ISSUE THREAD

**Issue by macstainless** [Sunoo/homebridge-camera-ffmpeg#1321]
About two weeks ago my WyzeCam stopped working within the Home app. It's continued to work natively in the Wyze app. 

Additionally, when I try to view the RTSP stream in an app like VLC, it loads up no problem. I can view the stream through there just fine.

I've checked my homebridge configuration and even copied the config from [here](https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Wyze-Cam-v2-and-Pan.html) but it doesn't make a difference. Hoping there's a quick and easy fix for this. Thanks.

When checking my Homebridge logs, I'm getting the following errors:
```[7/14/2022, 12:15:31 PM] [Camera FFmpeg] [House Cam] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[7/14/2022, 12:15:31 PM] [Camera FFmpeg] [House Cam] FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
[7/14/2022, 12:15:31 PM] [Camera FFmpeg] [House Cam] Stopped video stream.
[7/14/2022, 12:15:43 PM] [Camera FFmpeg] [House Cam] FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
[House Cam] Snapshot request handler provided empty image buffer!```

**Comment by jlg89** [comment]
What version of homebridge are you running?

**Comment by idominiki** [comment]
Same problem here. Homebridge Version 1.5.0

**Comment by macstainless** [comment]
I'm on version 1.5.0.

**Comment by sommo** [comment]
me too

**Comment by sommo** [comment]
resolved with unistall and install again the plugin

**Comment by idominiki** [comment]
> resolved with unistall and install again the plugin

Doesn't work for me

**Comment by jetmcquack** [comment]
same problem here, still not fixed

**Comment by jlg89** [comment]
I'm on homebridge 1.5.0, Node 16.17.1, plugin v3.1.4, and I have two different installs working fine. If you've tried uninstalling the plugin, restarting the homebridge box, and reinstalling the plugin, I would try running an update (sudo apt update && apt upgrade) as part of the process.
