### ISSUE TITLE
loglevel error (+verbose)

### ISSUE THREAD

**Issue by trigal** [Sunoo/homebridge-camera-ffmpeg#1325]
- plugin v3.1.4
- ffmpeg version 3.2.18-0+deb9u1 Copyright (c) 2000-2022 the FFmpeg developers built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
- Homebridge v1.5.0 (HAP v0.10.2)

https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/dfbf2cb10e772ed815aaf0843850b841bf1ded2a/src/streamingDelegate.ts#L410

The line above is generating an error with the loglevel, enabling debug in homebridge i saw this :

`-loglevel level+verbose -progress pipe:1`

ffmpeg requires something like "-loglevel verbose" without that "+" sign.

I changed:
`ffmpegArgs += ' -loglevel level' + (this.videoConfig.debug ? '+verbose' : '') +
' -progress pipe:1';`
to
`ffmpegArgs += ' -loglevel ' + (this.videoConfig.debug ? 'verbose' : '') +
' -progress pipe:1';`

and now works like a charm

**Comment by Sunoo** [comment]
Per the ffmpeg documentation, and my own testing, level+verbose is a valid setting.

**Comment by zobe123** [comment]
removing "level" from  code also worked for me, now i can  see debug output
