### ISSUE TITLE
Camera declared a microphone and no image shown

### ISSUE THREAD

**Issue by FortyTwoCoding** [Sunoo/homebridge-camera-ffmpeg#1335]
**The problem**
I have a Raspberry Pi Zero W v1.1 set up with a Pi camera v2. Using the following [GitHub repository](https://github.com/mpromonet/v4l2rtspserver), I made the Pi Zero run a stream. The stream is working fine and I can receive it on another device using VLC Media Player. However, on my other Raspberry Pi 3B+ running Homebridge I am unable to receive the Camera stream, using this ffmpeg plugin. It declares the camera a microphone, even though I did not even enable audio. I really want to see the camera stream, any help is appreciated!

**To Reproduce:**
I used this [guide](https://siytek.com/raspberry-pi-rtsp-to-home-assistant/) to get the RTSP stream running. Homebridge is in the same network as the camera. 

**Logs:**
I did not really get an error, these are the only two entries regarding the ffmpeg plugin
```
[31/08/2022, 13:42:50] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[31/08/2022, 13:42:50] [Camera FFmpeg] [Eingang Nord] Configuring bridged accessory...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 730D",
        "username": "0E:37:92:35:73:0D",
        "port": 51900,
        "pin": "360-89-154",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Eingang Nord",
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.3.151:8554/unicast",
                        "maxStreams": 1,
                        "maxFPS": 10
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}
```

**Screenshots:**
<img width="543" alt="Bildschirmfoto 2022-08-31 um 14 01 21" src="https://user-images.githubusercontent.com/68070089/187673902-a955a5c0-8a00-44d7-906c-0be738400bc3.png">

**Environment:**

* **Node.js Version**: v16.16.0
* **NPM Version**: What is this?
* **Homebridge Version**: v1.5.0
* **Homebridge Camera FFmpeg Version**: homebridge-camera-ffmpeg v3.1.4
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.50.1
* **Operating System**: Raspian (I assume - I flashed home bridge using the RPi imager. I don't really get how HomeBridge works :( )

**Comment by Sunoo** [comment]
Cameras don’t currently appear in the Homebridge UI, only on iOS devices.
