### ISSUE TITLE
Cameras not working on tvos16

### ISSUE THREAD

**Issue by wangel** [Sunoo/homebridge-camera-ffmpeg#1340]
After upgrading my AppleTV's to tvOS16, the camera's no long work.

They do work on my phone with ios16, but I can't get them to work on tvOS16.

To test this,  I upgraded 2 of my tv's, the camera's stopped working.  On the TV that still worked, it was running tvOS15.6 and the camera's worked fine.

After upgrading that tv to tvOS16, the cameras stop working and report "15minutes" as the last time it was connected (at the time of my testing)

Not sure where I can start debugging but if there's anything I can do to get more info, will be glad to start grabbing/debugging.

**Comment by Sunoo** [comment]
I haven’t tested tvOS 16 yet, guessing they got pickier about what streams they accept again.

**Comment by wangel** [comment]
Well good =(   Anything I can do to help debug / fix it?  It's not that big a deal, it seems to still work on ios16. :D

**Comment by Sunoo** [comment]
I’ll just have to look when I have a chance I guess. Apple TV has always been weirdly picky about showing cameras. I personally never look at my cameras on them either, but I am aware they’re problematic.

Would be nice to hear from others to see if it’s happening to everyone or just a few.

**Comment by wangel** [comment]
I never really look @ my cameras either, but my kids liked sneaking into the room I keep snacks / lunch stuff in in my garage, so I had it setup when I was in my bedroom upstairs watching TV it'd pop up on my tv if the camera detected motion @ night, and it would show them sneaking in so I could go bust them :P

Again, like you said, it's no big deal just something I ran across

**Comment by jlg89** [comment]
What vcodec are you using? If it's "copy," you might try using libx264 and see if that fixes the ATV issue. Also check the ffmpeg debug log when the ATV requests a video stream, see what it's asking for.

**Comment by StephenShamakian** [comment]
I'm having the same problem with tvOS 16 and tvOS 16.1.

The only temporary fix is to go into settings > HomeKit > Cameras and have to turn one camera off then back on again.

The feeds will then load for a while as notifications but after an undisclosed amount of time they will start failing to load again.

Cameras also don't load their feeds if I manually browse to them as well when having this problem.

What's strange is when a motion event occurs and triggers a camera alert on tvOS it never generates a message in homebridge that the camera was loaded. Just shows a grey box on the AppleTV.

Everything works fine in my iPhone running iOS 16/16.1

**Comment by Pistola1900** [comment]
Looks like they made some changes as im having the same issue.

The temporary fix isn't working for me either.

Has anyone else experienced this or been able to solve it?

**Comment by StephenShamakian** [comment]
Bumping, problem still persists with tvOS 16.2

**Comment by sweetw0r** [comment]
Not working for me also

**Comment by StephenShamakian** [comment]
So I have an update.

I was able to upgrade my HomeKit home to the new architecture (before Apple pulled the update) and that has fixed my cameras for HomeBridge, both for ffmpeg and UniFi Protect. They have been working solidly for 2+ weeks now.

So at this rate I would say wait till Apple re-releases the HomeKit architecture upgrade as it may fix your issues.

**Comment by mhuca** [comment]
Bump... Still unresolved.. Ever since I upgraded to the new HomeKit Architecture none of the cameras are working.. TVOs 16.3

**Comment by jlg89** [comment]
At this point, this plugin still works fine for basic video streams in HomeKit, but Sunoo isn't able to devote any dev time to it, so issues may or may not be addressed anytime soon. If you want full HomeKit support right now, Scrypted is really the only viable option.

**Comment by Sunoo** [comment]
I haven’t been able to update to the new HomeKit, so I cannot test anything with that until Apple puts it back out.
