### ISSUE TITLE
Hikvision DS-7608NI-K2 NVR setup fails

### ISSUE THREAD

**Issue by khwerhahn** [Sunoo/homebridge-camera-ffmpeg#1341]
**Describe The Problem:**
I'm using a Hikvision DS-7608NI-K2 and cannot get it to work even though URLs of video feeds works through VLC and still images are also displayed in the browser. So the URLs are correct. I have used the details such as video dimensions etc from vlc info.

**To Reproduce:**

**Logs:**
![image](https://user-images.githubusercontent.com/3821617/190190037-bf6ba604-b4aa-4e74-92e4-d617493b814c.png)

**Config:**

```json
{
    "platform": "Camera-ffmpeg",
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "Hof",
            "manufacturer": "HIK",
            "model": "Camera",
            "serialNumber": "12345678",
            "motion": false,
            "videoConfig": {
                "source": "-re -i rtsp://xxx:xxx@192.168.0.230:554/Streaming/Channels/201",
                "stillImageSource": "-i http://xxx:xxx@192.168.0.230:80/ISAPI/Streaming/channels/201/picture",
                "maxStreams": 2,
                "mapvideo": "201",
                "maxWidth": 2688,
                "maxHeight": 1520,
                "vcodec": "libx264",
                "maxFPS": 25
            },
            "firmwareRevision": "12345678"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: 16.17.0
* **Homebridge Version**: 1.5.0
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: Hoobs 4.2.8 on RPI

**Comment by dbrewood** [comment]
I use this:
{
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "Drive Cam",
            "manufacturer": "HIKVision",
            "model": "DDS-2CD2087G2-L(U)",
            "motion": true,
            "motionDoorbell": true,
            "unbridge": false,
            "videoConfig": {
                "source": "-i rtsp://xxxxx:xxxxx@192.168.1.77/Streaming/Channels/101/",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "mapvideo": "102",
                "audio": false
            }
        }
    ],
    "platform": "Camera-ffmpeg"
}
