### ISSUE TITLE
Video lagging....

### ISSUE THREAD

**Issue by dbrewood** [Sunoo/homebridge-camera-ffmpeg#1345]
**Describe The Problem:**
After adding one of my HIKVision cameras into Homebridge (running on my Synology NAS) I'm seeing the thumbnail looking like the bottom half of the video is streaked. When I tap on the camera image I get a 'no response' message.

**To Reproduce:**

I've played with the various configuration options but nothing seems to make a difference

**Logs:**
[10/2/2022, 11:16:14 AM] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[10/2/2022, 11:16:14 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[10/2/2022, 11:16:14 AM] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[10/2/2022, 11:16:14 AM] [Camera FFmpeg] [Drive Cam] Configuring cached bridged accessory...

**Homebridge Config:**

```json
{
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "Drive Cam",
            "manufacturer": "HIKVision",
            "model": "DDS-2CD2087G2-L(U)",
            "motion": true,
            "motionDoorbell": true,
            "unbridge": false,
            "videoConfig": {
                "source": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/101/",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "mapvideo": "102",
                "audio": false
            }
        }
    ],
    "platform": "Camera-ffmpeg"
}
```

**Screenshots:**

![Union_Cams](https://user-images.githubusercontent.com/93347139/193448783-a51760e0-9544-4f9f-bc2b-876c9005013f.jpg)

**Environment:**

* **Node.js Version**: [v16.16.0]
* **NPM Version**: No ideas how to get this
* **Homebridge Version**: 1.5.0
* **Homebridge Camera FFmpeg Version**: homebridge-camera-ffmpeg v3.1.4
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.50.1
* **Operating System**: Docker on Synology NAS

**Comment by dbrewood** [comment]
Hmm errors have now appeared in the logs:

> [10/2/2022, 10:58:47 AM] [Camera FFmpeg] [Drive Cam] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[10/2/2022, 10:58:49 AM] [Camera FFmpeg] [Drive Cam] FFmpeg exited with code: 1 and signal: null (Error)
[10/2/2022, 10:58:49 AM] [Camera FFmpeg] [Drive Cam] Stopped video stream.
[10/2/2022, 10:59:16 AM] [ADT Security System] Updating sensor Dining Room Motion (Occupancy Sensor) (103660714-4), state=0, prev=1
[10/2/2022, 11:00:26 AM] [ADT Security System] Logging into Alarm.com as xxxx
[10/2/2022, 11:00:28 AM] [ADT Security System] Logged into Alarm.com xxxx
[10/2/2022, 11:03:03 AM] [Camera FFmpeg] [Drive Cam] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[10/2/2022, 11:03:05 AM] [Camera FFmpeg] [Drive Cam] FFmpeg exited with code: 1 and signal: null (Error)
[10/2/2022, 11:03:05 AM] [Camera FFmpeg] [Drive Cam] Stopped video stream.
[10/2/2022, 11:03:13 AM] [Camera FFmpeg] [Drive Cam] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[10/2/2022, 11:03:14 AM] [Camera FFmpeg] [Drive Cam] FFmpeg exited with code: 1 and signal: null (Error)
[10/2/2022, 11:03:14 AM] [Camera FFmpeg] [Drive Cam] Stopped video stream.

**Comment by jlg89** [comment]
Have you tried different vcodec settings? I'd specifically try libx264. The snapshot issue might be fixable using the stillImageSource directive.

Something like:

```json
"stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/101/ -vframes 1 -r 1",
"vcodec": "libx264",
```

**Comment by dbrewood** [comment]
It didn't help alas with config of:

>                 {
>                     "name": "Patio Cam HB TEST",
>                     "manufacturer": "HIKVision",
>                     "model": "DDS-2CD2087G2-L(U)",
>                     "unbridge": true,
>                     "stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/101/ -vframes 1 -r 1",
>                     "vcodec": "libx264",
>                     "videoConfig": {
>                         "source": "-i rtsp:///user:pwd(user:pwd)@192.168.1.77/Streaming/Channels/303/",
>                         "maxStreams": 2,
>                         "maxWidth": 1280,
>                         "maxHeight": 720,
>                         "maxFPS": 25,
>                         "audio": false
>                     }
>                 }
Then the camera appears as a microphone accessory only (no motion sensor) and can't be added into Home. Secondary to this I'm not seeing any motion detection taking place or the 'recording bar' beneath the camera view. 
I'm wondering if these issues is because I'm getting the feeds via the NVR and not the camera itself?

**Comment by jlg89** [comment]
The vcodec directive needs to be inside the videoconfig section. 

You won't see the recording bar in the Home app because this plugin doesn't currently support HSV. So if you want motion detection alerts in HomeKit, you'll have to use something like an MQTT or Webhooks setup to allow your NVR to push motion events to the plugin.

**Comment by dbrewood** [comment]
Ah ha right, I'll see how it goes, but I think I'll put the project on hold for the moment as I've got most functionality in the HIKVision app itself. The main aim was to get the motion sensors in there in a simple manner :)
Thanks for the assistance and clarification.

**Comment by dbrewood** [comment]
Well I've decided to go ahead with it as it should hopefully allow me to view the feeds from my watch :) Would you say the following is a viable configuration:


> {
>     "name": "Camera FFmpeg",
>     "cameras": [
>         {
>             "name": "Drive Cam HB",
>             "manufacturer": "HIKVision",
>             "model": "DDS-2CD2087G2-L(U)",
>             "motion": true,
>             "motionDoorbell": true,
>             "unbridge": true,
>             "stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/102/ -vframes 1 -r 1",
>             "videoConfig": {
>                 "source": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/102/",
>                 "vcodec": "libx264",
>                 "maxStreams": 2,
>                 "maxWidth": 640,
>                 "maxHeight": 480,
>                 "maxFPS": 15,
>                 "audio": false
>             }
>         },
>         {
>             "name": "Patio Cam HB",
>             "manufacturer": "HIKVision",
>             "model": "DDS-2CD2087G2-L(U)",
>             "unbridge": true,
>             "stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/302/ -vframes 1 -r 1",
>             "videoConfig": {
>                 "source": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/302/",
>                 "vcodec": "libx264",
>                 "maxStreams": 2,
>                 "maxWidth": 640,
>                 "maxHeight": 480,
>                 "maxFPS": 15,
>                 "audio": false
>             }
>         }
>     ],
>     "_bridge": {
>         "username": "0E:E6:87:8F:97:98",
>         "port": 54692
>     },
>     "platform": "Camera-ffmpeg"
> }

**Comment by jlg89** [comment]
stillImageSource needs to be inside the videoConfig section. Otherwise, it seems to look OK. Give it a shot.

**Comment by dbrewood** [comment]
Ah ha right so like this:

> {
>     "name": "Camera FFmpeg",
>     "cameras": [
>         {
>             "name": "Drive Cam HB",
>             "manufacturer": "HIKVision",
>             "model": "DDS-2CD2087G2-L(U)",
>             "motion": true,
>             "motionDoorbell": true,
>             "unbridge": true,
>             "videoConfig": {
>                 "source": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/102/",
>                 "stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/102/ -vframes 1 -r 1",
>                 "vcodec": "libx264",
>                 "maxStreams": 2,
>                 "maxWidth": 640,
>                 "maxHeight": 480,
>                 "maxFPS": 15,
>                 "audio": false
>             }
>         },
>         {
>             "name": "Patio Cam HB",
>             "manufacturer": "HIKVision",
>             "model": "DDS-2CD2087G2-L(U)",
>             "unbridge": true,
>             "videoConfig": {
>                 "source": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/302/",
>                 "stillImageSource": "-i rtsp://user:pwd@192.168.1.77/Streaming/Channels/302/ -vframes 1 -r 1",
>                 "vcodec": "libx264",
>                 "maxStreams": 2,
>                 "maxWidth": 640,
>                 "maxHeight": 480,
>                 "maxFPS": 15,
>                 "audio": false
>             }
>         }
>     ],
>     "_bridge": {
>         "username": "0E:E6:87:8F:97:98",
>         "port": 54692
>     },
>     "platform": "Camera-ffmpeg"
> }

**Comment by dbrewood** [comment]
And that is indeed working well, thanks for the assistance.
