### ISSUE TITLE
Fixed port for unbridge mode

### ISSUE THREAD

**Issue by xyz4tech** [Sunoo/homebridge-camera-ffmpeg#1374]
It would be really great to have in this awesome plugin an option to add a fixed port if the unbridge mode is used. With the realization of a dynamically picked port it's currently a challenge to configure a firewall.

Many thanks.

**Comment by Sunoo** [comment]
It’s been a bit since I looked into that piece of things, but my recollection was that there was unfortunately no real way to force a specific port.
