### ISSUE TITLE
How to activate Secure Video

### ISSUE THREAD

**Issue by gerd2005** [Sunoo/homebridge-camera-ffmpeg#1380]
**Describe The Problem:**
I use HOOBS on a Synology (Docker) and I installed the "camera ffmpeg"-PlugIn. My Camera is in Homekit now, but Secure Video isnt active, I I dont know how I can activate it.

**Logs:**

21.2.2023, 21:35:09 Got SIGINT, shutting down Bridge...
21.2.2023, 21:35:15 Initializing HAP-NodeJS v0.9.3...
21.2.2023, 21:35:15 Loaded plugin 'homebridge-camera-ffmpeg'
21.2.2023, 21:35:15 [2/21/2023, 10:35:15 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
21.2.2023, 21:35:15 Loading 1 platforms...
21.2.2023, 21:35:15 [Camera FFmpeg] Initializing Camera-ffmpeg platform...
21.2.2023, 21:35:15 [Camera FFmpeg] [Wohnzimmer] Configuring cached bridged accessory...
21.2.2023, 21:35:15 Preparing Advertiser for 'HOOBS 682E' using bonjour-hap backend!
21.2.2023, 21:35:15 Starting to advertise 'HOOBS 682E' using bonjour-hap backend!
21.2.2023, 21:35:15 Bridge is running on port 51826.
21.2.2023, 21:35:22 [Camera FFmpeg] [Wohnzimmer] Snapshot requested: 640 x 360
21.2.2023, 21:35:22 [Camera FFmpeg] [Wohnzimmer] Fetching snapshot took 0.25 seconds.
21.2.2023, 21:35:22 [Camera FFmpeg] [Wohnzimmer] Sending snapshot: 640 x 360
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] Video stream requested: 1280 x 720, 30 fps, 299 kbps
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info] ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   built with gcc 9.3.0 (Alpine 9.3.0)
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libavutil      57. 17.100 / 57. 17.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libavcodec     59. 18.100 / 59. 18.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libavformat    59. 16.100 / 59. 16.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libavdevice    59.  4.100 / 59.  4.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libavfilter     8. 24.100 /  8. 24.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libswscale      6.  4.100 /  6.  4.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libswresample   4.  3.100 /  4.  3.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [info]   libpostproc    56.  3.100 / 56.  3.100
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [tcp @ 0x55d5d91d4840] [verbose] Starting connection attempt to 192.168.178.67 port 554
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [tcp @ 0x55d5d91d4840] [verbose] Successfully connected to 192.168.178.67 port 554
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [rtsp @ 0x55d5d91d4200] [verbose] SDP:
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] v=0
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] o=- 1676891896523375 1 IN IP4 192.168.178.67
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] s=Session streamed by "preview"
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] i=h264Preview_01_sub
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] t=0 0
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=tool:LIVE555 Streaming Media v2020.08.12
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=type:broadcast
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=control:*
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=range:npt=0-
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=x-qt-text-nam:Session streamed by "preview"
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=x-qt-text-inf:h264Preview_01_sub
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] m=video 0 RTP/AVP 96
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] c=IN IP4 0.0.0.0
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] b=AS:500
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=rtpmap:96 H264/90000
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgL/lQ,aO48sA==
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=control:track1
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] m=audio 0 RTP/AVP 97
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] c=IN IP4 0.0.0.0
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] b=AS:256
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=rtpmap:97 MPEG4-GENERIC/16000
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] a=control:track2
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] 
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [rtsp @ 0x55d5d91d4200] [verbose] setting jitter buffer size to 500
21.2.2023, 21:35:28 [Camera FFmpeg] [Wohnzimmer] [rtsp @ 0x55d5d91d4200] [verbose] setting jitter buffer size to 500
21.2.2023, 21:35:30 [Camera FFmpeg] [Wohnzimmer] [h264 @ 0x55d5da885980] [verbose] Reinit context to 640x368, pix_fmt: yuv420p
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] Input #0, rtsp, from 'rtsp://admin:01454312@192.168.178.67:554/h264Preview_01_sub':
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Metadata:
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     title           : Session streamed by "preview"
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     comment         : h264Preview_01_sub
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Duration: N/A, start: 0.000313, bitrate: N/A
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(progressive), 640x360 (640x368), 25.17 tbr, 90k tbn
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] Output #0, rtp, to 'srtp://192.168.178.63:63218?rtcpport=63218&pkt_size=1316':
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Metadata:
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     title           : Session streamed by "preview"
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     comment         : h264Preview_01_sub
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     encoder         : Lavf59.16.100
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(tv, progressive), 640x360 (0x0), q=2-31, 25.17 tbr, 90k tbn
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] Stream mapping:
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #0:0 -> #0:0 (copy)
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #0:1 -> #1:0 (aac (native) -> aac (libfdk_aac))
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] Press [q] to stop, [?] for help
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [graph_0_in_0_1 @ 0x55d5da90aa40] [verbose] tb:1/16000 samplefmt:fltp samplerate:16000 chlayout:0x4
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [format_out_1_0 @ 0x55d5da90b140] [verbose] auto-inserting filter 'auto_aresample_0' between the filter 'Parsed_anull_0' and the filter 'format_out_1_0'
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [auto_aresample_0 @ 0x55d5da90bc80] [verbose] ch:1 chl:mono fmt:fltp r:16000Hz -> ch:1 chl:mono fmt:s16 r:16000Hz
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] Output #1, rtp, to 'srtp://192.168.178.63:60846?rtcpport=60846&pkt_size=188':
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Metadata:
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     title           : Session streamed by "preview"
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     comment         : h264Preview_01_sub
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     encoder         : Lavf59.16.100
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]   Stream #1:0: Audio: aac (ELD), 16000 Hz, mono, s16, delay 288, 24 kb/s
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]     Metadata:
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info]       encoder         : Lavc59.18.100 libfdk_aac
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [info] frame=    0 fps=0.0 q=-1.0 size=       0kB time=00:00:00.04 bitrate=   0.0kbits/s speed=4.6e+04x    
21.2.2023, 21:35:31 [Camera FFmpeg] [Wohnzimmer] [rtp @ 0x55d5daa3f240] [warning] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
21.2.2023, 21:35:32 [Camera FFmpeg] [Wohnzimmer] [info] frame=   36 fps=0.0 q=-1.0 size=      59kB time=00:00:03.84 bitrate= 125.7kbits/s speed=7.44x    
21.2.2023, 21:35:32 [Camera FFmpeg] [Wohnzimmer] Getting the first frames took 3.926 seconds.
21.2.2023, 21:35:32 [Camera FFmpeg] [Wohnzimmer] [info] frame=   44 fps= 43 q=-1.0 size=      67kB time=00:00:04.36 bitrate= 125.6kbits/s speed=4.26x    
21.2.2023, 21:35:33 [Camera FFmpeg] [Wohnzimmer] [info] frame=   51 fps= 33 q=-1.0 size=      73kB time=00:00:04.87 bitrate= 122.8kbits/s speed= 3.2x    
21.2.2023, 21:35:33 [Camera FFmpeg] [Wohnzimmer] [info] frame=   59 fps= 29 q=-1.0 size=      80kB time=00:00:05.38 bitrate= 121.4kbits/s speed=2.63x    
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [info] frame=   67 fps= 26 q=-1.0 size=      99kB time=00:00:05.89 bitrate= 137.6kbits/s speed= 2.3x    
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] Stopped video stream.
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [info] 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [q] command received. Exiting.
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [info] frame=   70 fps= 25 q=-1.0 Lsize=     105kB time=00:00:06.12 bitrate= 140.6kbits/s speed=2.18x    
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [AVIOContext @ 0x55d5d91d4080] [verbose] Statistics: 1375 bytes written, 0 seeks, 7 writeouts
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [info] video:104kB audio:14kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose] Input file #0 (rtsp://admin:01454312@192.168.178.67:554/h264Preview_01_sub):
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Input stream #0:0 (video): 70 packets read (106376 bytes); 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Input stream #0:1 (audio): 74 packets read (38406 bytes); 74 frames decoded (75776 samples); 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Total: 144 packets (144782 bytes) demuxed
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose] Output file #0 (srtp://192.168.178.63:63218?rtcpport=63218&pkt_size=1316):
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Output stream #0:0 (video): 70 packets muxed (106376 bytes); 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Total: 70 packets (106376 bytes) muxed
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose] Output file #1 (srtp://192.168.178.63:60846?rtcpport=60846&pkt_size=188):
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Output stream #1:0 (audio): 148 frames encoded (75776 samples); 149 packets muxed (14304 bytes); 
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [verbose]   Total: 149 packets (14304 bytes) muxed
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [AVIOContext @ 0x55d5daa2f180] [verbose] Statistics: 107573 bytes written, 0 seeks, 113 writeouts
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] [AVIOContext @ 0x55d5da93dc40] [verbose] Statistics: 16716 bytes written, 0 seeks, 150 writeouts
21.2.2023, 21:35:34 [Camera FFmpeg] [Wohnzimmer] FFmpeg exited with code: 0 and signal: null (Expected)
**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```
"description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Wohnzimmer",
                    "motion": true,
                    "videoConfig": {
                        "source": "-i rtsp://admin:01454312@192.168.178.67:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.178.67/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=01454312&width=640&height=480 ",
                        "maxStreams": 2,
                        "maxWidth": 3840,
                        "maxHeight": 2160,
                        "maxFPS": 30,
                        "vcodec": "copy",
                        "debug": true,
                        "audio": true,
                        "hsv": true
                    }
                }
            ],
            "name": "Camera FFmpeg"
        }
    ]
}

**Comment by Sunoo** [comment]
This plugin does not currently have HSV support.

**Comment by gerd2005** [comment]
Hi,

thank you for your quick answer!

**Comment by jaranor** [comment]
> Este complemento actualmente no tiene soporte para HSV.

Hola, yo tambien estoy interesado en la grabacion en icloud Homekit Secure, que complementos llevan esto?? gracias
