### ISSUE TITLE
eufycam rtsp problems

### ISSUE THREAD

**Issue by koweye** [Sunoo/homebridge-camera-ffmpeg#1395]
i have enabled rtsp stream on eufycam s330. however i keep seeing this error. i am running hoobs 4.3.0

4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg
ERROR [Right Gate Cam] Failed
to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg ERROR [Right Gate Cam] Failed to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg ERROR [Right Gate Cam] Failed to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR [Right Gate Cam] Snapshot request
handler provided empty image buffer!
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR [Right Gate Cam] Snapshot request
handler provided empty image buffer!
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR [Right Gate Cam] Snapshot request
handler provided empty image buffer!
4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg
ERROR [Left Gate Caml Failed
to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg ERROR [Left Gate Cam] Failed to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge Camera FFmpeg
ERROR [Left Gate Caml Failed
to fetch snapshot.
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR [Left Gate Cam] Snapshot request
handler provided empty image buffer!
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR [Left Gate Cam] Snapshot request
handler provided empty image buffer!
4/19/2023, 6:20:03 PM Homekit Bridge
ERROR
[Left Gate Cam] Snapshot request

**Comment by Sunoo** [comment]
Sounds like your config is wrong, can you share what you have?

**Comment by koweye** [comment]
sure... here is my config

{
    "platform": "Camera-ffmpeg",
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "Man Cave Cam",
            "manufacturer": "Eufy",
            "model": "Indoor Pan Tilt",
            "videoConfig": {
                "source": "-re -i rtsp://10.10.100.109/live0",
                "audio": true
            }
        },
        {
            "name": "Right Gate Cam",
            "manufacturer": "Eufy",
            "model": "S330",
            "videoConfig": {
                "source": "-i rtsp://10.10.100.118/live1",
                "audio": true
            }
        },
        {
            "name": "Left Gate Cam",
            "manufacturer": "Eufy",
            "model": "S330",
            "videoConfig": {
                "source": "-i rtsp://10.10.100.118/live0",
                "audio": true
            }
        }
    ]
}

**Comment by Sunoo** [comment]
Do all cameras fail or just one? What do the logs show if you enable debug?

**Comment by koweye** [comment]
the one thats called man cave cam works. thats a different camera though, its a pan tilt. the other two are S330. not sure if that has anything to do with it.

sorry, where do i enable debug?

**Comment by Sunoo** [comment]
`"debug": true` in the videoConfig section: https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/master/README.md#optional-videoconfig-parameters
