### ISSUE TITLE
Motion reported twice

### ISSUE THREAD

**Issue by mfauvain** [Sunoo/homebridge-camera-ffmpeg#1396]
Hi, I've setup the plugin to report motion with mqtt triggers, however motion is reported twice. 
One has the still image source embedded and one is just a notification without image.
I've checked the mqtt msg sent, and there is indeed only one msg.
Any idea why?

**Comment by Sunoo** [comment]
Can you enable dubugging and share your logs?

**Comment by mfauvain** [comment]
SOLVED: adding ffmpeg bridge to the Home app (but leaving the cameras as 'unbridged' did solve the issue.. Now receiving only one notification (with it's embedded image).
