### ISSUE TITLE
Motion detection not working 

### ISSUE THREAD

**Issue by MLVC** [Sunoo/homebridge-camera-ffmpeg#1404]
**Describe The Problem:**
 motion detection not working after latest update

**To Reproduce:**

Install update I assume
**Logs:**
 no clue how to create a log. 

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by jlg89** [comment]
Without logs & config, there's no way for anyone to help you.
