### ISSUE TITLE
ffmpeg not overwriting files automatically

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Sunoo/homebridge-camera-ffmpeg#1406]
**Describe The Problem:**

8/11/2023, 11:00:06 PM] [Camera FFmpeg] [Intersection 110-00-110] File '299k' already exists. Overwrite? [y/N] [fatal] Not overwriting - exiting
[8/11/2023, 11:00:06 PM] [Camera FFmpeg] [Intersection 110-00-110] FFmpeg exited with code: 1 and signal: null (Error)
[8/11/2023, 11:00:06 PM] [Camera FFmpeg] [Intersection 110-00-110] Stopped video stream.

**To Reproduce:**

cameras": [
                {
                    "name": "Intersection 110-00-110",
                    "manufacturer": "Dahua NVR",
                    "model": "IPC-HDBW2831R-ZAS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://guest:85Elliott@192.168.1.29:554/cam/realmonitor?channel=1&subtype=0",
                        "stillImageSource": "-i http://guest:85Elliott@192.168.1.29/cgi-bin/snapshot.cgi?channel=1",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "forceMax": false,
                        "vcodec": "h264_videotoolbox",
                        "encoderOptions": "-realtime ",
                        "debug": true
                    }
                },

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v17.16.1
* **NPM Version**: 9.6.7
* **Homebridge Version**: 1.61.
* **Homebridge Camera FFmpeg Version**:

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)

* **Homebridge Config UI X Plugin Version**:
V4.50.4
* **Operating System**: 
macOS 14.0
M2 mac-mini

**Comment by Sunoo** [comment]
No files should be generated, so something has gone strangely wrong here. Please share your full log, not just a few lines.
