### ISSUE TITLE
VideoProcessor FFmpeg6 in Synology NAS

### ISSUE THREAD

**Issue by Vaifranz** [Sunoo/homebridge-camera-ffmpeg#1411]
Good morning, I use Homebridge via Docker in a Synology NAS, I have receptively installed ffmpeg6 via the SynoCommunity in order to be able to use it in addition to this Plugin to increase display performance (is this actually the case?).
I am trying to insert it in the "videoProcessor" line but to no avail.

I have tried these paths

/var/packages/ffmpeg6/target/bin/ffmpeg6
/var/packages/ffmpeg6/target/bin/ffmpeg
/volume3/@appstore/ffmpeg6/bin/ffmpeg6
/volume3/@appstore/ffmpeg6/bin/ffmpeg

without any results, I report my configuration below:

```
 "name": "Camera FFmpeg",
            "videoProcessor": "MY_QUESTION",
            "porthttp": 8880,
            "localhttp": true,
            "cameras": [
                {
                    "name": "CAM 01 Corte",
                    "manufacturer": "Dahua Technology",
                    "model": "IPC-HDW2431TP-AS-S2",
                    "serialNumber": "xxx",
                    "motion": false,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xxx:xxx@xxx:554/cam/realmonitorchannel=1&subtype=0&unicast=true&proto=Onvif",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "forceMax": false,
                        "vcodec": "libx264",
                        "audio": true

```

Where am I going wrong?

Thank you for your time.

**Comment by Sunoo** [comment]
What shows up in your logs? I’m guessing that version of ffmpeg is missing some codec or feature, but I don’t know much about Synology.
