### ISSUE TITLE
log entry "Snapshot ..." missing ?

### ISSUE THREAD

**Issue by roe1974** [Sunoo/homebridge-camera-ffmpeg#1414]
Just update to the latest Version of this PlugIn (3.1.4).
Is there no more log entry when snapshot is done like is was in previous versions ?
br, Richard

**Environment:**

* **Node.js Version**: 18.17.1
* **NPM Version**: 10.1.0
* **Homebridge Version**: 1.6.1
* **Homebridge Camera FFmpeg Version**: 3.1.4
* **Homebridge Config UI X Plugin Version**: 4.50.5
* **Operating System**: RaspiOS

**Comment by Sunoo** [comment]
I can double check, but I think it doesn't write those out unless debug is on.

**Comment by roe1974** [comment]
OKE :-) ... i jumped from 1.3.0 to 3.1.4 ... in 1.3.0 there were definitely log entries for each snapshot ... this was helpful to see if the camera was triggered ;-)
