### ISSUE TITLE
Homekit Homebrigde Streaming need longer at iOS 17

### ISSUE THREAD

**Issue by ysoftid** [Sunoo/homebridge-camera-ffmpeg#1415]
Just upgrade to iOS 17, somehow streaming the camera thru homebrigde-camera-ffmpeg (running on raspberry pi 4), taking longer than when still iOS 16. Have to wait 1-2 mins, and sometimes is failed eventually.

All happened if check via Home apps at iOS device when connected not in local network. If connect to local network, all run smoothly.

**Comment by Sunoo** [comment]
I’ve seen a few reports of this now, but I cannot recreate it, it’s been working fine for me on iOS17. Has anything else changed recently in your setup?

**Comment by ysoftid** [comment]
No change at all from the homebridge side. I already tried to restart the homebridge server, or even I reboot the raspberry pi, same result, still longer than iOS 16

**Comment by mrMiimo** [comment]
it's a iOS bug

**Comment by roe1974** [comment]
> Just upgrade to iOS 17, somehow streaming the camera thru homebrigde-camera-ffmpeg (running on raspberry pi 4), taking longer than when still iOS 16. Have to wait 1-2 mins, and sometimes is failed eventually.
> 
> All happened if check via Home apps at iOS device when connected not in local network. If connect to local network, all run smoothly.

+1 ... exactly the same here :-(
PS: I am on the new HK architecture
PSS: Control Center is a Apple TV 4K 3gen., Homebridge runs on a Pi4
PSSS: tested with h264_omx and libx264

**Comment by roe1974** [comment]
should we use/test perhaps ffmpeg-for-homebridge v2.1.0 (released last week) ?

**Comment by Sunoo** [comment]
> it's a iOS bug

Does this mean you’re seeing the same behavior with real HomeKit cameras?

**Comment by roe1974** [comment]
see here:
https://www.reddit.com/r/HomeKit/comments/16os8wr/ios_1701_update_camera_fix/
https://www.reddit.com/r/HomeKit/comments/16t60py/circle_views_will_not_stream_live_to_iphone/

quote from there: "I think the issue has to do with tvOS not iOS. My cameras were working fine till i updated my TV's and hubs"

**Comment by roe1974** [comment]
What is definitely different/new since iOS17 is this "Talk" button in the stream ... it was not there in iOS 16 ... and my camera can't do audio either ... can that be the problem ?
<img width="276" alt="Bildschirmfoto 2023-09-27 um 10 14 04" src="https://github.com/Sunoo/homebridge-camera-ffmpeg/assets/30420568/4c7d019a-1e3d-4943-8790-50c6e3842bb7">

**Comment by mrMiimo** [comment]
> Does this mean you’re seeing the same behavior with real HomeKit cameras?

The real homekit cam I have allows 2 way audio.
But I use other plugins with other cameras and integrations (scrypted) and they have the same problem.
Also there is another problem, streaming doesn't always work from **outside the network**, and the hk specs haven't changed, everything suggests it's a problem with ios and hubs

**Comment by ysoftid** [comment]
Looks like solve by upgrading to 17.0.1 or 17.0.2
Thanks guys for comments or inputs 🙏🏻

**Comment by roe1974** [comment]
not here .... 😐

**Comment by ysoftid** [comment]
> not here .... 😐

Sorry to know it, re-open this issue so can continue to discuss

**Comment by tkffaul** [comment]
I have the exact same issue. Even snapshots seem to take longer to show up in home. I'm up to 17.0.3 and 17 on everything in the house so it definitely seems to be an iOS problem.

**Comment by roe1974** [comment]
Waiting for tvOS/iOS 17.1 ;-)

**Comment by ysoftid** [comment]
[OOT] 17.0.3 seem that Location Service was broken, my all automations that have this function, won't running 😞

**Comment by Sunoo** [comment]
Maybe I’ve just been very lucky, I’ve had no issues with 17 and HomeKit.

**Comment by roe1974** [comment]
now with 17.1 everything works smooth again 😉👍

**Comment by ysoftid** [comment]
Then I will close this issue. Thanks to all who participated
