### ISSUE TITLE
[Camera FFmpeg] [Keller] FFmpeg process creation failed: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by Stonie70** [Sunoo/homebridge-camera-ffmpeg#1418]
**Describe The Problem:**
This Problem appears when i must setup the Homebridge again, and used a restore of HB

**To Reproduce:**
<Try to access a cam in Home>

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
You really didn’t provide much information, but ENOENT typically means you don’t have ffmpeg-for-homebridge installed. Reinstalling the plugin may help, or you may be on a system incompatible with it. Hard to say, you didn’t fill out the form.

**Comment by editwentyone** [comment]
that was helpful, maybe something to also post in the readme? thanks again

https://github.com/homebridge/ffmpeg-for-homebridge#install
