### ISSUE TITLE
tapo c200

### ISSUE THREAD

**Issue by biciu45** [Sunoo/homebridge-camera-ffmpeg#1421]
**Manufacturer/Model:**

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Additional Information:**

**Comment by MaDDeePee** [comment]
{
            "name": "YourName",
            "manufacturer": "Tapo",
            "model": "C200",
            "serialNumber": "3C846XXXXXXX",
            "firmwareRevision": "1.1.XX",
            "unbridge": false,
            "videoConfig": {
                "source": "-i rtsp://user:pass@192.168.178.13:554/stream1",
                "stillImageSource": "-i rtsp://user:pass@192.168.178.13:554/stream2",
                "audio": true
            }
        }

anyone got return audio working?
