### ISSUE TITLE
No stream since move from homebridge V1.6.1 Docker to Homebridge V1.7.0 Synology

### ISSUE THREAD

**Issue by Franco268** [Sunoo/homebridge-camera-ffmpeg#1423]
**Describe The Problem:**
I backuped my homebridge docker and I restored it on the Synology "app". Then I updated it to V1.7.0
Since I wasn't able to see pictures of my cameras on Home app.
I tried to go back in V1.6.1 but without succes...same result.

But that is still woking well on the docker version.

(For info, I didn't start both together)

Is it an issue only on Synology version?

**To Reproduce:**

**Logs:**
![image](https://github.com/Sunoo/homebridge-camera-ffmpeg/assets/60841044/72cb98a4-9cfe-45b4-a177-ab1f2fb64954)

**Homebridge Config:**

```json
{
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "Escalier jardin",
			"manufacturer": "Foscam",
			"model": "FI9853EP",
            "motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://XXX:Pass@XXX.XXX.XXX.XXX:Port/videoMain",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:Port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=XXX&pwd=Pass",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30
            }
        },
        {
            "name": "Couloir cave",
			"manufacturer": "Foscam",
			"model": "FI9826p",
			"motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://XXX:Pass@XXX.XXX.XXX.XXX:Port/videoMain",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:Port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=XXX&pwd=Pass",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30
            }
        },
        {
            "name": "Camera mobile",
            "manufacturer": "Foscam",
			"model": "FI9821W V21",
			"motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://XXX:Pass@XXX.XXX.XXX.XXX:Port/videoMain",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:Port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=XXX&pwd=Pass",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30
            }
        },
        {
            "name": "Entrée",
            "manufacturer": "Reolink",
			"model": "RLC-420-5MP",
			"motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-re -i rtsp://User:Pass@XXX.XXX.XXX.XXX:Port/h264Preview_01_sub",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=User&password=Pass",
                "maxStreams": 10,
                "maxWidth": 2560,
                "maxHeight": 1920,
                "maxFPS": 30
            }
        },
        {
            "name": "Garage",
            "manufacturer": "Reolink",
			"model": "RLC-420-5MP",
			"motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-re -i rtsp://User:Pass@XXX.XXX.XXX.XXX:Port/h264Preview_01_sub",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=User&password=Pass",
                "maxStreams": 10,
                "maxWidth": 2560,
                "maxHeight": 1920,
                "maxFPS": 30
            }
        },
        {
            "name": "Piscine",
			"manufacturer": "Reolink",
			"model": "RLC-520A-5MP",
            "motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-re -i rtsp://User:Pass@XXX.XXX.XXX.XXX:Port/h264Preview_01_sub",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=User&password=Pass",
                "maxStreams": 10,
                "maxWidth": 2560,
                "maxHeight": 1920,
                "maxFPS": 30
            }
        },
        {
            "name": "Arrière",
			"manufacturer": "Reolink",
			"model": "RLC-520A-5MP",
            "motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-re -i rtsp://User:Pass@XXX.XXX.XXX.XXX:Port/h264Preview_01_sub",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=User&password=Pass",
                "maxStreams": 10,
                "maxWidth": 2560,
                "maxHeight": 1920,
                "maxFPS": 30
            }
        },
        {
            "name": "Coté",
            "manufacturer": "Reolink",
			"model": "RLC-420-5MP",
			"motion": true,
            "switches": true,
            "videoConfig": {
                "source": "-re -i rtsp://User:Pass@XXX.XXX.XXX.XXX:Port/h264Preview_01_sub",
                "stillImageSource": "-i http://XXX.XXX.XXX.XXX:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=User&password=Pass",
                "maxStreams": 10,
                "maxWidth": 2560,
                "maxHeight": 1920,
                "maxFPS": 30
            }
        }
    ],
    "platform": "Camera-ffmpeg",
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX
    }
}
```

**Environment:**

* **Node.js Version**: V18.15.0
* **NPM Version**: 
* **Homebridge Version**: V1.6.1 and V1.7.0
* **Homebridge Camera FFmpeg Version**: homebridge-camera-ffmpeg v3.1.4
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.52.1
* **Operating System**: Docker & Synology V3.0.17

**Comment by Sunoo** [comment]
I don't know Synology at all, but is it possible there is some firewall or similar blocking network access? It may be easier to tell what's happening if you shared a log with debug active.

**Comment by Franco268** [comment]
From my point of view my Syno firewall is completelty onpen in the local network.

Please see debug:
[11/9/2023,` 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] Snapshot requested: 1280 x 720
[11/9/2023, 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] Snapshot command: ffmpeg -i http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/9/2023, 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] [Snapshot] http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass: Protocol not found
[11/9/2023, 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] [Snapshot] Did you mean file:http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass?
[11/9/2023, 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] Fetching snapshot took 0.011 seconds.
[11/9/2023, 7:07:17 PM] [Camera FFmpeg] [Escalier jardin] Failed to fetch snapshot.
[Escalier jardin] Snapshot request handler provided empty image buffer!

[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] Snapshot requested: 1280 x 720
[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] Snapshot command: ffmpeg -i http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] [Snapshot] http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass: Protocol not found
[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] [Snapshot] Did you mean file:http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass?
[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] Fetching snapshot took 0.01 seconds.
[11/9/2023, 7:07:38 PM] [Camera FFmpeg] [Escalier jardin] Failed to fetch snapshot.
[Escalier jardin] Snapshot request handler provided empty image buffer!

**Comment by Sunoo** [comment]
That’s a very weird error, best guess is something is wrong with whatever version of ffmpeg you have?

**Comment by Franco268** [comment]
3.1.4

**Comment by StephanH27** [comment]
I think I have the [same problem](https://github.com/Sunoo/homebridge-camera-ffmpeg/discussions/1424) ...

**Comment by Franco268** [comment]
Answer is here: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Synology-DSM
Chapter: Recommended Post-Install Steps
