### ISSUE TITLE
tvOS 17.2 Cameras Crashing

### ISSUE THREAD

**Issue by tkffaul** [Sunoo/homebridge-camera-ffmpeg#1431]
I've been on this software a LONG time... and I didnt change anything prior to the attached mess. Keep in mind all of this still works perfectly fine on my iphone. So I'm afraid this is an apple issue. If i restart Homebridge everything works fine, all the camera feeds come up and everything works as it should (TV, phone, ipad, etc). If i wait about 5 minutes... nothing show on the TV. And I mean nothing, just blank squares. The logs show nothing! The TV seems to just not request the stream or photo again. Previews don't come up... nothing. I go to my iphone and i can see the streams and everything works, the log starts backup everything. So i figure this has been working for so long... probably needs an upgrade all around. So i moved to Ubuntu 22.04 and reinstalled all the packages. Same behavior... i ended up even resetting my homebridge and starting over. Same behavior... i have cut down the config on the cameras... tried to make them as vanilla as possible... same behavior. This all started around the 17 issues... the updates fixed my phone but my TV has been messed up ever since. I'm on node 20.10, newest version of Homebridge , and  3.1.4 of this software. It just doesn't seem to matter if i roll the software up and down it just acts the same. I dont really have any way to show or reproduce this because i cant find a way to get it to behave differently. I'm normally a brute force go at it until something works so I'm out of ideas. I'm hoping someone else might have something.

**Comment by tkffaul** [comment]
No one else is having issues with this? I just rebuilt my whole camera config again from scratch started with one camera... same issues it works for the first 5 minutes then it just stops working all together. Nothing but a blank box. I'm about to rebuild the whole system again... i just cant find an issue and if no one else has this issue then its something in my network...

**Comment by zobe123** [comment]
Same here

**Comment by zobe123** [comment]
i've added one of my cams with @seydx cameraUI Plugin and now all cams work like a Charm, i hope this helps a little.
