### ISSUE TITLE
FFmpeg exited with code: 1 and signal: null (Error)

### ISSUE THREAD

**Issue by nfstange** [Sunoo/homebridge-camera-ffmpeg#1434]
**Describe The Problem:**
<My HOOBS image recently crashed and had to reflash. After completing that and reinstalling the camera ffmpeg plugin, its failing to load my cameras>

**To Reproduce:**
<I have typed in the rtsp stream multiple times and unbridged the cameras>

**Logs:**
<1/3/2024, 6:38:53 PMCamera FFmpeg BridgeERROR[Garage Camera 892D] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
1/3/2024, 6:38:55 PMCamera FFmpeg BridgeCamera FFmpeg[Garage Camera] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld)
1/3/2024, 6:39:00 PMCamera FFmpeg BridgeCamera FFmpegERROR[Garage Camera] FFmpeg exited with code: 1 and signal: null (Error)
1/3/2024, 6:39:00 PMCamera FFmpeg BridgeCamera FFmpeg[Garage Camera] Stopped video stream.>

**Homebridge Config:**

{
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Outdoor 1",
                    "manufacturer": "Lorex",
                    "doorbell": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://username:password@ipaddress:554/cam/realmonitor?channel=2&subtype=1"
                    },
                    "switches": true,
                    "motion": true
                },
                {
                    "name": "Garage Camera",
                    "videoConfig": {
                        "source": "-i rtsp://username:password@ipaddress:554/cam/realmonitor?channel=3&subtype=1",
                        "audio": true
                    },
                    "switches": true,
                    "motion": true,
                    "unbridge": true,
                    "doorbell": false
                }
            ]
        }
    ]
}

**Screenshots:**
<img width="1576" alt="Screenshot 2024-01-03 at 6 42 01 PM" src="https://github.com/Sunoo/homebridge-camera-ffmpeg/assets/52550843/842dd9ae-ff91-446b-a2b1-56d72e564c93">

**Environment:**

* **Node.js Version**: <16.20.2>
* **Homebridge Version**: <1.6.0>
* **Homebridge Camera FFmpeg Version**:<3.1.4>
* **Hoobs Version: <4.3.0>
* **Operating System**:

**Comment by costispavlou** [comment]
same issue here. had to reflash / reinstalled my json and facing the same error.
