### ISSUE TITLE
Camera not workign in hoobs any more

### ISSUE THREAD

**Issue by iconatorC** [Sunoo/homebridge-camera-ffmpeg#1441]
All of a sudden camera stopped working 

Just try watching camera from Home app and its unavailable 

2/25/2024, 2:47:20 AMCamera FFmpeg BridgeAmcrest[OfficeCam] Starting video stream: 1280 x 720, 15 fps, 299 kbps (AAC-eld)
2/25/2024, 2:47:23 AMCamera FFmpeg BridgeAmcrestERROR[OfficeCam] FFmpeg exited with code: 1 and signal: null (Error)
2/25/2024, 2:47:23 AMCamera FFmpeg BridgeAmcrest[OfficeCam] Stopped video stream.

**Homebridge Config:**

{
    "platform": "Camera-ffmpeg",
    "name": "Amcrest",
    "cameras": [
        {
            "name": "OfficeCam",
            "manufacturer": "Amcrest",
            "model": "IP4M",
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://user:pass@10.0.1.108:554/cam/realmonitor?channel=1&subtype=0",
                "stillImageSource": "-i http://user:pass@10.0.1.108/cgi-bin/snapshot.cgi?chn=1",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 15,
                "maxBitrate": 2048,
                "vcodec": "libx264 -preset ultrafast",
                "packetSize": 1316,
                "audio": true,
                "debug": false
            },
            "motion": true,
            "unbridge": false,
            "motionTimeout": 0
        }
    ]
}

**Screenshots:**

**Environment:**
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.6">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px Helvetica; color: #878787; -webkit-text-stroke: #000000}
span.s1 {font-kerning: none}
td.td1 {width: 134.2px; min-height: 26.0px; margin: 0.5px 0.5px 0.5px 0.5px; padding: 10.0px 10.0px 10.0px 10.0px}
td.td2 {width: 339.8px; min-height: 26.0px; margin: 0.5px 0.5px 0.5px 0.5px; padding: 10.0px 10.0px 10.0px 10.0px}
</style>
</head>
<body>

Version | 4.3.1 Check for Updates
-- | --
Node Version | 16.20.2
Homebridge Version | 1.7.0
CPU | 35%
Memory | 151.7 MB (57.3 MB)
Manufacturer | HOOBS.org
Model | HSLF-1
System Version | 11
SKU | 7-45114-12418-0
Hostname | hoobs

</body>
</html>

**Comment by costispavlou** [comment]
same here.
