### ISSUE TITLE
Calling another server on event 

### ISSUE THREAD

**Issue by maxboz** [Sunoo/homebridge-camera-ffmpeg#1443]
Hi. I really enjoy using this plugin! What I would love to see is if there was an option to make a request (GET or POST) to another server when Doorbell or Motion is triggered. The doorbell functionality is crucial to me personally, so if it's not something that you care about enough to make this a feature, I'd be very happy if someone experienced with this project helped me get around this limitation. 

Thank you!

**Comment by Sunoo** [comment]
Since doorbell is MQTT-based, is there a reason your other system couldn’t watch for the same MQTT event? Or am I misunderstanding the ask?

**Comment by maxboz** [comment]
> Since doorbell is MQTT-based, is there a reason your other system couldn’t watch for the same MQTT event? Or am I misunderstanding the ask?

Well, the only way I could configure my doorbell is for it to make a GET request to "/doorbell?Doorbell". I might be in the wrong here, but isn't MQTT just for triggering the doorbell event in Homebridge? So if the plugin is triggered by a GET request, MQTT isn't used at all? 

I tried using Dummy Switches and making an automation based around them, but found them unreliable. They work perfectly well when used to trigger the doorbell, but don't reflect the current state consistently if the doorbell is triggered some other way. 

I hope it makes sense, maybe I just don't understand how the plugin works :) Sorry
