### ISSUE TITLE
Homebridge 2.0 ready?

### ISSUE THREAD

**Issue by jdegouw** [Sunoo/homebridge-camera-ffmpeg#1455]
Hi

I got the famouse message:
**Homebridge Camera FFmpeg might not be ready for Homebridge v2.0**

Not sure if development is still active or this plugin and not sure if this will work.
Is there any feedback about this?

**Comment by Sunoo** [comment]
I wonder what needs to be done to make it Homebridge 2.0 ready… I’ll try to look into it.

**Comment by jdegouw** [comment]
I did a small check and I think it will work (not 100% sure as I'm only a hobby programmer) 
Breaking changes:
Batterservice not used
Characteristic.getValue not used
Accessory.getServiceByUUIDAndSubType already using Accessory.getServiceById
Accessory.updateReachability not used
storagePath not used
AudioCodec not used already using AudioStreamingCodec
VideoCodec not used, H264CodecParameters is new format
StreamAudioParams not used, AudioStreamingOptions is new format
StreamVideoParams not used, VideoStreamingOptions is new format
cameraSource not used, 
useLegacyAdvertiser not used
AccessoryLoader not used
Characteristic.ProgramMode -> PROGRAM_SCHEDULED_MANUAL_MODE_ corrected into PROGRAM_SCHEDULED_MANUAL_MODE not used

**Comment by nak0604** [comment]
Yeah, if you think it's ready you can do this to avoid this question coming up. 
![Screenshot 2024-09-28 154901](https://github.com/user-attachments/assets/d4e8f0b7-3cb0-436c-b8e4-440bfe8f8560)
