### ISSUE TITLE
iOS 13.2 picture notifications (fail after a couple notifications)

### ISSUE THREAD

**Issue by PaRkThEcAr** [Sunoo/homebridge-camera-ffmpeg#363]
hello! i got still photo snapshot notifications to work with iOS 13. however, if the sensor is triggered a couple times, eventually it stops sending images along with the notifications on all my devices.

any idea why? what do you need from me to get this to work? homebridge doesnt give me any errors to go off of here.

**Comment by iuliusmaximilian** [comment]
Having the same but could not figure out under which conditions no snapshots are send.

**Comment by NorthernMan54** [comment]
I’m out of the country and won’t be able to look at this until next week.

If you manually trigger the motion sensor by turning the switch on does it work?

**Comment by PaRkThEcAr** [comment]
Not after a couple triggers. I noticed rebooting Homebridge seems to solve this issue temporarily. But manually triggering the sensor seems to not work after a couple triggers either manually, or automatically

**Comment by BAngel87** [comment]
Same here and in addition with the Update to  1.13 google drive upload seams also broken

**Comment by NorthernMan54** [comment]
@BAngel87 Pull request #371 will fix the upload issue

for picture notifications, I'm still investigating as I have not been able to recreate it yet

**Comment by apollo316** [comment]
I think I figured out the problem. If I trigger the motion switch manually or with an automation no picture comes through. If I connect to the live feed of the camera first and then trigger the motion switch I get a picture. It seems to be a problem with querying the camera/connecting to it before taking the picture. In short, I think it’s trying to grab a picture too fast, not connecting to the camera in time, then sending a notification minus the picture. 

I’ve got a video of my tests showing this if that would help you. Also, this plugin is AMAZING!! I love that I can use any old camera. I don’t want a HomeKit ready one because they all upload my videos to the cloud (someone else’s computer). I have complete control this way. Love it!! Thank you!!

**Comment by llemtt** [comment]
@apollo316 yes you are right, snapshot generation and send time is the key.

I think, because I have no insights of the internals and I don't have inspected "over the wire", that is the client that once received the notification is going to request the snapshot (the snapshot doesn't get sent "inside" the notification) and if it doesn't receive it fast enough it displays the notification without.

**Comment by apollo316** [comment]
> if it doesn't receive it fast enough it displays the notification without.

Makes perfect sense! Sounds like there isn't much that can be done from our end yet. Thanks for the update and thank you again for this tool!!

**Comment by NorthernMan54** [comment]
Based on these comments, I’m thinking what is happening is that occasionally the snapshot request is taking too long, and HomeKit is issuing the notification without it.  Aka a timeout is occurring in HomeKit

Does this make sense based on what you are seeing?

**Comment by apollo316** [comment]
> Based on these comments, I’m thinking what is happening is that occasionally the snapshot request is taking too long, and HomeKit is issuing the notification without it. Aka a timeout is occurring in HomeKit Does this make sense based on what you are seeing?
> […](#)
> On Nov 6, 2019, at 9:42 AM, apollo316 ***@***.***> wrote: ﻿ if it doesn't receive it fast enough it displays the notification without. Makes perfect sense! Sounds like there isn't much that can be done from our end yet. Thanks for the update and thank you again for this tool!! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes I'd say that makes sense. And sorry, I thought I was replying to you with my last reply. It's as though Homekit sleeps the camera if I haven't connected to it in the last few minutes and then when motion is triggered the notification comes in almost instantaneously with no picture. A few seconds later I get a second notification also with no picture. If I connect to the camera live feed, and then trigger the notification I get the picture after 5-10 seconds.

**Comment by NorthernMan54** [comment]
@apollo316 That behaviour is not HomeKit, but how you're machine where you're running homebridge and the plugin works with your camera's.  Could be any number of things from DNS, to MDNS, to authentication or ???

**Comment by NorthernMan54** [comment]
I added this as a known issue on the Wiki page for the motion feature

**Comment by llemtt** [comment]
Overall may I suggest a different process?

When an event such as a motion sensor or a doorbell button push occurs, a snapshot from the camera should be immediately taken and saved to a file. Then when the snapshot request reach the camera plugin, the most recently saved snapshot should be sent back (immediately).

On occasion, while on remote access, I had someone push my doorbell being in front of it and the notification snapshot of him moved or turned such that I couldn't recognize him...

(I'm slowly implementing this in my video doorbell...)

**Comment by NorthernMan54** [comment]
@llemtt with my setup I’m doing this today

I did the following

1 - Create a daemon to cache video from the camera to a local RAM disk. For this I’m using the ffmpeg option segment

2 - changed the snapshot request to grap its frame from the cache going back a few seconds before the request

3 - as a bonus I’m also creating 60 seconds of video, starting 20 seconds before the sensor is triggered, and uploading it to my google photos account.

The work in progress is here, and is just shell scripts and a change to the plugin to use google photos, rather than drive and make the still shot processor command an option ( so I could point it to a shell script instead of ffmpeg )

https://github.com/NorthernMan54/homebridge-camera-ffmpeg/tree/Google-Photos/scripts

**Comment by llemtt** [comment]
@NorthernMan54 great! very clever! my latest D-Link camera does something very similar

I can save snapshots/videos in iCloudDrive, like you do with Google Photos,  to completely overcome the problem of missing snapshot notifications!!

thx

**Comment by NorthernMan54** [comment]
@PaRkThEcAr can you close this as it is resolved

**Comment by bluntiless** [comment]
Hi @llemtt, I was wondering if you could share how you implemented snapshots/videos in iCloudDrive. Since I updated home bridge-camera-ffmpeg to the latest version, Google Drive Upload is not supported anymore apparently. Any help you can offer would  be greatly appreciated.

**Comment by NorthernMan54** [comment]
@bluntiless At some point in the near future going to release a version with integration to google photo's instead of google drive.  Until this is ready you could continue to use the last 1.x.x version. with includes drive.

**Comment by Sunoo** [comment]
@NorthernMan54 It would be nice if there was a way to keep it somewhat generic, so people could potentially have a way to use different cloud providers, without this plugin needing to directly support everything possible.

I can’t think of a way that would actually work though, and I suppose this plugin had Google integration in the past anyways.

**Comment by bluntiless** [comment]
Hi  @NorthernMan54 , thanks for the advice. I have reinstalled version 1.2.1. Unfortunately I have another problem of :
"The limit for this folder's number of children (files and folders) has been exceeded."
Do you know how I can resolve this issue? I updated the plugin in the hope that it would eliminate this problem. It seems that Google have introduced a limit of 500,000 files per folder.

**Comment by NorthernMan54** [comment]
Besides deleting files, nope

Switch to a different folder on regular intervals?

**Comment by bluntiless** [comment]
Hi @NorthernMan54, I had started to manually delete files from my Camera Pictures folder, but this is proving to be very time consuming. So I am looking at your scripts https://github.com/NorthernMan54/homebridge-camera-ffmpeg/tree/Google-Photos. 
This is something I would like to try out if possible. Can you advise on how I could implement this?

**Comment by NorthernMan54** [comment]
If you install this version, it uses Google Photo's rather than drive

npm install -g NorthernMan54/homebridge-camera-ffmpeg#Google-Photos

My camera config for my Wyze Cam


```
{
      "platform": "Camera-ffmpeg",
"cameras": [{
        "name": "Bunkie",
        "motion": true,
        "uploader": true,
        "username": "... Google Photo's login...",
        "password": "... Google Photo's Password...",
        "album": "Cottage Porch",
        "videoConfig": {
          "source": "-re -i rtsp://FrontPorch:FrontPorch@192.168.1.22/live",
          "stillImageSource": "I did something custom here using node red, just use the usual",
          "maxStreams": 2,
          "maxWidth": 1920,
          "maxHeight": 1080,
          "maxFPS": 15,
          "vcodec": "h264_omx",
	  "audio": true,
	  "debug": false
        }
      }
```

**Comment by bluntiless** [comment]
Thanks for the information @NorthernMan54. I am going to try and install it now. I have created a new GDrive account as you suggested as well.

**Comment by bluntiless** [comment]
Hi again @NorthernMan54. I am getting Error: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r686378. 
Does this mean that Chromium is the problem?

**Comment by NorthernMan54** [comment]
Yes

**Comment by NorthernMan54** [comment]
It uses a browser for authentication.  For issues with the uploader, I'm using this package

https://github.com/3846masa/upload-gphotos

**Comment by bluntiless** [comment]
Hi again and thanks for the advice. I'm installing https://github.com/3846masa/upload-gphotos now.

**Comment by bluntiless** [comment]
Thanks again for all your helpful advice @NorthernMan54! It is uploading to Google Photos now!
Is it possible to upload video also?

**Comment by NorthernMan54** [comment]
For uploading a video when snapshot is triggered I went a little bit complex, and used a ram drive on my RPI to cache 2 minutes of video, then used node-red to grab the video and upload it to Google Photo's.  At some point I need to clean it up and make it more accessible for more people.  You can see pieces of it in the scripts directory of my branch.

**Comment by llemtt** [comment]
> Hi @llemtt, I was wondering if you could share how you implemented snapshots/videos in iCloudDrive. Since I updated home bridge-camera-ffmpeg to the latest version, Google Drive Upload is not supported anymore apparently. Any help you can offer would be greatly appreciated.

D-Link cameras can upload to ftp so I'm uploading to iCloudDrive on my mac using ftp

**Comment by bluntiless** [comment]
Thanks @llemtt for the information. I have already managed to install @NorthernMan54 Google photos implementation of homebridge-camera-ffmpeg. Just trying to figure out how to upload video clips. Do you upload video to iCloud Drive as well or is it just snapshots?
