### ISSUE TITLE
timeline stream is not discontinuous

### ISSUE THREAD

**Issue by felho001** [Sunoo/homebridge-camera-ffmpeg#648]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

[homebridge.zip](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4912944/homebridge.zip)

**Homebridge Config:**

```
 "platform": "Camera-ffmpeg",
            "videoProcessor": "ffmpeg",
            "cameras": [
                {
                    "name": "Nappali",
                    "manufacturer": "Dlink",
                    "model": "DCS 960L",
                    "firmwareRevision": "1.04.02",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:xxxxxxxx@192.168.1.xx:554/play1.sdp",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264",
                        "packetSize": 1316,
                        "audio": true,
                        "debug": true
                    }
                },
                {
                    "name": "konyha",
                    "manufacturer": "Dahua",
                    "model": "C36",
                    "videoConfig": {
                        "source": "-re -i rtsp://syno:cxxxxxxxxxxxxxxx@192.168.1.xx:554/Sms=3.unicast",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264",
                        "packetSize": 1316,
                        "audio": true,
                        "debug": true
                    }
```
**Screenshots:**

<img width="342" alt="Képernyőfotó 2020-07-13 - 15 47 43" src="https://user-images.githubusercontent.com/45117257/87311965-3e1dff00-c520-11ea-9da1-fed4783600ab.png">

here is the screenrecords from 2 cameras was streams always stop and big jump seconds:  https://share.icloud.com/photos/02C-ehDhck-JreIxAYwX2MJ7Q

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**: 2.2.1
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.23.2 - © 2020 oznu
* **Operating System**: Synology NAS Docker

**Comment by Sunoo** [comment]
I took a look through your logs, and all I really saw a significant number of corrupt frames. You could try adding `-fflags +discardcorrupt` to the start of your 'source' config options, and see if that improves anything.

**Comment by Sunoo** [comment]
I also just noticed you have `-re` in your 'source' option, this can cause packet loss and typically should not be used, so I’d recommend removing that and trying again.

**Comment by felho001** [comment]
> I took a look through your logs, and all I really saw was a significant number of corrupt frames. You could try adding `-fflags +discardcorrupt` to the start of your 'source' config options, and see if that improves anything.

How? It is good?: "-fflags -i rtsp://admin:xxxxxxxx@192.168.1.xx:554/play1.sdp"

and if I delete -re is itt a good source? "-i rtsp://admin:xxxxxxxx@192.168.1.xx:554/play1.sdp"

**Comment by Sunoo** [comment]
I would try `-i rtsp://admin:xxxxxxxx@192.168.1.xx:554/play1.sdp` first, and if that has problems, try `-fflags +discardcorrupt -i rtsp://admin:xxxxxxxx@192.168.1.xx:554/play1.sdp`.

**Comment by felho001** [comment]
YEEEH I delete -re and nos work correct stream. Only one thing the motion true but I dont give push notificaton. could you fix it?

**Comment by roe1974** [comment]
what is the function of the parameter "-re" ?
Richard

**Comment by SupImDos** [comment]
@roe1974 

From: https://trac.ffmpeg.org/wiki/StreamingGuide

> The FFmpeg's "-re" flag means to "Read input at native frame rate. Mainly used to simulate a grab device." i.e. if you wanted to stream a video file, then you would want to use this, otherwise it might stream it too fast (it attempts to stream at line speed by default). My guess is you typically don't want to use this flag when streaming from a live device, ever.

**Comment by Sunoo** [comment]
@roe1974 I don’t know where the advice to use it for this plugin started, but I plan to go through all the documentation and remove it. It should not ever be used when the source is live video.

**Comment by Sunoo** [comment]
@felho001 This plugin doesn't do anything to detect motion on it's own, you need to either [use automation within the Home app while using switches](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications) or [MQTT messages](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/MQTT-Motion) to trigger the motion alerts. HTTP support for triggering the alerts will also be available in version 2.3.0

**Comment by felho001** [comment]
> @felho001 This plugin doesn't do anything to detect motion on it's own, you need to either [use automation within the Home app while using switches](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications) or [MQTT messages](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/MQTT-Motion) to trigger the motion alerts. HTTP support for triggering the alerts will also be available in version 2.3.0

thanks.

This config nos crashing same time before delete "-re"
{
                    "name": "konyha",
                    "manufacturer": "Dahua",
                    "model": "C36",
                    "videoConfig": {
                        "source": -i rtsp://syno:cxxxxxxxxxxxxxxx@192.168.1.xx:554/Sms=3.unicast",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264",
                        "packetSize": 1316,
                        "audio": true,
                        "debug": true
I try this: "source": -i rtsp://syno:cxxxxxxxxxxxxxxx@192.168.1.xx:554/Sms=3.unicast", and this -fflags +discardcorrupt -i rtsp://syno:cxxxxxxxxxxxxxxx@192.168.1.xx:554/Sms=3.unicast",

Morning work perfect but now not work. It's a synology nas RTSP because the dahua c46 cam not havi http Settings page only app.

**Comment by Sunoo** [comment]
Darn, thought we had this solved. Can you please provide new logs?

Also, I don't see why running it through Synology should be a problem, could you try connecting to the camera directly and see if that gives any better results? I see an entry for the [C35P in iSpyConnect](https://www.ispyconnect.com/man.aspx?n=dahua&page=2), which is likely the configuration you need. If you click the model name and fill in your information, you'll be able to generate a URL that should work for your camera.

**Comment by felho001** [comment]
[homebridge.csv.zip](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4919333/homebridge.csv.zip)

**Comment by felho001** [comment]
Dahua C46!
Attention! The Dahua Consumer cameras are dedicated to management only via the imou application (previous name Lechange). These devices do not have the WEB interface. The Consumer series records the data only after motion detection (no continuous recording) - recording approx. 1 - 1.5 minutes depending on the duration of the movement in front of the camera. 
https://shopdelta.eu/ip-camera-ipc-c46-wi-fi-4-0-mpx-2-3-mm-dahua_l2_p14800.html

**Comment by felho001** [comment]
because not have web interface, and this cam work synology survallence station and there have RSTP link and I use that one.

**Comment by Sunoo** [comment]
I'm not sure I understand. Synology is almost certainly connecting to the camera via RTSP itself, and most likely at the URL provided in the iSpyConnect database.

**Comment by felho001** [comment]
synology always connect IP adresses 
<img width="731" alt="Képernyőfotó 2020-07-14 - 16 40 04" src="https://user-images.githubusercontent.com/45117257/87439392-0763e980-c5f1-11ea-8cc2-a2b1ff428ca5.png">
and after can I make RSTP link: 
![Képernyőfotó 2020-07-14 - 16 40 38](https://user-images.githubusercontent.com/45117257/87439446-18acf600-c5f1-11ea-828c-5421594d1bf0.png)

**Comment by Sunoo** [comment]
I took a quick look at your log and I'm still seeing a decent number of corrupt frames. Could you please try connecting directly to the camera to see if that works any better? I mentioned how in this comment: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/issues/648#issuecomment-658206823

**Comment by felho001** [comment]
Hi now work all cams. I will try when I live home and wake up my childrens and use internet:-)

**Comment by felho001** [comment]
Hi when I out my home all cams no connection.

**Comment by Sunoo** [comment]
So it’s working correctly while in the house then now?

Do you have a HomeKit hub on your network (Apple TV, iPad, etc)?

**Comment by felho001** [comment]
yes I settings apple TV 4K home hub. end now try out home wifi nappali cam work fine look: https://share.icloud.com/photos/08hFpNwzvov4fc0gwjl4n4ymw
bit konyha cam not work in or out same: https://share.icloud.com/photos/04rvF3oDcS2hfzIVGTKDqWHkw
here is a log:
[homebridge.csv.zip](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4925936/homebridge.csv.zip)

**Comment by Sunoo** [comment]
This is clearly from an older version of the plugin, please upgrade.
