### ISSUE TITLE
iOS 14 beta no doorbell notification

### ISSUE THREAD

**Issue by mishakim** [Sunoo/homebridge-camera-ffmpeg#660]
my iPhone X running iOS 14 beta 2 (public beta) does not receive notifications when the doorbell is rung. All devices running iOS 13 and MacOS 10.15.5 still receive the notification. Don't know if the issue is with homebridge or iOS. Have also submitted bug report to Apple.

**To Reproduce:**
send HTTP or MQTT doorbell message to camera configured with doorbell:true.

**Expected behavior:**
receive notification

**Logs:**

```
[7/15/2020, 12:00:38 PM] [Camera-ffmpeg] Snapshot from Vestibule at 480:270
[7/15/2020, 12:00:50 PM] [Camera-ffmpeg] Switch Doorbell On: Vestibule
[7/15/2020, 12:00:50 PM] [Camera-ffmpeg] Snapshot from Vestibule at 480:270
[7/15/2020, 12:00:50 PM] [Camera-ffmpeg] Snapshot from Vestibule at 1280:720
```

**Homebridge Config:**

```json
 {
            "mqtt": "127.0.0.1",
            "portmqtt": 1883,
            "usermqtt": "xxxx",
            "passmqtt": "xxxx",
            "topic": "homebridge",
            "porthttp": 1886,
            "cameras": [
                {
                    "name": "Vestibule",
                    "manufacturer": "Wyze",
                    "model": "Cam v2",
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://misha:xxxxx@10.0.1.218/live",
                        "stillImageSource": "-i rtsp://misha:xxxxx@10.0.1.218/live -vframes 1 -r 1",
                        "vcodec": "libx264",
                        "videoFilter": "transpose=1",
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**:2.3.1-beta.4
* **Homebridge Config UI X Plugin Version**:4.23.2
* **Operating System**: Raspbian Stretch (9)

**Comment by Sunoo** [comment]
Looks like the plugin at least thinks it’s sending the doorbell notification. If it’s working on iOS 13, I’m guessing it’s an Apple issue. For what it’s worth, I’ve seen issues with missing doorbell notifications from the Ring plugin on the beta as well. Weirdly, the tvOS beta does seem to show the doorbell alerts though.

**Comment by mishakim** [comment]
That's what I figured. Apple's doorbell support has always been a bit iffy, possibly due to a lack of certified products in the category.

**Comment by iRayanKhan** [comment]
There are three HomeKit doorbells on the market, none of which are appealing, but they do exist. I haven't been able to get any of my Homebridge camera streams, nor my HKSV camera to show on the AppleTV, so I'm assuming it's just a beta issue, or frankly just not implemented yet.

**Comment by hugozheng2017** [comment]
> Looks like the plugin at least thinks it’s sending the doorbell notification. If it’s working on iOS 13, I’m guessing it’s an Apple issue. For what it’s worth, I’ve seen issues with missing doorbell notifications from the Ring plugin on the beta as well. Weirdly, the tvOS beta does seem to show the doorbell alerts though.

that is Apple's problem.in iOS14 beta 3 and tvOS beta 3 the function come back.But I found that the button of the doorbell trigger disappear since iOS 14.may you fix it?

**Comment by Sunoo** [comment]
@hugozheng2017 I’m not sure I understand your question, but I believe you need to set ‘switches’ to true in the camera config.

**Comment by hugozheng2017** [comment]
> @hugozheng2017 I’m not sure I understand your question, but I believe you need to set ‘switches’ to true in the camera config.
thank you so much.it return to normal.I thought that as long as the doorbell function was added, then the trigger would be added automatically.thank you again.

**Comment by hugozheng2017** [comment]
> @hugozheng2017 I’m not sure I understand your question, but I believe you need to set ‘switches’ to true in the camera config.
thank you so much.it return to normal.I thought that as long as the doorbell function was added, then the trigger would be added automatically.thank you again.

**Comment by hugozheng2017** [comment]
> @hugozheng2017 I’m not sure I understand your question, but I believe you need to set ‘switches’ to true in the camera config.

thank you so much.it return to normal.I thought that as long as the doorbell function was added, then the trigger would be added automatically.thank you again.

**Comment by Sunoo** [comment]
@hugozheng2017 That’s how it used to work, but was changed when support for other ways of triggering the doorbell and motion sensor were added.

**Comment by Sunoo** [comment]
@mishakim I’ve heard beta 3 fixes the issues with doorbells, but I haven’t had a chance to test it out myself yet.

**Comment by mishakim** [comment]
Confirmed, beta 3 fixes the issue, notification is back

**Comment by Sunoo** [comment]
Great, we'll close this out then.
