### ISSUE TITLE
Future Request (Motion by ftp)

### ISSUE THREAD

**Issue by monza258** [Sunoo/homebridge-camera-ffmpeg#662]
**Describe the solution you'd like:**
My cam doesn’t have MQTT motion but an option for ftp.

**Describe alternatives you've considered:**
The homebridge-camera-Ui plugin from seydx support that option. 

**Additional context:**
is the any way to include this option to your Plugin?

**Comment by Sunoo** [comment]
I think this would be best solved in a translation plugin that accepts the FTP connection and republished it as either MQTT or HTTP to this plugin, [similar to what I did for Dafang Hacks cameras](https://github.com/Sunoo/homebridge-dafang-mqtt-republish).

If I have some free time later, I may look into writing such a plugin myself.

**Comment by monza258** [comment]
Unfortunately, I don't understand anything about it, or how to implement it. 😅

**Comment by Sunoo** [comment]
Like I said, I might take a stab at it myself if I have some free time. Unfortunately my laptop is going in for repairs this afternoon, and I’m not sure how long that’ll take.

**Comment by monza258** [comment]
I'm glad you take your time for it.  (Sometime)

**Comment by Sunoo** [comment]
I plan on supporting a few methods, but to make sure I prioritize the most useful one, do you save your pictures to the computer that is running Homebridge, or somewhere else? (or, I guess, do you not care about the pictures themselves and just use them to trigger alerts?)

**Comment by monza258** [comment]
I use it for both options. 

The picture will saved on my fritzbox. See attached Screenshot. The Camera-ui Plugin send me also the picture by telegram to see all the motions why have triggered. 

Think the plugin will work so: 
If there is a new pic on ftp then send it by telegram and trigger the camera motion. 

Pic by Telegram. My favorite option.

**Comment by Sunoo** [comment]
I've just [published a very early version of this](https://www.npmjs.com/package/homebridge-ftp-motion), that currently only triggers motion alerts based on FTP uploads. It does not yet store the images or do anything else.

I'm going to close this issue out now. If you want to comment on anything about that plugin, please do it on [that project's issue tracker](https://github.com/Sunoo/homebridge-ftp-motion/issues).
