### ISSUE TITLE
Motion Dummy Switches missing

### ISSUE THREAD

**Issue by MikeDProducer** [Sunoo/homebridge-camera-ffmpeg#670]
**Describe The Bug:**
2.3.1 no longer shows the dummy motion switches in Homekit.

**To Reproduce:**
Any time homebridge loads, the motion switches do not show any more. It worked in the previous version I had installed which was 1.3. The "motion": true, is present for all cameras, but it doesn't show up.

**Expected behavior:**
In the past you would have a dummy switch for motion for each camera that has the  "motion": true, command.

**Logs:**
[7/17/2020, 7:58:15 AM] [Camera ffmpeg] Configuring accessory Deck
[7/17/2020, 7:58:15 AM] [Camera ffmpeg] Configuring accessory Driveway
[7/17/2020, 7:58:19 AM] [Camera ffmpeg] Configuring accessory South
[7/17/2020, 7:58:19 AM] [Camera ffmpeg] Configuring accessory Backyard
[7/17/2020, 7:58:20 AM] [Camera ffmpeg] Configuring accessory Garage

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

https://pastebin.com/j9rZbana

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.3.1
* **Homebridge Config UI X Plugin Version**: 4.23.2
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
Since other methods of automating motion alerts were put in place, there was another configuration option added so switches were only shown when ‘switches’ is also set to true.

**Comment by MikeDProducer** [comment]
That makes sense! Perhaps it would be helpful to add this to the documentation. 

If you ever need any help with documentation, I am willing to help! I can send you some tutorials I've written as examples of my ability.

**Comment by Sunoo** [comment]
Documentation is not my strong suit, and I only just took over this project, so I need to go through all the old docs and try to get things updated. After you opened this, I did go to the wiki and add a note about switches.

Happy to talk to you more about what help you could provide with documentation though.
