### ISSUE TITLE
Poor bitrate and video quality with latest beta and CPU pegging

### ISSUE THREAD

**Issue by burnbrigther** [Sunoo/homebridge-camera-ffmpeg#671]
**Describe The Bug:**

The bitrate has dropped dramatically with the latest beta release.  I also see cpu pegging on raspi.

Earlier this morning:
homebridge.log:[7/17/2020, 7:27:35 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame=21304 fps= 33 q=-0.0 size=  111902kB time=00:17:45.05 bitrate= 860.7kbits/s dup=2130 drop=0 speed=1.67x    
homebridge.log:[7/17/2020, 7:27:36 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame=21323 fps= 33 q=-0.0 size=  112016kB time=00:17:46.00 bitrate= 860.8kbits/s dup=2132 drop=0 speed=1.67x    
homebridge.log:[7/17/2020, 7:27:36 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame=21340 fps= 33 q=-0.0 size=  112230kB time=00:17:46.85 bitrate= 861.8kbits/s dup=2134 drop=0 speed=1.67x

Now:
[7/17/2020, 9:39:34 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame= 4979 fps= 33 q=-0.0 size=    4078kB time=00:04:08.80 bitrate= 134.3kbits/s dup=498 drop=0 speed=1.67x    
[7/17/2020, 9:39:34 AM] [Camera-ffmpeg] RIGHT Front Cam: frame= 4997 fps= 33 q=-0.0 size=    4096kB time=00:04:09.70 bitrate= 134.4kbits/s dup=500 drop=0 speed=1.67x    
[7/17/2020, 9:39:35 AM] [Camera-ffmpeg] RIGHT Front Cam: frame= 5014 fps= 33 q=-0.0 size=    4108kB time=00:04:10.55 bitrate= 134.3kbits/s dup=501 drop=0 speed=1.67x    
[7/17/2020, 9:39:35 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame= 5032 fps= 33 q=-0.0 size=    4124kB time=00:04:11.45 bitrate= 134.4kbits/s dup=503 drop=0 speed=1.67x    
[7/17/2020, 9:39:36 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame= 5050 fps= 33 q=-0.0 size=    4135kB time=00:04:12.35 bitrate= 134.2kbits/s dup=505 drop=0 speed=1.67x 

**To Reproduce:**

Run the latest release.
Tail the log, view the bitrate.
**Expected behavior:**

I should be seeing bitrates in the mid-800's.
**Logs:**

```
[7/17/2020, 9:36:55 AM] [Camera-ffmpeg] Snapshot from FRONT DOOR (Axis) at 480:270
[7/17/2020, 9:36:56 AM] [Camera-ffmpeg] Snapshot from LEFT Side Cam at 480:270
[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] Starting RIGHT Front Cam video stream (640x360, 20 fps, 132 kbps, 1316 mtu)... debug enabled
[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] RIGHT Front Cam command: ffmpeg -rtsp_transport tcp -r 18 -i rtsp://root:XXXXXXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 264k -maxrate 132k -payload_type 99 -ssrc 11128696 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params gSDjJemjJP+W6PSw8VDIJ24CKdP7Hzkaf8+9bAS/ srtp://192.168.1.43:55541?rtcpport=55541&localrtcpport=55541&pkt_size=1316 -loglevel level+verbose
[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] 
[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] RIGHT Front Cam: ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
[info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
[info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
[info]   libavutil      56. 31.100 / 56. 31.100
[info]   libavcodec     58. 54.100 / 58. 54.100
[info]   libavformat    58. 29.100 / 58. 29.100
[info]   libavdevice    58.  8.100 / 58.  8.100
[info]   libavfilter     7. 57.100 /  7. 57.100
[info]   libswscale      5.  5.100 /  5.  5.100
[info]   libswresample   3.  5.100 /  3.  5.100
[info]   libpostproc    55.  5.100 / 55.  5.100[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] RIGHT Front Cam: [tcp @ 0x267f030] [verbose] Starting connection attempt to 192.168.1.233 port 554[7/17/2020, 9:37:03 AM] [Camera-ffmpeg] RIGHT Front Cam: [tcp @ 0x267f030] [verbose] Successfully connected to 192.168.1.233 port 554[7/17/2020, 9:37:04 AM] [Camera-ffmpeg] RIGHT Front Cam: [rtsp @ 0x267cf80] [verbose] SDP:
v=0
o=- 815368507048721138 1 IN IP4 192.168.1.233
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://192.168.1.233:554/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQCgC3YC3AQEBpB4kRUA==,aO48gA==
a=ts-refclk:local
a=mediaclk:sender
a=control:rtsp://192.168.1.233:554/axis-media/media.amp/stream=0?streamprofile=Media?tcp&resolution=1280x720
a=framerate:30.000000
a=transform:1.000000,0.000000,0.000000;0.000000,1.000000,0.000000;0.000000,0.000000,1.000000
[7/17/2020, 9:37:04 AM] [Camera-ffmpeg] RIGHT Front Cam: [rtsp @ 0x267cf80] [verbose] setting jitter buffer size to 0[7/17/2020, 9:37:04 AM] [Camera-ffmpeg] RIGHT Front Cam: [h264 @ 0x2680520] [verbose] Reinit context to 1280x720, pix_fmt: yuvj420p[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] Input #0, rtsp, from 'rtsp://root:XXXXXXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720':
[info]   Metadata:
[info]     title           : Session streamed with GStreamer
[info]     comment         : rtsp-server
[info]   Duration: 
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: N/A, start: 0.033344, bitrate: N/A
[info]     Stream #0:0: Video: h264 (Main), 1 reference frame, yuvj420p(pc, bt709, progressive, center), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 180k tbc[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [warning] Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (srtp://192.168.1.43:55541?rtcpport=55541&localrtcpport=55541&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [warning] Codec AVOption tune (Tune the encoding to a specific scenario) specified for output file #0 (srtp://192.168.1.43:55541?rtcpport=55541&localrtcpport=55541&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] Stream mapping:
[info]   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
[info] Press [q] to stop, [?] for help[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [h264 @ 0x269be70] 
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] 
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: Reinit context to 1280x720, pix_fmt: yuvj420p
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [Parsed_scale_0 @ 0x267cb50] [verbose] w:640 h:360 flags:'bicubic' interl:0[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [graph 0 input from stream 0:0 @ 0x29ffab0] [verbose] w:1280 h:720 pixfmt:yuvj420p tb:1/18 fr:18/1 sar:1/1 sws_param:flags=2[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [swscaler @ 0x2a00880] [warning] deprecated pixel format used, make sure you did set range correctly[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [Parsed_scale_0 @ 0x267cb50] [verbose] w:1280 h:720 fmt:yuvj420p sar:1/1 -> w:640 h:360 fmt:yuv420p sar:1/1 flags:0x4[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [h264_omx @ 0x26996f0] [info] Using OMX.broadcom.video_encode[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [h264_omx @ 0x26996f0] [verbose] OMX state changed to 2
[h264_omx @ 0x26996f0] [verbose] OMX state changed to 3
[h264_omx @ 0x26996f0] [verbose] OMX port 201 settings changed
[info] Output #0, rtp, to 'srtp://192.168.1.43:55541?rtcpport=55541&localrtcpport=55541&pkt_size=1316':
[info]   Metadata:
[info]     title           : Session streamed with GStreamer
[info]     comment         : rtsp-server
[info]     encoder         : Lavf58.29.100
[info]     Stream #0:0: Video: h264 (h264_omx), 1 reference frame, yuv420p(center), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 132 kb/s, 20 fps, 90k tbn, 20 tbc
[info]     Metadata:
[info]       encoder         : Lavc58.54.100 h264_omx[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] *** 1 dup![7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] 
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: *** 1 dup![7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame=   20 fps=0.0 q=-0.0 size=      16kB time=00:00:00.90 bitrate= 144.5kbits/s dup=2 drop=0 speed=1.77x    
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] 
[7/17/2020, 9:37:05 AM] [Camera-ffmpeg] RIGHT Front Cam: *** 1 dup![7/17/2020, 9:37:06 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] *** 1 dup![7/17/2020, 9:37:06 AM] [Camera-ffmpeg] RIGHT Front Cam: [info] frame=   45 fps= 44 q=-0.0 size=      37kB time=00:00:02.10 bitrate= 143.7kbits/s dup=4 drop=0 speed=2.06x    
[7/17/2020, 9:37:06 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] *** 1 dup![7/17/2020, 9:37:06 AM] [Camera-ffmpeg] RIGHT Front Cam: [verbose] 
[7/17/2020, 9:37:06 AM] [Camera-ffmpeg] RIGHT Front Cam: *** 1 dup!
```

**Homebridge Config:**

```json
                    "name": "RIGHT Front Cam",
                    "manufacturer": "Axis",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -r 18 -i rtsp://root:XXXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720",
                        "stillImageSource": "-i http://root:XXXXXXX@192.168.1.233/axis-cgi/jpg/image.cgi",
                        "maxStreams": 3,
                        "maxFPS": 20,
                        "vcodec": "h264_omx",
                        "debug": true
                    }
                },
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
homebridge-camera-ffmpeg@2.3.1 
* **Homebridge Version**: 
homebridge@1.2.0-beta.30 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: 
Raspbian Buster
 4.19.118-v7l+

**Comment by Sunoo** [comment]
You say the latest beta causes these problems, but the version you reported of this plugin isn’t a beta.

Looking at your config, nothing should be limiting the bitrate, so perhaps your iOS device is requesting a low bitrate video for some reason? Which device were you streaming from, and were you on wifi or cellular?

If you want to force higher bitrates, you could use the minBitrate config option. I can’t speak to why you’re seeing increased CPU usage though, nothing in this plugin has changed recently with regard to how it is transcoding video.

Also, one bit of weirdness I see in your config is that you are passing `-r 18` in your source to set the framerate to 18fps, but then also set a maxfps of 20. I’m not sure that would cause problems, but you probably should remove the -r argument.

**Comment by burnbrigther** [comment]
Good catch.  Yes I was on mobile.  But even with bitrate going higher, CPU is still high and picture is pixilated.  I will need to tinker some more with the configuration.  **One thing I am seeing are multiple stuck ffmpeg processes.**  I do not believe that is normal.
```top - 12:27:47 up  3:15,  4 users,  load average: 4.52, 4.81, 4.94
Tasks: 156 total,   5 running, 151 sleeping,   0 stopped,   0 zombie
%Cpu(s): 76.1 us, 15.1 sy,  0.0 ni,  7.4 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
MiB Mem :   3906.0 total,   2223.6 free,    484.8 used,   1197.6 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   3266.0 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                      
 8298 homebri+  20   0  192044  36132  11356 R  99.7   0.9  90:59.99 ffmpeg                                                                                                                                                                                       
 1445 homebri+  20   0  194820  38788  11332 R  92.1   1.0 186:45.58 ffmpeg                                                                                                                                                                                       
 7956 homebri+  20   0  192396  36480  11428 R  90.4   0.9  84:18.05 ffmpeg                                                                                                                                                                                       
 1555 homebri+  20   0  191876  35068  11424 R  77.8   0.9 144:48.67 ffmpeg
````
When I started tinkering with the config - I started to receive ffmpeg -1 error.  I think I am seeing what is happening I don't believe all residual ffmpeg instances are being killed off when config-ui-x is restarting.

**Comment by Sunoo** [comment]
Can you give `pgrep -f -a ffmpeg` a run and share the results so we can see what the FFmpeg processes are doing?

I had another user just recently report a similar issue in #651, but we were never able to get to the bottom of it, and reinstalling Homebridge seemed to somehow fix it for them.

**Comment by burnbrigther** [comment]
All I needed to do was to change something in config-ui-x, then restart the config a four times to see all four.  Do you want that pgrep with all four running?  Or do it till I receive ffmpeg error -1?

**Comment by burnbrigther** [comment]
Here is for two ffmpeg (and two node)
````
top - 12:53:08 up  3:40,  5 users,  load average: 2.73, 1.94, 2.33
Tasks: 156 total,   4 running, 152 sleeping,   0 stopped,   0 zombie
%Cpu(s): 52.3 us,  9.1 sy,  0.0 ni, 38.2 id,  0.0 wa,  0.0 hi,  0.5 si,  0.0 st
MiB Mem :   3906.0 total,   2290.0 free,    416.8 used,   1199.2 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   3350.1 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                      
19011 homebri+  20   0  189552  35652  11376 R 120.6   0.9  11:26.23 ffmpeg                                                                                                                                                                                       
19692 homebri+  20   0  192952  36976  11472 S 115.3   0.9   3:42.38 ffmpeg                                                                                                                                                                                       
19498 homebri+  20   0  175788  89508  29916 S   3.3   2.2   0:16.18 node                                                                                                                                                                                         
  588 homebri+  20   0  191876 107176  29720 S   2.7   2.7   2:35.00 node   
````
````
pi@dockerpi-c:~ $ pgrep -f -a ffmpeg
19011 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:XXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 9886894 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params LoCR4KSvEdWOXBvKaxg7pWHnU5f2dZ3LrHOZ4w8I srtp://192.168.1.20:51868?rtcpport=51868&localrtcpport=51868&pkt_size=1316 -loglevel level+verbose
19692 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:XXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 2137269 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params JCxwbBBa3XUSr+esdU7X+t25jJWyWWtmFG5OTLo4 srtp://192.168.1.20:60049?rtcpport=60049&localrtcpport=60049&pkt_size=1316 -loglevel level+verbose
````

**Comment by Sunoo** [comment]
That sounds like possibly a different issue then, though still confusing.

Running the prep once you have a bunch running is good.

Also, I must have missed that you were getting an error out of FFmpeg. What situations does that happen in?

**Comment by burnbrigther** [comment]
I think I noticed when there were four ffmpeg processes.  It appears to me simply that ffmpeg isn't getting cleanly killed off/shut down when doing a config change and restart.  I manually kill off the processes between restarts as a workaround.

**Comment by Sunoo** [comment]
Those definitely look like instances streaming video for the plugin, not doing snapshots or anything... Did you have the camera feed open somewhere when you restarted Homebridge?

I did some brief testing, but wasn’t able to recreate it.

Best guess is that error is coming just from a lack of resources, once you have several instances of FFmpeg chugging along transcoding video on a Pi, there can’t be much left for a fifth.

I do see it using OMX in your log though, so that shouldn’t be it. I am confused as to why you are seeing poor video quality suddenly though, as there have been no changes that should have impacted that.

**Comment by burnbrigther** [comment]
Ok, I can re-create this in a different way.  I stream another instance on my iphone, which spawns an ffmpeg process.  If I leave my window open for a while, a timeout occurs and the window stops streaming ("No response. This camera is not responding" is seen on iPhone).   The related ffmpeg process does not go away (I see the process remaining).   The cleanup of the process doesn't appear to happen.   The process DOES however continue to be tied to the window in homekit even though it has stopped processing video.  It will not process more video and appears to be effectively stuck.  Maybe the plugin believes a session is still happening OR why did the ffmpeg process die or stop processing video?  If the ffmpeg is behaving as it should and timing out as expected, another process should be cleaning it up and unassociating it with the current session.

**Comment by Sunoo** [comment]
That’s an odd thing as well, HomeKit should let you stream video indefinitely. Could you upload a log from when that happens?

This has given my an idea on how to possibly reproduce this though. I wonder if opening up one of the cameras then throwing my device into airplane mode would result in one of these stuck processes. I’ll have to give that a try after I finish making dinner.

**Comment by Sunoo** [comment]
Okay, I was able to recreate this stuck FFmpeg process with the method I mentioned. Now I just need to find a decent way to handle this problem.

**Comment by Sunoo** [comment]
I've put a fix for this into the new beta, you can install that with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. Please let me know if this resolves your issues.

**Comment by burnbrigther** [comment]
@Sunoo thanks.  I'll try it now.  BTW - It's interesting what you describe above as you shouldn't have any remaining streaming sessions open to home when starting up homebridge-camera-ffmpeg.
Shouldn't the application clean up after itself by killing all ffmpeg processes as the process stops?  That would solve the problem of zombie processes remaining.

**Comment by Sunoo** [comment]
Yes, it does that now.

**Comment by Sunoo** [comment]
If you hit an issue about get-port while installing the beta, that has been resolved now as well.

**Comment by burnbrigther** [comment]
1. Installed new beta per your instructions
2. Restarted homebridge - working
3. Made changes to configuration
4. Started homekit via config-ui-x
5. KERPLOOOI!
`[7/18/2020, 12:35:40 PM] Loading 4 platforms...
[7/18/2020, 12:35:40 PM] [Config] Initializing config platform...
[7/18/2020, 12:35:40 PM] [Config] Running in Service Mode
[7/18/2020, 12:35:40 PM] Error loading platform requested in your config.json at position 2
[7/18/2020, 12:35:41 PM] Error: The requested platform 'Camera-ffmpeg' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/18/2020, 12:35:41 PM] Got SIGTERM, shutting down Homebridge...
[7/18/2020, 12:35:46 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/18/2020, 12:35:51 PM] [HB Supervisor] Restarting Homebridge...`

**Comment by burnbrigther** [comment]
Zombies:
`pi@dockerpi-c:~ $ pgrep -f -a ffmpeg
996 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -r 24 -i rtsp://root:Acmg$c4mt0U@192.168.1.230:554/axis-media/media.amp?streamprofile=Media?tcp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 12826153 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params YGRJjUBtp6oSOnWYXpDZ3qsqxr1nni4dGSiZNgp8 srtp://192.168.1.184:58694?rtcpport=58694&localrtcpport=58694&pkt_size=1316
15456 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:Acmg$c4mt0U@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1920:1080 -b:v 800k -bufsize 1600k -maxrate 800k -payload_type 99 -ssrc 5729139 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params kChNsdwkEbCOOxXKZ41GrdwQlMM8e4amsVI/8dAb srtp://192.168.1.183:57597?rtcpport=57597&localrtcpport=57597&pkt_size=1316
15544 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:Acmg$c4mt0U@192.168.1.231:554/axis-media/media.amp?streamprofile=Media -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 8728374 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 9pS3fj0RzdUGag+4LJd/3IX1MWXZz3TqgJ/MfGqA srtp://192.168.1.20:59025?rtcpport=59025&localrtcpport=59025&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 2891183 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params KI78bNHyTqEDFFx+PfTEVGKhzCV5ltGycUGKsOvt srtp://192.168.1.20:55903?rtcpport=55903&localrtcpport=55903&pkt_size=188`

**Comment by burnbrigther** [comment]
Zombies:
`pi@dockerpi-c:~ $ pgrep -f -a ffmpeg
996 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -r 24 -i rtsp://root:XXXXXXX@192.168.1.230:554/axis-media/media.amp?streamprofile=Media?tcp -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 12826153 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params YGRJjUBtp6oSOnWYXpDZ3qsqxr1nni4dGSiZNgp8 srtp://192.168.1.184:58694?rtcpport=58694&localrtcpport=58694&pkt_size=1316
15456 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:XXXXXXX@192.168.1.233/axis-media/media.amp?streamprofile=Media?tcp&resolution=1280x720 -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 20 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1920:1080 -b:v 800k -bufsize 1600k -maxrate 800k -payload_type 99 -ssrc 5729139 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params kChNsdwkEbCOOxXKZ41GrdwQlMM8e4amsVI/8dAb srtp://192.168.1.183:57597?rtcpport=57597&localrtcpport=57597&pkt_size=1316
15544 /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://root:XXXXXXX@192.168.1.231:554/axis-media/media.amp?streamprofile=Media -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 8728374 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 9pS3fj0RzdUGag+4LJd/3IX1MWXZz3TqgJ/MfGqA srtp://192.168.1.20:59025?rtcpport=59025&localrtcpport=59025&pkt_size=1316 -map 0:1 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 2891183 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params KI78bNHyTqEDFFx+PfTEVGKhzCV5ltGycUGKsOvt srtp://192.168.1.20:55903?rtcpport=55903&localrtcpport=55903&pkt_size=188`

**Comment by Sunoo** [comment]
Did you end up with beta.4 or beta.5? There was a missed dependency in beta.4 that I resolved.

Also, the zombies are cleared on shutdown of Homebridge. If zombies were already running when Homebridge starts, nothing will be done to terminate them.

**Comment by burnbrigther** [comment]
I had Beta 4
```homebridge-camera-ffmpeg@2.3.2-beta.4 ```
Just upgraded to beta 5.
```homebridge-camera-ffmpeg@2.3.2-beta.5```
This works @Sunoo.  It's cleaning up nicely.  Well done.
In my testing, I found I could only have two simultaneous stream running on Pi4 w/4GB.  That seems pretty low.  Any ideas on how I can optimize/reduce/eliminate the transcoding?  Or does two streams for this device seem to be the norm?

**Comment by burnbrigther** [comment]
As a follow up to this, this device has 4 cores and this only seems to be using one?  SMP is not an option or balancing the ffmpeg process across additional cores can't be done?  If there is history with this part of the discussion, I apologize in advance for not RTFMing. :)

**Comment by Sunoo** [comment]
Great, glad you’re working. I’ll close this out now.

As for your other question, if your camera is putting out h.264, you can try adding `-vcodec h264_mmal` to the start of your source. You could also try experimenting with the ‘copy’ vcodec option in your config to skip transcoding entirely, but that can cause other problems.

**Comment by Sunoo** [comment]
Linux’s scheduler should handle putting FFmpeg on various cores, perhaps using OMX is causing issues with that? You could try using the standard libx264 instead and see if that works any better for you.

**Comment by burnbrigther** [comment]
@Sunoo thank you for fixing this.  You are doing great work here!

**Comment by burnbrigther** [comment]
I am genuinely surprise to see libx264 performing better than than h264_omx.  It was always my impression that omx was hardware optimized and it just couldn't get better than that.  I can do 3 streams at 80% cpu without having ffmpeg -1 error.  The streams appear to be less pixilated than omx too.  I will continue to experiment.

**Comment by Sunoo** [comment]
I’m not super up on the OMX stuff, but my understanding is that it hasn’t really been updated much while the processors in the Pis have kept getting faster.
