### ISSUE TITLE
Dont know what's wrong (noob btw)

### ISSUE THREAD

**Issue by hanzala-123** [Sunoo/homebridge-camera-ffmpeg#688]
I am entering all my details correctly (i think) and am getting stange issues.

```
[Camera-ffmpeg] Starting Ender 3 1111 video stream (1280x720, 30 fps, 802 kbps, 1316 mtu)... debug enabled
[7/24/2020, 15:44:03] [Camera-ffmpeg] Ender 3 1111 command: ffmpeg http://192.168.1.83/webcam/?action=stream -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 802k -bufsize 1604k -maxrate 802k -payload_type 99 -ssrc 3257660 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params k2IOjR8z1ODnRMTcjoy7t07Q58x+pMbyR/GEv/tO srtp://192.168.1.79:53694?rtcpport=53694&localrtcpport=53694&pkt_size=1316 -loglevel level+verbose
[7/24/2020, 15:44:03] [Camera-ffmpeg] Ender 3 1111: [info] ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
[info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
[info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa

[7/24/2020, 15:44:03] [Camera-ffmpeg] Ender 3 1111: [info]   libavutil      56. 31.100 / 56. 31.100
[info]   libavcodec     58. 54.100 / 58. 54.100
[info]   libavformat    58. 29.100 / 58. 29.100
[info]   libavdevice    58.  8.100 / 58.  8.100
[info]   libavfilter     7. 57.100 /  7. 57.100
[info]   libswscale      5.  5.100 /  5.  5.100
[info]   libswresample   3.  5.100 /  3.  5.100
[info]   libpostproc    55.  5.100 / 55.  5.100

[7/24/2020, 15:44:03] [Camera-ffmpeg] Ender 3 1111: [NULL @ 0x2be3fd0] [error] Unable to find a suitable output format for 'http://192.168.1.83/webcam/?action=stream'
[error] http://192.168.1.83/webcam/?action=stream: Invalid argument

[7/24/2020, 15:44:04] [Camera-ffmpeg] [Ender 3 1111] ffmpeg exited with code: 1 and signal: null (Error)
[7/24/2020, 15:44:04] [Camera-ffmpeg] Stopped Ender 3 1111 video stream!
[7/24/2020, 15:44:38] [Camera-ffmpeg] Ender 3 1111 appears to be inactive for over 5 seconds. Stopping stream.
```

![Capture](https://user-images.githubusercontent.com/66522609/88404158-6847aa80-cdc5-11ea-8064-0971a7b22e4d.JPG)

**Comment by Sunoo** [comment]
Looks like an Octoprint webcam setup. Assuming you haven't changed things from the way they work by default try using:

- source: `http://192.168.1.83:8080/?action=stream`
- stillImageSource: `http://192.168.1.83:8080/?action=snapshot`

If Octoprint and Homebridge are running one the same device, you could use 127.0.0.1 instead of 192.168.1.83

**Comment by hanzala-123** [comment]
that was quick!
what shall i use as the video processor?

**Comment by Sunoo** [comment]
Leaving it unset is usually your best bet, unless you have some unique setup.

**Comment by hanzala-123** [comment]
sure.
sorry for the questions.
what about the codec. I assume you know more than me about octoprint

**Comment by Sunoo** [comment]
If you're running on a raspberry pi, you can use `h264_omx`, otherwise `libx264`.

**Comment by hanzala-123** [comment]
No luck friend.

<img width="1005" alt="Chaudry Residence Brain" src="https://user-images.githubusercontent.com/66522609/88414542-f1b2a900-cdd4-11ea-9c44-593490839f0b.png">

**Comment by hanzala-123** [comment]
This is a webcam connected to octoprint btw and is using default settings

**Comment by Sunoo** [comment]
If you go to http://192.168.1.83:8080/?action=stream in your browser, what do you see?

**Comment by hanzala-123** [comment]
I see my stream

**Comment by hanzala-123** [comment]
<img width="1024" alt="PNG image" src="https://user-images.githubusercontent.com/66522609/88415015-b369b980-cdd5-11ea-8d56-37769633ed7d.png">
<img width="1024" alt="PNG image" src="https://user-images.githubusercontent.com/66522609/88415073-cb413d80-cdd5-11ea-8892-f9480a1f4db0.png">

**Comment by Sunoo** [comment]
What are you seeing in your Homebridge logs with debug set to true?

**Comment by hanzala-123** [comment]
![IMG_1034](https://user-images.githubusercontent.com/66522609/88415593-a7cac280-cdd6-11ea-9433-8af5f27025e5.jpeg)

**Comment by hanzala-123** [comment]
I got it to work now. thanks so much for the help. What i did was install another plugin and look at the prefix used e.g -re -I and used it on yours. Thanks so much for helping brother.

**Comment by Sunoo** [comment]
Oh, somehow I missed that you were missing `-i`. I highly recommend against `-re` though.
