### ISSUE TITLE
Sporadically no live video in HomeApp "Wait until no one else uses the camera"

### ISSUE THREAD

**Issue by california444** [Sunoo/homebridge-camera-ffmpeg#695]
**Describe The Bug:**
Since the Zombie ffmpeg fix release, I sporadically don't get a live video in Home App but the error that I have to wait until no one else uses the camera (although no one else is watching).
Restart of Homebridge is the only way I found to resolve the issue for some time.

In the logs I can see in this case that the device was inactive. 
It looks like the stream is not released properly and at some point HomeKit thinks that too many streams are open...

**To Reproduce:**
Only a sporadic issue. I found no way to reproduce...

**Logs:**

```
[7/27/2020, 21:09:15] [Camera-ffmpeg] [Isabel] [info] frame=27797 fps= 15 q=-1.0 size=  289434kB time=00:30:55.67 bitrate=1277.7kbits/s speed=   1x    
[7/27/2020, 21:09:16] [Camera-ffmpeg] [Isabel] [info] frame=27805 fps= 15 q=-1.0 size=  289505kB time=00:30:56.21 bitrate=1277.7kbits/s speed=   1x    
[7/27/2020, 21:09:16] [Camera-ffmpeg] [Isabel] Device appears to be inactive for over 5 seconds. Stopping stream.
[7/27/2020, 21:09:16] [Camera-ffmpeg] [Isabel] Stopped video stream.
[7/27/2020, 21:09:16] [Camera-ffmpeg] [Isabel] ffmpeg exited with code: null and signal: SIGKILL (Expected)
```

**Homebridge Config:**

``` {
                    "name": "Isabel",
                    "manufacturer": "Foscam",
                    "model": "FI9902P",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -err_detect ignore_err -i rtsp://url -tune zerolatency -preset ultrafast",
                        "stillImageSource": "-i url",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1280,
                        "maxFPS": 25,
                        "maxBitrate": 2000,
                        "vcodec": "copy",
                        "videoFilter": "none",
                        "additionalCommandline": "-fflags +discardcorrupt+igndts",
                        "audio": false,
                        "debug": true
                    }
```

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.4.0
* **Homebridge Config UI X Plugin Version**: 4.24.0
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
Do you know if this only happens after seeing `Device appears to be inactive for over 5 seconds. Stopping stream.` in your logs? I'm guessing that perhaps I need to do something different to close the stream out when those happen.

**Comment by california444** [comment]
Yes, that log line was always there when this issue occurs...

**Comment by Sunoo** [comment]
Okay, good, that's what I expected. Let me do some poking and see if I can figure out what needs to be done. Clearly I'm not shutting down the connection properly in HomeKit in that case.

**Comment by Sunoo** [comment]
I think I solved it. I found a way to recreate it at will, and after adding this fix, I was no longer able to get it to happen.

I know you said that you have trouble recreating it on demand, but I pushed a beta if you wanted to give it a shot `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. I want to do a bit more testing myself before pushing it as a release version.

**Comment by california444** [comment]
Cool, thx. Beta is installed, I will let you know, if the issue happens again...

**Comment by Sunoo** [comment]
The beta should resolve the issue in at least some situations, I’m just not sure if my method of forcing the issue to happen has the same exact results as whatever is happening for you in actual use.

**Comment by california444** [comment]
So I found a way to reproduce the issue (but I think there must also be another way to get into this issue). When I just close my MacBook while the video is live streaming and wait for some time and then open the MacBook again, the inactive issue happens, and unfortunately the issue still exists even with the new beta...

**Comment by Sunoo** [comment]
I’ll give that a shot. I was forcing the issue by turning wifi off on my iPad while streaming, and that at least seemed to be resolved. I’ll give what you said a shot with my laptop shortly.

**Comment by california444** [comment]
As I have set maxStreams = 2, I needed to do it twice until I saw the "No response" screen....

**Comment by Sunoo** [comment]
In my testing earlier I had set it down to 1 stream, just to make it easier to trigger.

**Comment by Sunoo** [comment]
I cannot recreate the issue by closing my laptop lid. I did notice that it takes around 30 seconds after closing the lid before the stream goes inactive though.

The closest I've been able to get is that sometimes I get the "no response" message, but I've not been able to trigger the too many people are watching message on the beta.
