### ISSUE TITLE
Documentation bug:

### ISSUE THREAD

**Issue by jsiegenthaler** [Sunoo/homebridge-camera-ffmpeg#698]
**Describe The Problem:**
The documentation here:
https://www.npmjs.com/package/homebridge-camera-ffmpeg

states under **Most Important Parameters**:
`platform: (Required) Must always be set to Config-ffmpeg.`

This is incorrect. 
The platform name is   "**Camera**-ffmpeg",

**Comment by Sunoo** [comment]
Wow, can’t believe I did that. I can’t update NPM without pushing a new release, so it’ll be fixed in the next version.

**Comment by jsiegenthaler** [comment]
Thanks @Sunoo
