### ISSUE TITLE
"interfaceName": not working ?

### ISSUE THREAD

**Issue by tumekee** [Sunoo/homebridge-camera-ffmpeg#701]
I have 2x NIC's on my server if they are both enabled then i am unable to stream on my local network ( externally works fine as port forwarding specifies the internal IP therefore the NIC ) . I tried specifying "interfaceName": which , by the description this is used for , but appears to make no difference. i have everything working now with one NIC but would like to option to enable to the other one again at some point 👍  

Node.js Version 12.16.3
NPM Version 6.14.5
Homebridge Version 1.1.1 
Homebridge Camera FFmpeg Version 2.4.2
Homebridge Config UI X Plugin Version 4.24.0
Operating System  Ubuntu 20.04

**Comment by Sunoo** [comment]
What value did you have interfaceName set to?

**Comment by tumekee** [comment]
Ifconfig returns eno1 and eno2 as the interface names, I have eno1 as the value.

**Comment by Sunoo** [comment]
Interesting, did you get any errors or warnings in your logs? I assume eno2 was the interface you disabled.

If you run `node -e "console.log(require(\"os\").networkInterfaces())"` do you see the interfaces you’d expect?

I’m pretty sure what you did should have worked, but perhaps you have an unusual network setup?

**Comment by tumekee** [comment]
top would normally be eno2 ( but is currently disabled ) , as far as my network setup goes it doesn't get much more basic I'm afraid , default IP range , router only does NAT and DHCP an nothing else , the most complicated part of my network set up is the static IP assigned to the Server ( below ) eno2 is normally 192.168.1.132

`{
  lo: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    }
  ],
  eno1: [
    {
      address: '192.168.1.131',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '00:1e:c9:aa:e6:a9',
      internal: false,
      cidr: '192.168.1.131/24'
    }
  ]
}
`

**Comment by Sunoo** [comment]
Okay, I think that actually explains it. You have two NICs connected to the same network, which is fairly unusual. Because of that, there is no way to be sure which one your iOS device will try to connect on. Unfortunately, HomeKit requires an answer from the same NIC it talked to, so I don't think there is any way for me to support your setup.

**Comment by tumekee** [comment]
no worries ! at least i know for sure now ! thanks for your time 👍

**Comment by Sunoo** [comment]
Sure thing. I really hope one day I’ll be able to figure out which interface HomeKit wants to use, and select automatically, but I haven’t found a way to do that yet.
