### ISSUE TITLE
Screenshot Time

### ISSUE THREAD

**Issue by lfiocco** [Sunoo/homebridge-camera-ffmpeg#706]
is there any way to set the times between screenshots? currently it about every minute. Can we get this down to 10 seconds?

**Comment by Sunoo** [comment]
It’s decided by HomeKit, but every case I’ve personally seen, HomeKit pulls a snapshot every 10 seconds.

**Comment by lfiocco** [comment]
I have been experimenting. Fresh install of everything on Raspberry Pi this time... 
I have a total of 6 cameras, they can go up to 1080, however for speed, 480x270 is good, if i see something odd, can always switch to the manufacture app and go HD.

So I had time to configure only 2 cameras before leaving, guess what? it was soooo fast... click, 8-10 seconds later i have a stream and this is on LTE..wifi even faster...thumbnails are between 10-15 seconds...

So i started adding and adding cameras util i got to 6, my full config...now everything started slowing down again.

having 6 cameras, just sitting there generating thumbnails between 60-75 seconds...for each. the streams also started to slow down also, between the time I click on the camera and the time I see the frames 45-65 seconds again...

Looks like the more cameras you add, the slower it reacts and sends live streams... 

The sweet spot for me is 2 cameras. the reaction time is very good. 3,4 starts slowning down... 5-6 your at 60 seconds waiting time. No idea if it's homebridge or the plug in..

I will bring this up on Ubuntu 20.04 LTS, 3 VM's each with2 cameras see where that goes..let you know.

**Comment by Sunoo** [comment]
The most cameras I’ve used at a time on one installation was 3, sounds like maybe Homebridge isn’t happy about much more than that? I don’t think there is much I can do about that.

**Comment by lfiocco** [comment]
btw, one camera 3-4 seconds....

**Comment by oznu** [comment]
Pre-[v2.0.0](https://github.com/Sunoo/homebridge-camera-ffmpeg/releases/tag/v2.0.0) the cameras were not all behind the same bridge - they were external so not all cameras had to be ready for a single snapshot to load - perhaps an option to make cameras "external" again would help performance?

**Comment by lfiocco** [comment]
I fixed the issue by running one homebridge and one camera. (VMs) I can get 1920x1080 30fps. Change the Rez or frame rate does change the speed. Would be nice to run all on one, but this works.

**Comment by Sunoo** [comment]
@oznu That's not a bad idea, I may work on that soon and provide people with an option to set individual cameras to be unbridged. I'll have to look into how to implement that way of doing things, since that's before my time working on this, and I think before the TypeScript conversion on this plugin.

**Comment by lfiocco** [comment]
If you can pull that off. wow. I am looking into switching to docker containers on Ubuntu. running 6 vm's a eating resources, plus another 4 for other services.  Not too familiar with dockers. I will read up on it.

Are docker containers slower than VM's?

**Comment by oznu** [comment]
You can run multiple instances without VMs or containers. See the wiki guide for you platform over on the homebridge project. Each guide had a section on "multiple instances".

**Comment by Sunoo** [comment]
It's definitely possible, just a matter of how much work it'll take.

In the meantime, it is possible to run two instances of Homebridge next to each other, just specify different ports and such.

**Comment by Sunoo** [comment]
I've just pushed a beta that allows for unbridging cameras, just set `unbridge` to true inside the camera settings of the config.json (it's also available in Config UI X). To install the beta, you can run `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`.

**Comment by lfiocco** [comment]
Nice! I will test later today, I will report my findings

**Comment by lfiocco** [comment]
o, Fresh install, Ubuntu 20.04LTS, installed updates, installed homebridge as per instructions, no errors. 
installed plugin v.2.4.4-beta 3

                    "name": "Camera 1 - Front-Door",
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://username:somepw@cam1.testthisplugin.ca:554/cam/realmonitor?channel=1&subtype=1",
                        "maxFPS": 30,
                        "maxBitrate": 2048,
                        "debug": true
                    }

rez = 1280x720, Changing these values did not really make a difference.

the results are the same as running one homebridge per camera. Super fast...thumbnails are generated every 16 seconds on iOS, 45 seconds on macOS.

Stream WiFi, click = 3-4 seconds to open the stream.
Stream on LTE = 8-10 seconds..
When your on LTE, you can see the thumbnail requests are much slower, the App knowns your on LTE and slows it down by 4 times. Apple trying to save your data plan? back on wifi, boom! 12-16 seconds...

BTW adding the cameras was about as fast as your finger can handle..

what is important, the cameras stream on click. before there was a delay of 30-45 seconds. Seems that it had to wait for all the thumbnails to be generated before it responded to the request for stream. Problem seems fixed with this version. Good work and thank you!

**Comment by Sunoo** [comment]
Glad it’s working for you. I’ll probably push this version to release once I ever get electricity back.
