### ISSUE TITLE
Scrambled snapshots stream works fine

### ISSUE THREAD

**Issue by Jborn4christ** [Sunoo/homebridge-camera-ffmpeg#716]
**Describe The Problem:**
In the main screen that shows the still image previews before accessing live streams, the snapshot has been showing scrambled. The live feed works fine. It’s a Wyze cam with the v2 beta enabled rtsp.

![2C62A7D4-A099-41EB-A6A6-A508DD07392F](https://user-images.githubusercontent.com/3494551/89694830-ecc71c80-d8df-11ea-96b2-d046824a4554.png)

**To Reproduce:**
To reproduce, I open the home app and look at the driveway thumbnail preview

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
Please share your config. The WyzeCams are known to occasionally send corrupted frames, so there are tweaks that can be done to skip over them.

**Comment by Jborn4christ** [comment]
@Sunoo I did see there was an update, so went ahead and installed that, checked and seemed to be better, but here’s the config in case you see something i can tweak to maximize consistency.

![8198F44A-A047-46F0-B070-53F7AD8E966E](https://user-images.githubusercontent.com/3494551/89695080-c190fd00-d8e0-11ea-84c9-9f5704b6a51a.png)

**Comment by Sunoo** [comment]
It's impossible to see your full 'source' line, but you should definitely remove the `-re` and you should consider adding `-fflags +discardcorrupt` to the beginning of that.

**Comment by Jborn4christ** [comment]
@Sunoo That seems to have worked. I’ll keep an eye on it. Thanks
