### ISSUE TITLE
homebridge-camera-ffmpeg v2.4.4 ability to call camera snapshot gone

### ISSUE THREAD

**Issue by psyciknz** [Sunoo/homebridge-camera-ffmpeg#717]
**Describe The Problem:**

upgraded tonight to look at adding some external motion detectors via mqtt (camerevents)

but after adding the motion device, i was trying to set up a take snap shot on motion detection, but i cant call the camera  now for an action.

I was able to do this previously, as id actually been triggering an image on garage door open.

**To Reproduce:**

new autonation
on motion detection sensor
next
choose action, stuck here.

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

```
"name": "Camera ffmpeg",
            "mqtt": "mqt,
            "topic": "CameraEvents/+/event",
            "cameras": [
                {
                    "name": "Backdoor",
                    "manufacturer": "Dahua",
                    "motion": false,
                    "switches": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://IOS:password@cam-nvr554/cam/realmonitor?channel=2&subtype=1",
                        "stillImageSource": "-i http://IOS:password@cam-nvr/cgi-bin/snapshot.cgi?channel=2",
                        "maxStreams": 1,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "audio": false,
                        "debug": false
                    }
                },

```

only a partial config.  camera works for automTic snapshot and live.

**Screenshots:**

**Environment:**
docker on ubuntu.

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
What is publishing the MQTT messages?

**Comment by psyciknz** [comment]
https://github.com/psyciknz/CameraEvents

Just posts a ON of OFF.

**Comment by Sunoo** [comment]
What you described won’t work directly with this plugin’s MQTT implementation, as you seem to be trying.

If you are trying to use HomeKit automations to trigger the motion alert, you’ll need to set motion to true to enable the motion sensor.

**Comment by psyciknz** [comment]
Is there a way of doing it without an homekit automation?

I did see something about looking at some mqtt base topic as part of the camera-ffmpeg config 

Can that be used for triggering snapshots?

**Comment by psyciknz** [comment]
I read here https://github.com/Sunoo/homebridge-camera-ffmpeg

About the motion and switches settings.   Unsure what these are 4.  Are they to be watched by the plugin and will set a motion sensor and cause a snap shot to be taken?

**Comment by Sunoo** [comment]
Better documentation on those features ares here: https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

When a motion sensor is tripped, the devices seem to tend to update their snapshots, and if you have notifications set up in the Home app, you’ll get a snapshot with the alert.

**Comment by psyciknz** [comment]
I'm looking at changes to the camera Events service to match this.

Do you think you might be able to consider adding the following format for mqtt messages?
```
homebridge/motion/<camera> payload ON or OFF
```
My CameraEvents service can send a photo....but it tends to have a bit too much of a delay and so misses the event. So I'll look at camera-ffmeg for the snapshots.

**Comment by psyciknz** [comment]
So I've got my events system now sending the homebridge format motion events...
```
CameraEvents/motion/reset Backyard
CameraEvents/motion Backdoor
CameraEvents/motion Backdoor
CameraEvents/motion Backdoor
CameraEvents/motion Backdoor
CameraEvents/motion/reset Backdoor
CameraEvents/motion Garage
CameraEvents/motion/reset Garage
CameraEvents/motion Garage
CameraEvents/motion Garage
CameraEvents/motion/reset Garage
CameraEvents/motion Backdoor
CameraEvents/motion/reset Backdoor
```

Base topic changed obviously.  And on my phone I get a notification that motion has been detected, but it doesn't up[date the snapshot.....unless I go into the camera and set the Motion Trigger Switch....hmm it does seem to update and send an image if the notification is triggered while I'm viewing the live camera feed (in the home app)

**Comment by Sunoo** [comment]
Do the motion notification doesn’t have a snapshot at all on it when it comes in? Also, the Homebridge logs should show snapshots being requested if you run with debug enabled. Do any attempts appear?

The only thing that comes to mind, assuming the request happens at all, is that maybe the camera or Homebridge is taking too long to respond.
