### ISSUE TITLE
Motion detection on camera Hikvision DS-2CD2752F-IZS

### ISSUE THREAD

**Issue by Martinx64** [Sunoo/homebridge-camera-ffmpeg#726]
Hello i would like to have following homekit scene. When my cammera detects motion, i want to trigger homekit scene, that my hue lamps will turn on. I can see in my homekit accessory motion sensor, but no motion is detected by homekit motion sensor.

Camera streaming is working.

Do i need some additional motion sensor or can i do it just with my camera and some mqtt combination? 

* **Node.js Version**: 14.4.0
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version 2.4.4
* **Homebridge Config UI X Plugin Version v4.24.0
* **Operating System**: Ubuntu 18.04

json.config bellow:

   {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Hikvision",
                    "motion": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:password@ipaddress/Streaming/Channels/xxx",
                        "stillImageSource": "-i http://user:password@ipaddress/Streaming/channels/x/picture",
                        "vcodec": "h264",
                        "audio": true,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Comment by Sunoo** [comment]
This plugin doesn’t do any motion detection on its own, you need to trigger it via one of these methods: https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

The most common that I’d expect cameras to support directly would be either FTP or SMTP.
