### ISSUE TITLE
DCS-933L tested config

### ISSUE THREAD

**Issue by agneevX** [Sunoo/homebridge-camera-ffmpeg#743]
**Manufacturer/Model:**

D-Link DCS 933L

**Homebridge Config:**

```json
                    "name": "Front Gate Camera",
                    "manufacturer": "D-Link",
                    "model": "DCS-933L",
                    "firmwareRevision": "1.15.01",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://user:password@10.0.0.20/mjpeg.cgi -i http://user:password@10.0.0.20/audio.cgi",
                        "stillImageSource": "-i http://user:password@10.0.0.20/image/jpeg.cgi",
                        "maxStreams": 6,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 6000,
                        "minBitrate": 6000,
                        "vcodec": "h264_omx",
                        "packetSize": 564,
                        "videoFilter": "scale=640:480",
                        "mapaudio": "1:0",
                        "audio": true,
                        "debug": false
```

**Additional Information:**

Tested on Raspberry Pi 4. There is a delay while using audio, so turn it off if it's not very important.

**Comment by Sunoo** [comment]
Added https://sunoo.github.io/homebridge-camera-ffmpeg/configs/D-Link-DCS-933L.html

**Comment by agneevX** [comment]
> I want to review the logs you shared before I accept that -re is required, since that really makes no sense to me to have resolved the issue.

Sure, but I can tell you for a fact that without `-re` I got errors: https://hastebin.com/mipilapaju.cs

> Why are you resizing the video with videoFilter instead of maxWidth and maxHeight, especially when you have both set?

Because setting `maxWidth` and `maxHeight` to the actual dimensions of the video output results in no video in the Home app. 
Before a couple of updates, the `videoFilter` parameter was not required as the 640x480 output was automatically adjusted... even with a 1280x720 setting in the config.

**Comment by agneevX** [comment]
In light of the latest update, I have updated my config.

```json
{
    "name": "Front Gate Camera",
    "manufacturer": "D-Link",
    "model": "DCS-933L",
    "firmwareRevision": "1.15.01",
    "motion": false,
    "videoConfig": {
        "source": "-re -f mjpeg -i http://admin:admina@10.0.0.20/mjpeg.cgi -i http://admin:admina@10.0.0.20/audio.cgi",
        "stillImageSource": "-i http://admin:admina@10.0.0.20/image/jpeg.cgi",
        "maxStreams": 6,
        "maxWidth": 0,
        "maxHeight": 0,
        "maxFPS": 0,
        "maxBitrate": 6000,
        "forceMax": true,
        "preserveRatio": true,
        "vcodec": "h264_omx",
        "mapaudio": "1:0",
        "audio": true,
        "debug": false
    }
}
```

**Comment by Sunoo** [comment]
Thanks, I'll update the config on the site and close this out later today.

**Comment by Sunoo** [comment]
Updated https://sunoo.github.io/homebridge-camera-ffmpeg/configs/D-Link-DCS-933L.html
