### ISSUE TITLE
Instacam / Motion, bad URL schema

### ISSUE THREAD

**Issue by busaku** [Sunoo/homebridge-camera-ffmpeg#759]
I love the camera-ffmpeg plugin. Runs like a charm.
But my "Instar IN-7011HD" cam, arent able to call the motion URL.

Caus instar triggerd the alarm-server like:
http://.../motion%3FFrontdoor
(It replaces the ? with %3F)

Or if i call the name like a attribute:
http://.../motion?Frontdoor=
(it places automatically the = at the end..)

It isnt possible to put the correct url into the configuration of the instar-cam.
May, its possible to call the camera with a parameter?

Like http://.../motion?cam=xxx

Would be amazing :)

**Comment by Sunoo** [comment]
Interesting that that software can not properly handle a valid URL.

I can definitely have it so that the `=` and anything after it is ignored. Should be a fairly simple feature, so it should be in the next release.

**Comment by busaku** [comment]
that would be super nice of you 🥰

**Comment by Sunoo** [comment]
Added in v3.0.2

**Comment by busaku** [comment]
Works! Thank you!

**Comment by Sunoo** [comment]
Great, glad I got that resolved for you.
