### ISSUE TITLE
Possibility of remove direct dependency to ffmpeg-for-homebridge

### ISSUE THREAD

**Issue by zokl** [Sunoo/homebridge-camera-ffmpeg#768]
Hello,
I'm using openwrt and I have a problem with the ffmpeg-for-homebridge package on different platforms. I prefer to use the built-in ffmpeg. Would it be possible for homebridge-camera-ffmpeg not to have a direct dependency on this package, or at least if it doesn't find it, but the built-in ffmpeg will be available, then it won't fail?

Typically output without ffmpeg-for-homebridge:
```
Wed Sep  2 21:04:13 2020 daemon.err homebridge[2233]: [Wed Sep 02 2020 21:04:13 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-camera-ffmpeg:
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: [Wed Sep 02 2020 21:04:14 GMT+0000 (UTC)] Error: Cannot find module 'ffmpeg-for-homebridge'
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: Require stack:
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge-camera-ffmpeg/dist/streamingDelegate.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge-camera-ffmpeg/dist/index.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/lib/plugin.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/lib/pluginManager.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/lib/api.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/lib/server.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/lib/cli.js
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]: - /usr/lib/node/homebridge/bin/homebridge
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at require (internal/modules/cjs/helpers.js:72:18)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Object.<anonymous> (/usr/lib/node/homebridge-camera-ffmpeg/src/streamingDelegate.ts:30:22)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Module.load (internal/modules/cjs/loader.js:985:32)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
Wed Sep  2 21:04:14 2020 daemon.err homebridge[2233]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
```

If I remove **pathToFfmpeg** constant from streamingDelegate.js it works fine.

Is it possible to make a better solution?

Thank you,
Zbynek Kocur

**Comment by Sunoo** [comment]
I don’t understand exactly how you got it into that state, did you manually delete that package after installation?

Already, if ffmpeg-for-homebridge doesn’t successfully download a version of FFmpeg (because, for example you aren’t on a supported OS) this plugin will use the version of FFmpeg in the system path. It can also be overridden with the videoProcessor config option.

**Comment by zokl** [comment]
> I don’t understand exactly how you got it into that state, did you manually delete that package after installation?
> 
> Already, if ffmpeg-for-homebridge doesn’t successfully download a version of FFmpeg (because, for example you aren’t on a supported OS) this plugin will use the version of FFmpeg in the system path. It can also be overridden with the videoProcessor config option.

The loading procedure as described does not work because the loading of the homebridge-camera-ffmpeg module fails in the absence of the ffmpeg-for-homebridge  module as I mentioned above. 

It would take care of loading the ffmpeg-for-homebridge module in the streamingDelegate.js file.  Me helped delete row with its import.

**Comment by Sunoo** [comment]
Why have you removed the ffmpeg-for-homebridge module? There is no reason to do that.

That module will return `undefined` if a binary was not downloaded by it. This plugin will see that and swap to the version in the system path.

**Comment by zokl** [comment]
> Why have you removed the ffmpeg-for-homebridge module? There is no reason to do that.
> 
> That module will return `undefined` if a binary was not downloaded by it. This plugin will see that and swap to the version in the system path.

I made a Makefile for OpenWRT - https://github.com/zokl/openwrt-node-packages/blob/master/node-homebridge-camera-ffmpeg/Makefile but if this module persist in your installation as a dependency a have a problem with C and C++  libraries which are on ffmpeg downloaded with the module ffmpeg-for-homebridge.

**Comment by Sunoo** [comment]
Open an issue with ffmpeg-for-homebridge then? Sounds like they aren’t downloading the right binary for your system.

You could also do what I suggested earlier and set `videoProcessor` to `ffmpeg` to use the one in your system path.

**Comment by zokl** [comment]
> Open an issue with ffmpeg-for-homebridge then? Sounds like they aren’t downloading the right binary for your system.
> 
> You could also do what I suggested earlier and set `videoProcessor` to `ffmpeg` to use the one in your system path.

I try to set `videoProcessor` to `ffmpeg` but loading of  `homebridge-for-ffmpeg` is earlier....

**Comment by zokl** [comment]
For embedded and compiled systems will be good if you will be able to have a homebridge-for-ffmpeg as an option not required.

**Comment by Sunoo** [comment]
Here is the logic you’re referring to: https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/315e8afea080bdc1d7b0c66125a29496d038af02/src/streamingDelegate.ts#L83

If videoProcessor is set, it uses that, if not it tries for ffmpeg-for-homebridge, if that isn’t set, it defaults to the ffmpeg in the system path.

**Comment by zokl** [comment]
> Here is the logic you’re referring to:
> 
> https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/315e8afea080bdc1d7b0c66125a29496d038af02/src/streamingDelegate.ts#L83
> 
> If videoProcessor is set, it uses that, if not it tries for ffmpeg-for-homebridge, if that isn’t set, it defaults to the ffmpeg in the system path.

But it fails on this import in the same file:
```import ffmpegPath from 'ffmpeg-for-homebridge';```

**Comment by Sunoo** [comment]
Right, as I’ve said before, and apparently need to keep repeating. You cannot randomly delete dependencies and expect things to work. There is no reason to delete the ffmpeg-for-homebridge package.

If you want to use a different version of FFmpeg, feel free to override it with videoProcessor.

**Comment by Sunoo** [comment]
Why?

**Comment by zokl** [comment]
I am using Openwrt cross-compilation building process. ffmpeg-for-homebridge download binary ffmpeg and compilation environment is not able to resolve libc and other static linked libraries into this binary.

The second issue is ffmpeg version. I am compiling on x86_64 for ARMv7. System download version for x86_64 instead of armv.

OpenWRT contains ffmpeg. It does not need external binary.

**Comment by Sunoo** [comment]
If that version of FFmpeg isn’t compiled with libfdk-aac (and it almost certainly isn’t), you won’t have audio support.

**Comment by Sunoo** [comment]
Unless ffmpeg is compiled against them, it won't matter. But that's besides the point.

You basically have four options:

1. Do what I've suggested, repeatedly. Don't randomly delete dependencies. Use `videoProcessor` to override the version of FFmpeg used. This is the only solution that is supported and that will do what you want reliably.
2. Install using the `--ignore-scripts` option to NPM to skip the ffmpeg-for-homebridge install script (and any other scripts). Unless you remember to use this every time you update this package, you'll eventually pull down a version of ffmpeg-for-homebridge.
3. Run `npm config set ignore-scripts true` to set NPM to never run scripts. This prevents you from pulling down ffmpeg-for-homebridge, but will likely cause issues installing other packages that use scripts.
4. Manually delete the ffmpeg binary from the ffmpeg-for-homebridge directory. The next time that package updates, it will redownload that binary.

Number one is the only method that I will be supporting. The other three are all bad ideas for various reasons. Your choice though, I suppose.

**Comment by zokl** [comment]
Ok, thank you.
