### ISSUE TITLE
Motion sensor active via another accessory

### ISSUE THREAD

**Issue by NikDevx** [Sunoo/homebridge-camera-ffmpeg#774]
Hi everyone!
It's possible to activate motion sensor or doorbell via another accessory?
I try to create doorbell with camera on click the button from esp8266

**Comment by Sunoo** [comment]
You can trigger them via [MQTT](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/mqtt.html) or [HTTP](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/http.html). If you want to trigger it with another HomeKit device, [you can do that too](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/switch.html).

**Comment by NikDevx** [comment]
> You can trigger them via [MQTT](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/mqtt.html) or [HTTP](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/http.html).


I tried this one via HTTP, but it doesn't work for me
My cam shows the stream via web and rtsp use port 80 and 8554
When I go **http://192.168.0.18/motion?Video%20DooreBell** I getting this one **Unable to access site Timeout for response from site 192.168.0.18 was exceeded.**

My config
```
"platforms": [{
		"platform": "Camera-ffmpeg",
		"port": 8080,
		"localhttp": true,
		"cameras": [{
			"name": "Домофон",
			"doorbell": true,
			"doorbellSwitch": true,
			"switches": true,
			"manufacturer": "ESP",
			"model": "ESP32 CAM",
			"serialNumber": "HAA-865800",
			"firmwareRevision": "1.0",
			"videoConfig": {
				"source": "-i rtsp://admin:admin@192.168.0.18:8554/mjpeg/1",
				"stillImageSource": "-i http://192.168.0.18/jpg",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 1080,
				"maxFPS": 30,
				"debug": true,
				"maxBitrate": 15000
			}
		}]
```

**Comment by Sunoo** [comment]
`port` should be `porthttp`, and you probably don’t want `localhttp`.

**Comment by NikDevx** [comment]
> `port` should be `porthttp`, and you probably don’t want `localhttp`.

Thanks a lot!
But I can use this one only on local running machine homebridge.
For my cam I use ip 192.168.0.18
My local machine ip on Mac 192.168.0.16
When i use get request http://192.168.0.16:8080/doorbell?Video - that's work for me.

What's wrong?

**Comment by Sunoo** [comment]
I’m sorry, I don’t believe I understand your question.

**Comment by NikDevx** [comment]
> I’m sorry, I don’t believe I understand your question.
Sorry ))

I'll try to explain you
I am using homebridge on my Mac and my Mac has ip 192.168.0.16
But my cam has ip 192.168.0.18
The doorbell works when I use the ip of my mac **curl -X GET -d 'doorbell?Video' http://192.168.0.16:8080**


```
"platform": "Camera-ffmpeg",
		"porthttp": 8080,
		"cameras": [{
			"name": "Video",
			"doorbell": true,
			"manufacturer": "ESP",
			"model": "ESP32 CAM",
			"serialNumber": "HAA-865800",
			"firmwareRevision": "1.0",
			"videoConfig": {
				"source": "-i rtsp://admin:admin@192.168.0.18:8554/mjpeg/1",
				"stillImageSource": "-i http://192.168.0.18/jpg",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 1080,
				"maxFPS": 30,
				"debug": true,
				"maxBitrate": 15000
			}
```

**Comment by Sunoo** [comment]
Sounds like it is working as expected.

**Comment by NikDevx** [comment]
> Sounds like it is working as expected.

I thought that if my camera has IP 192.168.0.18, then I should send a request to the IP camera **curl -X GET -d 'doorbell?Video' http://192.168.0.18:8080**  
Not to the ip of my macbook (homebridge server) **curl -X GET -d 'doorbell?Video' http://192.168.0.16:8080**

**Is it supposed to work this way?**

**Comment by Sunoo** [comment]
Yes, the HTTP server than handle triggering the doorbell and motion runs inside the Homebridge plugin, so you need to use the IP of whatever machine you run Homebridge on.

**Comment by NikDevx** [comment]
> Yes, the HTTP server than handle triggering the doorbell and motion runs inside the Homebridge plugin, so you need to use the IP of whatever machine you run Homebridge on.

Thank you very much!
Now I understand
