### ISSUE TITLE
moved my homebridge from pi to os x but cant get cameras to work

### ISSUE THREAD

**Issue by steveharris08** [Sunoo/homebridge-camera-ffmpeg#776]
**Describe The Problem:**
moved my homebridge from pi to os x but cant get cameras to work
i litterally copied my config over and everything works except for the cameras they just show as black screen with no response this camera is not responding . streams work in vlc no problem.. any advice would be appreciated

**Logs:**
[9/8/2020, 4:57:58 PM] [Camera-ffmpeg] [Alfresco] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT
[9/8/2020, 4:57:58 PM] [Camera-ffmpeg] [Front Door] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT

**Homebridge Config:**
 {
            "cameras": [
                {
                    "name": "Alfresco",
                    "videoConfig": {
                        "vcodec": "libx264",
                        "source": "-rtsp_transport tcp -re -i rtsp://Smartwire:Smartwire008@192.168.1.212",
                        "maxFPS": 25,
                        "maxHeight": 720,
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "stillImageSource": "-i http://Smartwire:Smartwire008@192.158.1.212/cgi-bin/snapshot.cgi?1"
                    }
                },
                {
                    "name": "Front Door",
                    "videoConfig": {
                        "vcodec": "libx264",
                        "source": "-rtsp_transport tcp -re -i rtsp://Smartwire:Smartwire008@192.168.1.178",
                        "maxFPS": 25,
                        "maxHeight": 720,
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "stillImageSource": "-i http://Smartwire:Smartwire008@192.168.1.178/cgi-bin/snapshot.cgi?1"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Comment by Sunoo** [comment]
Looks like FFmpeg isn’t on your system. When you installed this plugin on the new system, did you use `--unsafe-perm`?

**Comment by steveharris08** [comment]
yes i installed using --unsafe-perm

**Comment by Sunoo** [comment]
Something else is preventing the installation of FFmpeg then. What version of macOS are you running?

**Comment by toshibochan** [comment]
Share your config. vcodec is set to what?

**Comment by steveharris08** [comment]
Share your config. vcodec is set to what?

can you explain how? please

**Comment by steveharris08** [comment]
> Share your config. vcodec is set to what?



> It is extremely unlikely to be related to vcodec, your error shows that the ffmpeg binary is not being found.
> 
> So, again, what version of macOS are you running? The bundled version of FFmpeg only supports macOS 10.14 “Mojave” or later: https://github.com/homebridge/ffmpeg-for-homebridge#supported-platforms

I Have macOS 10.13.6

**Comment by Sunoo** [comment]
That’s the problem. If you want audio support, you’ll need to compile FFmpeg yourself with libfdk-aac. Otherwise you can download the official release of FFmpeg and set audio to false in your config.

**Comment by steveharris08** [comment]
> FFmpeg

> That’s the problem. If you want audio support, you’ll need to compile FFmpeg yourself with libfdk-aac. Otherwise you can download the official release of FFmpeg and set audio to false in your config.

not worried about audio, i thought i had downloaded and installed the official release of FFmpeg? can you please send me the link so i have the correct file to install. thanks

**Comment by Sunoo** [comment]
Looks like https://evermeet.cx/ffmpeg/ffmpeg-4.3.1.7z

If it’s not in your path, you’ll need to set the videoProcessor option in your config to be the full path to the binary.

**Comment by steveharris08** [comment]
> Looks like https://evermeet.cx/ffmpeg/ffmpeg-4.3.1.7z
> 
> If it’s not in your path, you’ll need to set the videoProcessor option in your config to be the full path to the binary.

thanks for your help. do you know the default full path to the binary?

**Comment by Sunoo** [comment]
No, it’s wherever you put it on your system.
