### ISSUE TITLE
Stream Desktop. Use gdigrab instead of rtsp stream as input.

### ISSUE THREAD

**Issue by gprsnlty** [Sunoo/homebridge-camera-ffmpeg#781]
**Is your feature request related to a problem? Please describe:**
I would like to stream my Desktop to Homekit to watch a backup process occasionally.

**Describe the solution you'd like:**
So I was thinking I can just replace the source part of your ffmpeg commands to 
for the video stream:  " -f gdigrab -framerate 30 -i desktop " and leave the transcoding and output part.
for the still Frame:  " -f gdigrab -t 1 -i desktop " and leave the formatting and output part.

These commands work with the ffmpeg version bundled with your plugin.
to screen capture a video: ffmpeg -f gdigrab -framerate 30 -i desktop output.mkv
to screen capture a still Frame: ffmpeg -f gdigrab -t 1 -i desktop -f mjpeg stillframe.png -y

I took a look at streamingDelegate.ts but I am a bit lost and can't find the ffmpeg command wich is called when a stream or a still Frame in Homekit is requested.

**Describe alternatives you've considered:**
At the moment I use Vlc to stream my desktop continuously to rtsp://localhost:port/ and everything works ok. 
I just don't like that I have to leave Vlc running continuously in the Background.

**Additional context:**
Im probably wildly simplifying this. Im just playing around for fun and don't know much about programming.
Im thankful for any little tips or help and don't want to waste your time.

I really like your plugin! 
Cheers Florian

**Comment by Sunoo** [comment]
If you set the source to the values you set, theoretically it should work. Keep in mind that depending on how you installed Homebridge, FFmpeg will most likely be running under the homebridge user account, which I’m not sure whether it would have permissions to grab the screen.

**Comment by gprsnlty** [comment]
tried it just now. worked. aaah of course haha thanks
Im running Homebridge on windows in a command prompt no permission issues here.
