### ISSUE TITLE
 No snapshot but stream works with Home App (Mac OS Catalina 10.15.6)

### ISSUE THREAD

**Issue by nov-** [Sunoo/homebridge-camera-ffmpeg#790]
**Describe The Problem:**
No snapshot but stream works with Home App on Mac OS. On iOS 13.4.1 snapshot and streams works pretty good, without any problem. Again: stream on Home App (on Mac OS) works good but not snapshots. On iOS works both.

**To Reproduce:**
Open Home App on MacOS with camera provided by current homebridge-camera-ffmpeg plugin

**Homebridge Config:**

```json
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera1",
                    "manufacturer": "Some Camera",
                    "serialNumber": "SomeCam1",
                    "firmwareRevision": "1.0",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@path:port",
                        "maxFPS": 0
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Screenshots:**
[Home App screenshot](https://api.monosnap.com/file/download?id=mg3KGoDR7qR5lmJOrzGNUEJ0JDe0oX)
![2020-09-16 23-27-20](https://user-images.githubusercontent.com/7754103/93389320-ac5ea500-f874-11ea-89c9-6684c3c03c9e.jpg)

**Environment:**

* **Node.js Version**: 12.18.3
* **NPM Version**: 6.14.6
* **Homebridge Version**: 1.2.2
* **Homebridge Camera FFmpeg Version**: 3.0.3
* **Homebridge Config UI X Plugin Version**: 4.27.1
* **Operating System**: Raspbian

Thank you, awesome plugin! 👍

**Comment by Sunoo** [comment]
Does it work if you wait for a bit? I’ve noticed that on macOS the first snapshot sometimes takes a bit longer than expected to appear.

**Comment by nov-** [comment]
> Does it work if you wait for a bit? I’ve noticed that on macOS the first snapshot sometimes takes a bit longer than expected to appear.

now it's working 👍 I just run Home app and leave my laptop. when I was back all work fine! thanks a lot! I thinks we can close this issue.

**Comment by Sunoo** [comment]
Great!
