### ISSUE TITLE
'Chime on Homepod' not working

### ISSUE THREAD

**Issue by jqnatividad** [Sunoo/homebridge-camera-ffmpeg#794]
**Describe The Problem:**
In IOS 14, if you go to Notifications on Homekit for a camera that has `doorbell` set to true, an additional option is shown - Chime on Homepod.

If you try to toggle it on for a camera setup using this plugin, it says 'Could not complete operation' 

![IMG_0328](https://user-images.githubusercontent.com/1980690/93482716-0475c580-f8ce-11ea-8719-8e30e34b1adf.png)

**To Reproduce:**

1. setup a camera with `doorbell = true`
2. go to Settings\Notification of the camera in Home.app.
3. try toggling on 'Chime on Homepod'

**Logs:**
No error shown on HOOBS log file. It appears to be something on the Homekit side...

**Comment by toshibochan** [comment]
iOS 14 on HomePod is not out yet.

**Comment by jqnatividad** [comment]
Just installed the 14.2 beta profile on my paired Homepods.  Can confirm that it now works.
