### ISSUE TITLE
Sercomm OC810 working config

### ISSUE THREAD

**Issue by cinsu** [Sunoo/homebridge-camera-ffmpeg#797]
**Manufacturer/Model:**

Sercomm OC810
**Homebridge Config:**

```json
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera",
                    "motion": true,
                    "videoConfig": {
                        "source": "-i rtsp://administrator@[ip]:1025/img/media.sav",
                        "stillImageSource": "http://administrator@[ip]/img/snapshot.cgi",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 15,
                        "audio": true
}
```

**Additional Information:**

Default video size is 320x240 which I’ve increased. There are reports some Sercomm models support 720 with a hidden api call but that did not work for this model. I’ve been testing the ffmpeg audio return without success. The parameter is http://[ip]/img/g711a.cgi

**Comment by Sunoo** [comment]
The two-way stuff is still very much a work in progress, in the current implementation you’d likely need to include information as to which codec to use and such as well. Eventually I do plan to make it somewhat easier, but I haven’t quite figured that all out yet.

That said, I’ll get this added to the site shortly.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Sercomm-OC810.html
