### ISSUE TITLE
modified copy for WyzeCamV2

### ISSUE THREAD

**Issue by MattsthomeK** [Sunoo/homebridge-camera-ffmpeg#799]
Wyze CamV2 

{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Wyze Cam",
                    "videoConfig": {
                        "source": "-i rtsp://username:password@192.168.1.x/live",
                        "stillImageSource": "-i rtsp://username:password@192.168.1.x/live -vframes 1 -r 1",
                        "vcodec": "copy",
                        "encoderOptions": ""
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }

```json
{
    "bridge": {
        "name": "Homebridge ****",
        "username": "---------------",
        "port": 51043,
        "pin": "***-**-***"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "red",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                "192.168.1.x"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "sensors": false,
            "users": {
                "Hue user key"
            },
            "wallSwitch": true,
            "platform": "Hue"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "user@gmail.com",
                "password": "******",
                "countryCode": "1",
                "platform": "tuya"
            },
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Camera FFmpeg",
            "videoProcessor": "/Users/username/Library/ffmpg/ffmpeg-4.1-macos64-static/bin/ffmpeg",
            "cameras": [
                {
                    "name": "Crate Cam",
                    "videoConfig": {
                        "source": "-i rtsp://username:password@192.168.1.x/live",
                        "stillImageSource": "-i rtsp://username:password@192.168.1.x/live -vframes 1 -r 1",
                        "vcodec": "copy",
                        "encoderOptions": ""
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}
```

**Additional Information:**
had to add the blank line to override the default filters otherwise it would error out and fail to spawn

**Comment by Sunoo** [comment]
I’ll get this added shortly, but are you sure encoderOptions needed to be set blank? If so, I’ll have to go look for the bug in my code, as it should be defaulting to blank when not using the default libx264 vcodec.

**Comment by MattsthomeK** [comment]
sorry to say I am not as sure as I was an hour ago. I went to remove the line just now and verify and found the line is now removed on its own and still working. sorry for the false alarm. wish I could say what fixed it

**Comment by Sunoo** [comment]
Darn. I’ll take a look later and see if I can see a condition where this wouldn’t work as I expect.

**Comment by MattsthomeK** [comment]
in looking at my logs I think my issue is with my version of ffmpeg and the aac encoder

**Comment by Sunoo** [comment]
Does the packaged version of FFmpeg not work for you? That version is compiled with support for the needed codecs.

**Comment by MattsthomeK** [comment]
sorry I am very new to this, it didn't want function at all without a path to ffmpeg so I installed the current stable and directed it to that folder

maybe this has been my issue all along?

**Comment by MattsthomeK** [comment]
FYI I am running on a macosX 10.12

**Comment by Sunoo** [comment]
That’s why. The packages version of FFmpeg requires macOS 10.14 or newer. You can try to compile your own version of FFmpeg with libfdk-aac, or you can use the stable version and disable audio.

**Comment by MattsthomeK** [comment]
Ahh that makes sense. Thanks for the help!
