### ISSUE TITLE
No sound if using audio codec AAC (ffmpeg native) or LIBOPUS

### ISSUE THREAD

**Issue by alexwala** [Sunoo/homebridge-camera-ffmpeg#807]
**Describe The Problem:**
As the stock ffmpeg has libfdk_aac disabled (yes i know [ffmpeg for homebridge](https://github.com/homebridge/ffmpeg-for-homebridge) - which works fine), i tried to use a different audio codec: AAC or LIBOPUS.
If opening the camera live view on an ios device, i see that the audio stream is working (homebridge log files) but there is no sound on the device. I can hear the sound only when switching to libfdk_aac.
Afaik the native aac encoder is a AAC-LC. Does homekit only works with aac eld or do i have to change anything else ?

**To Reproduce:**
in streamingDelegate.ts (line 336) set:

' -codec:a libfdk_aac'
to
' -codec:a aac'
or
' -codec:a libopus'

**Environment:**
* **Node.js Version**: v12.18.4
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Homebridge Camera FFmpeg Version**: v3.0.3
* **Homebridge Config UI X Plugin Version**: v4.27.1
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
Older versions of this plugin had that configurable, however libfdk-aac is the only one that works reliably. This is basically the reason why ffmpeg-for-homebridge even exists, if we could have gotten one of the stock FFmpeg codecs to work, it would be easier for everyone.

**Comment by alexwala** [comment]
Thanks for clarification. In the meantime i adapted ffmpeg-for-homebridge enabling libpulse to use with homebridge, alexa and google assistant.
