### ISSUE TITLE
Camera is showing no stream

### ISSUE THREAD

**Issue by MBj1703** [Sunoo/homebridge-camera-ffmpeg#811]
I'm running Homebridge 1.2.3 with plugin homebridge-camera-ffmpeg v3.0.3

Two camera added, one is working, the second not.

Homebridge log it saying:
[9/25/2020, 6:14:50 PM] [Camera FFmpeg] [Gartentor] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[9/25/2020, 6:14:50 PM] [Camera FFmpeg] [Gartentor] FFmpeg exited with code: 1 and signal: null (Error)
[9/25/2020, 6:14:50 PM] [Camera FFmpeg] [Gartentor] Stopped video stream.

If I open the stream in VLC, it is working.
Also I have motioneye installed. Working there as well.

Config is mostly default:
 {
                    "name": "Gartentor",
                    "videoConfig": {
                        "source": "-i rtsp://192.168.0.105/live/ch0:554",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true
                    }

Thanks
Markus

**Comment by mtressl** [comment]
I think your "source"-line should read as follows:
`"source": "-i rtsp://192.168.0.105:554/live/ch0",`

The port must directly follow the IP address.

Cheers, Markus

**Comment by MBj1703** [comment]
No, port is not needed if standard.
Needed to add more parameters: -rtsp_transport tcp -i

**Comment by MBj1703** [comment]
Fixed
