### ISSUE TITLE
EzViz C3 Husky

### ISSUE THREAD

**Issue by Careless2000** [Sunoo/homebridge-camera-ffmpeg#819]
**Manufacturer/Model:**
EzViz C3 Husky

**Homebridge Config:**

"videoConfig": {
                        "source": "-vcodec h264 -i rtsp://admin:******@192.x.x.x/Streaming/Channels/1",
                        "stillImageSource": "-i rtsp://admin:*****@192.x.x.x/Streaming/Channels/1/picture",
                        "vcodec": "copy",
                        "audio": true,
                        "maxFPS": 30,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "videoFilter": "none",
                        "maxBitrate": 1024,
                        "packetSize": 188,
                        "maxStreams": 2,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0 -loglevel verbose",
                        "debug": true
                    }
**Additional Information:**

**Comment by ValadAmoleo** [comment]
These settings also work for the CTQ3W

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/EzViz-C3-Husky.html
