### ISSUE TITLE
Duplicate Name with plug in Alexa

### ISSUE THREAD

**Issue by giannimp** [Sunoo/homebridge-camera-ffmpeg#827]
when motion sensor are enabled switches and door bell:
 "name": "Fuori porta",
        "motion": false,
        "switches": true,
        "doorbell": true,
Plug in Alexa show this warning:
7/10/2020, 11:50:07 [Alexa] WARNING: Duplicate device name Balcone Cucina
7/10/2020, 11:50:07 [Alexa] WARNING: Duplicate device name Balcone Camera
7/10/2020, 11:50:07 [Alexa] WARNING: Duplicate device name Balcone Ciro

can you also customize the names of motion, switches and doorbell ??
sorry for my english
thank you

**Comment by Sunoo** [comment]
I'll take a look at the code in a minute, but I'm pretty sure it should have unique names already.

**Comment by NorthernMan54** [comment]
@giannimp I believe this is resolved in the latest release of homebridge-alexa
