### ISSUE TITLE
Recording on Motion Detection

### ISSUE THREAD

**Issue by jcbshw** [Sunoo/homebridge-camera-ffmpeg#830]
I have a Wyze Cam V2 running dafang hacks. I was previously using homebridge-dafang but was having issues with camera quality/ffmpeg so I moved back to this plugin. It had a feature that exposed a switch to record the rstp stream to my homebridge server. I had an automation setup that would record for a predetermined time on motion detection.

Is it possible to add recording capabilities to this plugin?

**Comment by Sunoo** [comment]
It is possible to do, but I don’t have any plans to add that. The ability to trigger a recording on the camera is already in place though.

**Comment by ThiagoFacchini** [comment]
Hi @Sunoo you just mentioned it is possible to record.

In my case I have some ESP32Cams with motion sensors sending MQTT messages to homebridge when movement is detected and I would like to record this footage on my hard drive when it happens.

So the question is: How do I achieve it?

Thanks!
