### ISSUE TITLE
Alternative URL for still picture if camera is not reachable

### ISSUE THREAD

**Issue by Tobias007** [Sunoo/homebridge-camera-ffmpeg#831]
**Describe the solution you'd like:**

I have implemented several cameras with the still-picture and stream URLs. Both work fine if camera is switched on and working. However - if there is an issue with the camera or I want to switch it off at certain times of the day to save energy the HomeKit app is usually showing no picture or a very old one. 

Additionally I save pictures every hour on a separate server (I switch all the cameras automatically on, save the pictures, and then switch the cameras off again. 

It would be excellent, if ffmpeg could detect, that if there is no picture coming from the switched off camera and then instead taking the last picture saved on the server.

Parameter could be like: "stillImageSourceAlternative": "/opt/saved_images/still_image.jpg",

**Comment by Sunoo** [comment]
This feels like a solution that would be very specific to your setup, so I’m not sure it would make sense to add to the main plugin.

In my mind, the best way to handle this would be for you to point StillImageSource at a proxy you control, and that could handle attempting to pull the still from the camera, or reverting to the secondary location if that fails.

**Comment by Tobias007** [comment]
Yep, you are right - maybe it is a very specific request for my scenario only.

I found a solution (maybe it helps if someone wants to use it:

insert in the file streamingDelegate.js  after handleSnapshotRequest(request, callback) { 
the following code:

`    const isReachable = require('is-reachable');

    if (this.videoConfig.checkReachable == true)
    {
        if (this.videoConfig.reachable == false)
        { this.videoConfig.stillImageSource = '-i ' + this.videoConfig.stillImageSource2;
        } else
        { this.videoConfig.stillImageSource = '-i ' + this.videoConfig.stillImageSource1;
        };

        (async () => { this.videoConfig.reachable = await isReachable(this.videoConfig.stillImageSource1); })();
    };

`

then define following new parameters in the camera definition:

                        "checkReachable": true,
                        "stillImageSource1": "http://192.168.1.1/jpg",
                        "stillImageSource2": "/opt/test/Sunflower_from_Silesia2.jpg",

**Comment by Sunoo** [comment]
I’d still think some sort of proxy would work a bit better for you, as you wouldn’t need to update every version that comes out, but as long as you have something that works for you, that’s what matters.

**Comment by Tobias007** [comment]
You are right - but I didn't had a starting point how to set up a proxy - so I thought it is easier to adapt the code directly. 

But really thanks for your help and for your excellent module!
