### ISSUE TITLE
Getting the stream faster

### ISSUE THREAD

**Issue by mihailescu2m** [Sunoo/homebridge-camera-ffmpeg#839]
Using the plugin with a TpLink C200 camera here (also configured in my Synology), and vcodec="copy" (not that it matters)

Compared to the TpLink app (Tapo) and even to the Synology app (DS Cam), the feed in the Home app is much slower to start. From what I see, in the camera app the stream starts playing after 2-3 seconds, and similarly in DS Cam.

With Homebridge, it takes 6-10 seconds to get the live feed: roughly 4-6 seconds until I get the "Starting video stream" message in the Homebridge log, then 3-4 seconds after that to receive the stream.

Is this just me, or is the Homekit protocol more cumbersome and it's slower to establish connections? Any hints to make this more responsive?

PS: Once the live feed starts, there isn't any issue, it keeps going nice and fast. It's just getting it live that shows too much of the spinning wheel.

**Comment by mrMiimo** [comment]
same here....

**Comment by Sunoo** [comment]
So HomeKit seems to be picky, especially with regard to the copy vcodec. My experience is that if you re-encode (especially with the default libx264) the stream will start faster, even if you use a high bitrate.

As far as I’ve been able to find, I have no control over anything that would speed that up.

**Comment by kontur11** [comment]
The more fps set on the camera, the faster it will start. On my Synology starts 1-2 seconds.
