### ISSUE TITLE
Vivint Doorbell Camera Pro

### ISSUE THREAD

**Issue by Error404UNF** [Sunoo/homebridge-camera-ffmpeg#840]
**Manufacturer/Model:**
Vivint Doorbell Camera Pro

**Homebridge Config:**

```json
"name": "Doorbell",
                    "manufacturer": "VIVINT",
                    "model": "DBC300",
                    "motion": true,
                    "doorbell": true,
                    "motionTimeout": 1,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:XYXYXYXYXYXYXYXYXYXYXYX@10.10.10.10:0000/Video-00",
                        "vcodec": "copy",
                        "audio": true
```

**Additional Information:**
2 way audio not included due to WIP state. Ensure you have "showCameraConfig": true in the Vivint platform in config.json, copy the Config from the log in the Homebridge Log, paste into the "source" in the Config. Optional videoConfig Parameters can go anywhere after "source".

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Vivint-Doorbell-Camera-Pro.html
