### ISSUE TITLE
2n HeliosIP

### ISSUE THREAD

**Issue by hihipto** [Sunoo/homebridge-camera-ffmpeg#842]
**Manufacturer/Model:**
2n HeliosIP

**Homebridge Config:**

```json
        {
            "name": "Camera FFmpeg",
            "porthttp": 5555,
            "cameras": [
                {
                    "name": "Doorbell",
                    "manufacturer": "2n",
                    "model": "HeliosIP",
                    "serialNumber": "1234",
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-i rtsp://IPaddress:554/h264_stream",
                        "stillImageSource": "-i http://IPaddress/enu/camera640x480.jpg",
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxBitrate": 512,
                        "forceMax": true,
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Additional Information:**
Automation is required to enable the doorbell function:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/5295141/96009114-8e1ea180-0e40-11eb-986f-559e9f783152.png">

Not sure "Enhanced Video License" is required for streaming video:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/5295141/96009267-c0300380-0e40-11eb-806d-2c9d1ca11a2c.png">

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/2n-HeliosIP.html
