### ISSUE TITLE
Techage 2MP PoE Cameras

### ISSUE THREAD

**Issue by ashtonaut** [Sunoo/homebridge-camera-ffmpeg#857]
**Manufacturer/Model:**

Techage 2MP PoE NVR kit.

Cheap and very reliable across multiple installs with Homebridge running on Raspberry Pi 3B and 4.

Purchased from official Techage store on AliExpress.

[Link](https://star.aliexpress.com/share/share.htm?image=U4560a6731267453a9d910c46dc8d76d18.jpg&businessType=ProductDetail&title=NZ%24%20182.49%20%2026%EF%BC%85%20Off%20%7C%20H.265%20POE%20Security%20Camera%20System%204CH%201080P%20NVR%20Kit%202.0MP%20Audio%20Microphone%20CCTV%20Grey%20IP%20Camera%20IR%20Outdoor%20Video%20Surveillance%20Set&platform=AE&redirectUrl=https%3A%2F%2Fwww.aliexpress.com%2Fitem%2F32989530341.html%3F%26srcSns%3Dsns_Copy%26tid%3Dwhite_backgroup_101%26mb%3DZRnGKokBpR7GoKx%26businessType%3DProductDetail%26spreadType%3DsocialShare)

I have only tested the 2MP H264 (older) and H265 (newer) PoE cameras (grey cylindrical body). I haven’t tested wifi cameras or the 5MP cameras. One way audio works.

**Homebridge Config:**

Partial config showing camera info:

```json
"name": "Camera Name",
"motion": true,
"switches": true,
"videoConfig": {
	"source": "-rtsp_transport tcp -re -i rtsp://<cameraip>:554/user=admin&password=&channel=1&stream=0.sdp",
	"stillImageSource": "-i http://<cameraip>/webcapture.jpg?command=snap&channel=0",
	"audio": true
}
```

**Additional Information:**

- These cameras can upload snapshots on motion detect directly to a FTP server. I’ve used vsftp as the FTP server on the Pi.
- To set up, log into the cameras directly using their IP address (you need to use an old version of Internet Explorer, user “admin”, no password) and set up the FTP snapshot location. Then enable FTP upload on motion trigger for each camera.
- Use a plugin like homebridge-filesensor to watch the folder and trigger motion when a new snapshot is uploaded.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Techage-2MP-PoE-NVR.html
