### ISSUE TITLE
August Doorbell Cam Pro

### ISSUE THREAD

**Issue by jlg89** [Sunoo/homebridge-camera-ffmpeg#874]
**Manufacturer/Model:**
August Doorbell Cam Pro

**Homebridge Config:**

```
    {
        "name": "DoorbellCam",
        "manufacturer": "August Home",
        "model": "Doorbell Cam Pro",
        "serialNumber": “ABCD12345",
        "motion": true,
        "motionTimeout": 15,
        "videoConfig": {
            "source": "-i rtsp://admin:admin@192.168.0.10/live/stream",
            "stillImageSource": "-i rtsp://admin:admin@192.168.0.10/live/stream -vframes 1 -r 1",
            "maxStreams": 2,
            "maxWidth": 480,
            "maxHeight": 640,
            "maxFPS": 10,
            "audio": true,
            "debug": false
        }
    },
```

**Additional Information:**
Included below is a writeup on configuring an RPi with Motion to monitor the RTSP stream from an August Doorbell Cam and generate MQTT motion events in homebridge-camera-ffmpeg.

**Comment by jlg89** [comment]
The August doorbell cameras are really slick, but they don’t support HomeKit at all, and their API is not made public. The August app alerts you when motion is detected or the doorbell is rung, and there are some integrations with Google and Amazon, but there’s no HomeKit integration at all. It’s a bit pathetic, really.

Doorbell-button events can be obtained (from the wired versions of August doorbell cams, at least) by using the doorbell wiring to trigger an input on something like a Sonoff SV with RavenSystem/esp-homekit-devices firmware, or a Raspberry Pi, but video motion events require a software solution. Thankfully, August saw fit to enable a basic RTSP video stream from their doorbell cameras. We can monitor that video stream, at a very low frame rate to keep network traffic to a minimum, detect motion using a lightweight video monitoring application, and send motion events to homebridge via MQTT.

This is not for the faint of heart. It requires the ability to use command-line UNIX tools, navigate the filesystem, edit configuration files, and more. It is neither point-and-click nor plug-and-play. If that doesn’t scare you, then carry on.

If you haven’t already, get setup with Homebridge, preferably on a dedicated Raspberry Pi. Install the homebridge-camera-ffmpeg plugin and get your August doorbell cam configured and working there. As part of this setup, you’ll want to be sure to assign a dedicated IP address to the doorbell with your local DHCP server (probably your Internet router).

Make sure the homebridge-camera-ffmpeg configuration for the doorbell cam looks something like the following, inserting your doorbell cam's actual serial number, IP address, etc. in their respective spots:

<pre>
    {
        "name": "DoorbellCam",
        "manufacturer": "August Home",
        "model": "Doorbell Cam Pro",
        "serialNumber": “ABCD12345",
        "motion": true,
        "motionTimeout": 15,
        "videoConfig": {
            "source": "-i rtsp://admin:admin@192.168.0.10/live/stream",
            "stillImageSource": "-i rtsp://admin:admin@192.168.0.10/live/stream -vframes 1 -r 1",
            "maxStreams": 2,
            "maxWidth": 480,
            "maxHeight": 640,
            "maxFPS": 10,
            "audio": true,
            "debug": false
        }
    },
</pre>

You’ll also need an MQTT broker & client:

<pre># sudo apt-get install mosquitto mosquitto-clients</pre>

Edit /etc/mosquitto/mosquitto.conf and set “allow_anonymous true” unless you want to force authentication, in which case you’ll have to dig up that configuration magic yourself. Add your MQTT config to homebridge-camera-ffmpeg per instructions at https://sunoo.github.io/homebridge-camera-ffmpeg/automation/mqtt.html

The lightweight video stream monitoring app is called “Motion”:

<pre># sudo apt-get install motion</pre>

Edit /etc/motion/motion.conf. Find these parameters and set them accordingly, inserting your doorbell cam’s IP in the netcam_url string (everything else should be fine at defaults):

<pre>
width 480
height 640
netcam_url rtsp://192.168.0.10/live/stream
netcam_userpass admin:admin
netcam_keepalive on
stream_localhost off
on_motion_detected /etc/motion/motion_detected.sh
</pre>

This is a very basic no-frills configuration that will monitor your doorbell cam video at 2 fps and run the “motion_detected.sh” shell script when the motion daemon detects motion. For more information on motion and its configuration, visit https://motion-project.github.io .

To enable motion as a system service (taken from https://raspberrypi.stackexchange.com/questions/41342/how-to-start-motion-in-daemon-mode-on-rpi-running-raspbian-jessie):

Edit /etc/default/motion and set “start_motion_daemon=yes”

<pre># sudo systemctl enable motion</pre>

Now we need set up the script that Motion will use to trigger camera motion events from the command line. There are multiple ways to do this; the method I chose was taken from https://www.ev3dev.org/docs/tutorials/sending-and-receiving-messages-with-mqtt/ and requires a Python module, paho-mqtt:

<pre># sudo pip3 install paho-mqtt</pre>

Edit /etc/motion/motion_detected.sh and set its contents to the script below, with the following changes:

1. Set “your-mqtt-topic” to the MQTT Topic value in your homebridge-camera-ffmpeg configuration.
2. Set “DoorbellCam” to the “name” value of your doorbell cam in the homebridge-camera-ffmpeg configuration.

<pre>
#!/usr/bin/env python3
import paho.mqtt.client as mqtt
# This is the Publisher
client = mqtt.Client()
client.connect("localhost",1883,60)
client.publish(“your-mqtt-topic/motion", “DoorbellCam");
client.disconnect();
</pre>

Set permissions on the file:

<pre># sudo chmod 755 /etc/motion/motion_detected.sh</pre>

You can execute the file directly and make sure it triggers a motion event in HomeKit:

<pre># sudo /etc/motion/motion_detected.sh</pre>

Reboot your RPi, and you should start automatically receiving doorbell camera motion events in HomeKit.

**Comment by Sunoo** [comment]
Interesting. I may see about putting the instructions for Motion somewhere else, since it seems like it would be fairly applicable to any camera.

**Comment by jlg89** [comment]
I'm running a request up the tech support food chain at August, trying to get some kind of detail on their RTSP implementation. There are all sorts of different URLs you can hit that all seem to return the same audio/video stream (see https://www.ispyconnect.com/man.aspx?n=August), and I want to see if there are really any differences in terms of performance, CPU load on the doorbell itself, etc.

**Comment by Sunoo** [comment]
Good luck, I’ve had a real hard time getting technical information from any customer service department. Fingers crossed that things work out better for you.

**Comment by macjl** [comment]
Hello,

Thank you for your instructions with motion. It inspired me to do same thing with v4l2 camera.

The instructions are pretty the same, except that I had to use two v4l2loopback devices and ffmpeg to duplicate the camera stream : one for homebridge-camera-ffmpeg, and one for motion. The good point by doing that, is the camera has always an stream for motion detection. And then, the Homekit visualisation is really really fast! Faster than any official Homekit camera I already have!

@Sunoo, if you want, I can make a quick guide for those who are interested in doing that. I did all that within Docker Containers (one container for v4l2loopback stram cloning with ffmpeg, one for Motion and one for Homebridge-camera-ffmpeg).

**Comment by jlg89** [comment]
Me: I'm mainly interested in how the Doorbell Cam handles multiple simultaneous RTSP streams, from a CPU standpoint. IOW if I have two devices accessing the RTSP stream, is it better to have one using /stream0 and the other /stream1 or is it really no different than both of them using /stream ?

August Support: We escalated this question to our upper management department, and we receive your response. Our Doorbell Cam does not have a camera-side CPU advantage, and we can not ensure you that either stream will be usable for you.

**Comment by jlg89** [comment]
My Doorbell Cam seems to be relatively unstable with the Motion setup, I'm having to reboot it with the August app daily. So macjl's solution, or something like it, may be a better option. I know Motion can be configured to run a low frame rate for motion detection, and then increase the frame rate when motion is detected. I'm playing with the Motion and homebridge-camera-ffmpeg configs to see if I can reduce the load on the Doorbell Cam. So far, I've been able to change the snapshot source from the rtsp stream to "http://localhost:8081" which grabs the current frame from Motion's jpeg output. That output doesn't include audio, but there are other ways to get video output from Motion.

**Comment by jlg89** [comment]
How do I specify an mjpeg input stream for homebridge-camera-ffmpeg? Right now I have it as follows, and snapshots work fine but the stream fails with the log output below.

<pre>
       "videoConfig": {
            "source": "-f mjpeg -i http://localhost:8081",
            "stillImageSource": "-i http://localhost:8081",
            "maxStreams": 2,
            "maxWidth": 480,
            "maxHeight": 640,
            "maxFPS": 10,
            "audio": true,
            "debug": true
        }
</pre>


<pre>
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] Video stream requested: 1280 x 720, 30 fps, 299 kbps
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] Starting video stream: 480 x 640, 10 fps, 299 kbps
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] Stream command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -f mjpeg -i http://localhost:8081 -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 10 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(480,iw)':'min(640,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 14072822 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 8W4XmQ+6hJrhElG30EI06p55ZkgPKaup16azR7nO srtp://192.168.77.237:51025?rtcpport=51025&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 3134797 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params UWnnov7kthgxMnzo4KqGJxpJ/p5DNLLm3fSVGPex srtp://192.168.77.237:53909?rtcpport=53909&pkt_size=188 -loglevel level+verbose
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libavutil      56. 51.100 / 56. 51.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libavcodec     58. 91.100 / 58. 91.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libavformat    58. 45.100 / 58. 45.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libavdevice    58. 10.100 / 58. 10.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libavfilter     7. 85.100 /  7. 85.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libswscale      5.  7.100 /  5.  7.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libswresample   3.  7.100 /  3.  7.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [info]   libpostproc    55.  7.100 / 55.  7.100
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] 
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [tcp @ 0x3c24d60] [verbose] Starting connection attempt to ::1 port 8081
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] 
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [tcp @ 0x3c24d60] [verbose] Connection attempt to ::1 port 8081 failed: Connection refused
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [tcp @ 0x3c24d60] [verbose] Starting connection attempt to 127.0.0.1 port 8081
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] 
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] [tcp @ 0x3c24d60] [verbose] Successfully connected to 127.0.0.1 port 8081
11/5/2020, 12:32:10 PM [Camera FFmpeg] [DoorbellCam] 
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [info] Input #0, mjpeg, from 'http://localhost:8081':
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [info]   Duration: N/A, bitrate: N/A
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [info]     Stream #0:0: Video: mjpeg (Baseline), 1 reference frame, yuvj420p(pc, bt470bg/unknown/unknown, center), 480x640 [SAR 1:1 DAR 3:4], 25 tbr, 1200k tbn, 25 tbc
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [info] Output #1, rtp, to 'srtp://192.168.77.237:53909?rtcpport=53909&pkt_size=188':
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [error] Output file #1 does not contain any stream
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [AVIOContext @ 0x3c66ad0] [verbose] Statistics: 0 seeks, 0 writeouts
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] [AVIOContext @ 0x3c25b80] [verbose] Statistics: 60249 bytes read, 0 seeks
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] 
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] FFmpeg exited with code: 1 and signal: null (Error)
11/5/2020, 12:32:11 PM [Camera FFmpeg] [DoorbellCam] Stopped video stream.
</pre>

**Comment by jlg89** [comment]
It's because I forgot to disable audio, so FFmpeg was looking for an audio stream that wasn't there.

This config doesn't include audio, but -- with the Motion config above -- it puts the least possible network load on the Doorbell Cam. Snapshots and video for HomeKit always use the Motion output. When no motion is being detected, video frame rate is 1 fps. When motion is detected, it goes to 10 fps.

<pre>
    {
        "name": "DoorbellCam",
        "manufacturer": "August Home",
        "model": "Doorbell Cam Pro",
        "serialNumber": "XXXXXXXXXX",
        "motion": true,
        "motionTimeout": 15,
        "videoConfig": {
            "source": "-i http://127.0.0.1:8081",
            "stillImageSource": "-i http://127.0.0.1:8081",
            "maxStreams": 2,
            "maxWidth": 480,
            "maxHeight": 640,
            "maxFPS": 10,
            "audio": false,
            "debug": false
        }
    },
</pre>

Interestingly, you can pull an audio-only stream from the Doorbell Cam and have FFmpeg mix it into the output stream, but it doesn't seem to work very well. I'm sure it could be tuned somehow:

<pre>
            "source": "-i http://127.0.0.1:8081 -i rtsp://admin:admin@192.168.77.7/stream2",
</pre>

**Comment by jlg89** [comment]
@macjl, Motion appears to work well with v4l2, and can mirror its video input to a v4l2 device. I haven't tried piping video from an RTSP stream that way, primarily because I can't seem to get v4l2loopback-dkms to install, but it looks like it should work.

**Comment by jlg89** [comment]
Oh, yes. Once v4l2loopback is working, set "video_pipe /dev/video0" in /etc/motion/motion.conf, and then set the camera's source in homebridge-camera-ffmpeg as follows:

<pre>
    {
        "name": "DoorbellCam",
        "manufacturer": "August Home",
        "model": "Doorbell Cam Pro",
        "serialNumber": "XXXXXXXXXX",
        "motion": true,
        "motionTimeout": 15,
        "videoConfig": {
            "source": "-f video4linux2 -i /dev/video0",
            "stillImageSource": "-i http://127.0.0.1:8081",
            "maxStreams": 2,
            "maxWidth": 480,
            "maxHeight": 640,
            "maxFPS": 10,
            "audio": false,
            "debug": false
        }
    },
</pre>

This gives smooth video, at the "framerate" setting in /etc/motion/motion.conf--much smoother than pulling the mjpeg stream, and with very fast response time in the Home app as @macjl mentioned. I've been running the Doorbell Cam for several days now with this basic config, and it hasn't needed a reboot.

**Comment by glassman81** [comment]
> This gives smooth video, at the "framerate" setting in /etc/motion/motion.conf--much smoother than pulling the mjpeg stream, and with very fast response time in the Home app as @macjl mentioned. I've been running the Doorbell Cam for several days now with this basic config, and it hasn't needed a reboot.

Hey there. Thank you for all your work. I was wondering if you might be able to provide a quick guide  using v412 instead of mqtt? It would really help the inexperienced folks out there, such as myself.

**Comment by jlg89** [comment]
> Hey there. Thank you for all your work. I was wondering if you might be able to provide a quick guide using v412 instead of mqtt? It would really help the inexperienced folks out there, such as myself.

v4l2 (video4linux2) and MQTT do two different things. In my config:

The motion app pulls video from the doorbell camera, monitors the video stream to detect motion events, and sends notifications to homebridge using MQTT. At the same time, it pipes the video stream to a virtual video device created by video4linux2, which provides a local stream for the homebridge-camera-ffmpeg plugin.

It's a convoluted setup, and is only necessary because 1) August doesn't provide motion-detection events to homebridge or HomeKit, 2) August only--somewhat begrudgingly--provides a basic RTSP stream for third-party access, 3) The August hardware can't reliably support more than one stream at a time.

I have realized that you might as well set the motion-detect framerate for the motion stream at 10fps, as the network traffic and hardware load isn't really any different for that vs. 1-2fps, and the quality is obviously better.

**Comment by Sunoo** [comment]
I'll almost certainly rewrite it a bit in the future, but for now I just copied your write-up to the Automation section of the web page.

Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/August-Doorbell-Cam-Pro.html
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/automation/motion.html
