### ISSUE TITLE
MQTT: Camera do not support different topics for activating motion and resetting motion

### ISSUE THREAD

**Issue by MichlW** [Sunoo/homebridge-camera-ffmpeg#877]
Hey guys

I use Yi Outdoor 1080p Camera with alternative yi-hack-v4 firmware that adds several features including MQTT for motion detection.

My problem is that the implementation do not support different topics for activating and resetting motion as homebridge-camera-ffmpeg needs it. I just can enter one topic and two different activation and reset motion messages as shown in the Screenshot below.

![image](https://user-images.githubusercontent.com/49558935/98292076-638db780-1fac-11eb-84e0-1ab9657de6ee.png)

If it is configured as in the screenshot the motion detection works well.
But I do not have had any idea how to re-publish the message `homebridge/motion Haustuer_MotionStop` as `homebridge/motion/reset Haustuer` to allow resetting the motion by the camera.

Any ideas how I can workaround this?

Thanks in advance.
Michael

**Comment by Sunoo** [comment]
I’m gonna have to give this some thought. I handled this for Dafang Hacks cameras by writing another plugin to handle republishing, but I’d rather not have to force people to do that for every single camera that can publish to MQTT.

Easiest short term workaround would be to ignore the camera’s motion stop alerts and just set a motion timeout in this plugin’s config, since it is typically the motion start that matters more anyways.

I will try to figure out a good way to handle this though.

**Comment by MichlW** [comment]
This is how i actually handle it in a shell script to republish messages in homebridge-camera-ffmpeg specific topic/message format:

Camera topic: `camera/motion`
Message if motion is detected: `Haustuer_MotionDetected`
Message if motion is resetted: `Haustuer_MotionReset`

```
while true; do
        mosquitto_sub -t "camera/motion" | while read -r line; do
                case $line in
                "Haustuer_MotionDetected")
                        mosquitto_pub -t "homebridge/motion" -m "Haustuer"
                ;;
                "Haustuer_MotionReset")
                        mosquitto_pub -t "homebridge/motion/reset" -m "Haustuer"
                ;;
                esac
        done
        sleep 15
done
```

Outer while is when connection to MQTT broker is disconnected.

But it would be smoother if I could enter custom topics and messages per camera and per state in plugin configuration.

**Comment by Sunoo** [comment]
Yea, I just need to figure out a good way to handle it, without breaking existing users.

**Comment by MichlW** [comment]
The existing (hardcoded) topic and message combination could be the default configuration for custom fields, especially after upgrading the plugin.

That should prevent breaking existing users configuration.

**Comment by Sunoo** [comment]
MQTT was completely reworked in 3.1.0 and now supports these scenarios.
