### ISSUE TITLE
FFMPEG exit with code 1 when audio is enabled

### ISSUE THREAD

**Issue by HJ2k** [Sunoo/homebridge-camera-ffmpeg#893]
**Describe The Problem:**

Error only appears when enabling audio on cameras but goes way when audio disabled again.
**To Reproduce:**

enable audio
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Entrance Cam",
                    "motion": false,
                    "videoConfig": {
                        "source": "-i rtsp://user1:password@10.0.1.33:554/videoMain",
                        "audio": true,
                        "debug": true
                    }
                },
                {
                    "name": "DoorBell Cam",
                    "motion": true,
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-i rtsp://admin:user1:password@10.0.1.16:554/Streaming/Channels/101",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 12,
                        "maxBitrate": 300,
                        "audio": true,
                        "debug": true
                    }
                }
            ],

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: 

Homebridge and ffmpeg camera plugin updated today 11-17-2020

OS | OS X El Capitan
-- | --
MacBook-Pro.local
10.0.1.31
v14.15.0
v6.14.8

**Comment by joeyski** [comment]
Same here with foscam.  When audio is enabled, I get room previews in home kits but errors out when trying to live stream

**Comment by Sunoo** [comment]
Neither of you shared much information of debug logs, but most likely you are using a version of FFmpeg without the proper codec compiled in.

**Comment by joeyski** [comment]
If I disable audio, both previews and streaming work flawlessly

**Comment by Sunoo** [comment]
Most likely because you are missing the proper codec.

**Comment by joeyski** [comment]
Sorry if it’s a silly question but you mean audio codec I’m guessing?  I don’t find anything in the read me for installing audio codec.  Do I need to install that separately?  What I mean is it’s not automatically installed?

**Comment by joeyski** [comment]
I installed your plugin through config xi, if that matters?  Thanks in advance!

**Comment by Sunoo** [comment]
It is automatically installed if you are using a system supported by ffmpeg-for-homebridge.

**Comment by joeyski** [comment]
I don’t understand.  How would I know that?  Is config xi supported?  That’s what I’m using

**Comment by ggsubs** [comment]
Failing on fresh installs on both or raspberry and mac Catalina. The offending line from the debug out:
```
[21/11/2020, 13:22:52] [Camera FFmpeg] [Hik] Video stream requested: 1280 x 720, 30 fps, 299 kbps
[21/11/2020, 13:22:52] [Camera FFmpeg] [Hik] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[21/11/2020, 13:22:52] [Camera FFmpeg] [Hik] Stream command: /usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg rtsp://***:***@10.0.1.98:554/HighResolutionVideo -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 30 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 11856190 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params **** srtp://10.0.1.65:64307?rtcpport=64307&pkt_size=1316
  HAP-NodeJS:EventedHTTPServer [10.0.1.55] HTTP Response is finished +109ms
[21/11/2020, 13:22:52] [Camera FFmpeg] [Hik] FFmpeg exited with code: 1 and signal: null (Error)
[21/11/2020, 13:22:52] [Camera FFmpeg] [Hik] Stopped video stream.
```

Running the same in shell results:
`-bash: syntax error near unexpected token `('`

The issue seems the filter arg is not enclosed in quotes:
`-filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2`

Once the command line rerun with quotes the command succeeds in the shell.

**Comment by joeyski** [comment]
My home bridge server is in Catalina, but I don’t see the log details that you posted.  (Only error 1...)  wonder if osx installs are the issue?

**Comment by ggsubs** [comment]
To have debug need to start manually:
`DEBUG=* homebridge -D`

**Comment by HJ2k** [comment]
I still need help because I cannot get my homebridge to start up any longer.

>

**Comment by Sunoo** [comment]
You haven’t shared much information still. Please post your logs with debug enabled.

**Comment by HJ2k** [comment]
I enabled debug and my homebridge never started up again.   Now I don’t know how to get it to work at all.

**Comment by Sunoo** [comment]
I don’t know what to tell you. If you’re getting no output at all, open a ticket with the Homebridge project.

**Comment by razzfox** [comment]
This issue happened to me because `libfdk_aac` is not included in ffmpeg unless it is compiled with nonfree codecs.
