### ISSUE TITLE
vflip,hflip not working with ESP-32Cam

### ISSUE THREAD

**Issue by markunca** [Sunoo/homebridge-camera-ffmpeg#897]
**vlip and hflip configuration not working with ESP-32Cam through config**
trying it several option as optional item, even put through source but nothing help. Even with  -vf scale=320:240 hflip

**To Reproduce:**
Use ESP-32Cam with RTSP streamer

**Homebridge Config:**

"name": "Test Cam",
                    "model": "ESP 32",
                    "serialNumber": "50PAJ2DF4B",
                    "firmwareRevision": "V1.0",
                    "videoConfig": {
                        "source": "-re -i http://192.168.1.176",
                        "stillImageSource": "-i http://192.168.1.176",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 460,
                        "vcodec": "h264_omx",
                        "debug": true,
                        "hflip": true,
                        "maxFPS": 10
                    }

**Environment:**

* **Node.js Version**: v14.15.0
* **NPM Version**: v6.14.8
* **Homebridge Version**: v1.1.6
* **Homebridge Camera FFmpeg Version**: v3.0.3
* **Homebridge Config UI X Plugin Version**:  v4.33.0
* **Operating System**: Raspbian

**Comment by Sunoo** [comment]
The way to enable those features was changed in v2.5.0: https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/master/CHANGELOG.md#breaking-changes-1
