### ISSUE TITLE
Enhanced MQTT or HTTP Post notification messages

### ISSUE THREAD

**Issue by fretzy99** [Sunoo/homebridge-camera-ffmpeg#912]
![IMG_2523](https://user-images.githubusercontent.com/74735779/100662234-7aa09a80-3309-11eb-9505-365ceb85fbcd.jpg)
Add the ability to generate a detailed notification indicating the type of movement.... instead of something generic like "The BY1 camera has detected motion" add ability to indicate Person, Car, Pet/Object if received from the alerting source. Similar to what the nest does (see attached)

**Comment by Sunoo** [comment]
Does Nest offer that through Homebridge? I’m not familiar with a way to implement that in HomeKit, but if I the Nest plugin does it, I can look at the code and see how it was done.
