### ISSUE TITLE
Update from 1.3.0 -> latest (3.0.3) ... what do i have to consider ?

### ISSUE THREAD

**Issue by roe1974** [Sunoo/homebridge-camera-ffmpeg#945]
Hi
as described above I am currently still on 1.3.0 ... would like to go now on latest (3.0.3) ... what do I have to consider there ?
THANKS ! br, Richard

**Comment by Sunoo** [comment]
Best thing to do would be to open the change log and take a look at any sections labeled “Breaking Changes”: https://github.com/Sunoo/homebridge-camera-ffmpeg/blob/master/CHANGELOG.md
