### ISSUE TITLE
Can’t add unbridged cameras

### ISSUE THREAD

**Issue by MikeDProducer** [Sunoo/homebridge-camera-ffmpeg#948]
**Describe The Problem:**

Hi folks. It’s been a while. For the longest time was was running version 1.3.0 of the plug-in. It worked perfectly. For some reason I finally decided to update to the latest version. The bridged cameras slowed everything down so I changed the option to use them unbridged. But now I can no longer manually add the cameras in home app. They don’t show up despite the homebridge logs telling me to add them manually.

**To Reproduce:**
Any time I try to add cameras they do not show up in home app.

Do I have to redo my homebridge pin to fix this? I know it probably would solve it but then I would have to totally redo all of my accessories to homekit and that would suck.

**Comment by MikeDProducer** [comment]
I solved it! I removed them from cached accessories in homebridge.

**Comment by Sunoo** [comment]
Glad you solved it. Not sure too many people have jumped ahead that many versions at once, so I guess that never got caught.
