### ISSUE TITLE
How to access V2 Cam motion sensor for Homekit automation

### ISSUE THREAD

**Issue by HoTiCE2** [Sunoo/homebridge-camera-ffmpeg#952]
**Describe The Problem:**
I've just successfully flashed 4 x V2 Cams to the latest RTSP firmware 4.28.4.49 and everything works for streaming. I am however unable to access the motion sensor that is available in the Wyze native app. From reading online, it appears some are saying it should work.

I understand that we can create fake switches and motion sensors and tie them to a real sensor automation but I am trying to see if I can access the native motion sensor that is on the camera. Is this possible?

**To Reproduce:**
Nothing to reproduce, the motion sensor is simply not available.

**Logs:**
Even in debug mode, nothing occurs when there is motion in front of the camera

**Homebridge Config:**

```json
"name": "Camera Driveway",
                    "manufacturer": "Wyze",
                    "model": "Cam V2",
                    "motion": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://username:password@1[IP address]/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://username:password@[IP address]/still_image.jpg",
                        "vcodec": "copy",
                        "audio": true
                    }

.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.18.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.7
* **Homebridge Camera FFmpeg Version**:  3.0.3
* **Homebridge Config UI X Plugin Version**: 4.36.0
* **Operating System**:  Raspbian

**Comment by Sunoo** [comment]
Here are the various ways to get motion sensor from the camera to trigger a motion sensor in HomeKit. https://sunoo.github.io/homebridge-camera-ffmpeg/automation/ 

I’m not sure what Wyze RTSP supports natively, but if you switch to Dafang there is plugin for getting the motion sensor info over MQTT and into HomeKit.

**Comment by HoTiCE2** [comment]
Gotcha but those just generate a dummy motion sensor that you can trigger with a distinct real sensor. I assume there is no way then to get access to the native motion sensor in the Wyze Cam V2

**Comment by Sunoo** [comment]
If the RTSP firmware supports FTP uploads or SMTP emails, you can trigger motion that way. I’m not familiar with that firmware.
