### ISSUE TITLE
Add more automation/advanced Options

### ISSUE THREAD

**Issue by Tombra1889** [Sunoo/homebridge-camera-ffmpeg#957]
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/60692414/103096847-9136ca80-4605-11eb-945d-d1dc1d833557.png">

**Comment by Sunoo** [comment]
I honestly have no idea what UI this is a picture of, or how I would add anything to it.

**Comment by Tomba1889** [comment]
Maybe to control the NightVision via http as a light blub or disable the camera state as a switch control.

**Comment by Sunoo** [comment]
I still have no idea what tool this is.

**Comment by Tomba1889** [comment]
That's only an screenshot from ioBroker that shwos the possible Camera-Homekit-Characteristics.
