### ISSUE TITLE
Hikvision DS-2CD2T22WD-I5 and DS-2CD2322WD-I

### ISSUE THREAD

**Issue by r8plicant** [Sunoo/homebridge-camera-ffmpeg#958]
**Manufacturer/Model:**
Hikvision DS-2CD2T22WD-I5 and DS-2CD2322WD-I, firmware V5.5.82 build 190909.

**Homebridge Config:**

```json
    "platforms": [
        {
        "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera Front Door",
                    "videoConfig": {
                    "source": "-i rtsp://user:password@192.168.0.2/ISAPI/Streaming/channels/101/HighResolutionVideo",
                     "stillImageSource": "http://user:password@192.168.0.2/ISAPI/Streaming/channels/101/picture"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
```

**Additional Information:**
There are other APIs that work as well, such as rtsp://user:password@192.168.0.2/ISAPI/Streaming/channels/101/ for example, but I found this work to work best for me. The still image Source is not updated automatically on homekit, but the live stream works nice.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2T22WD-I5-and-DS-2CD2322WD-I.html

**Comment by r8plicant** [comment]
Hi, removing the line "stillImageSource": "http://user:password@192.168.0.2/ISAPI/Streaming/channels/101/picture"
makes the still image picture work, as the "source" line is used instead as fallback.

**Comment by Sunoo** [comment]
Great, I’ll update that shortly.

**Comment by Sunoo** [comment]
Updated: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2T22WD-I5-and-DS-2CD2322WD-I.html
