### ISSUE TITLE
JAWA

### ISSUE THREAD

**Issue by cj-debug** [Sunoo/homebridge-camera-ffmpeg#959]
**Manufacturer/Model:**
JAWA

**Homebridge Config:**
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Camera Name",
                    "manufacturer": "Jawa",
                    "model": "Z_22047",
                    "firmwareRevision": "1.70",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://admin:password@ipaddress:2600/",
                        "stillImageSource": "-rtsp_transport tcp rtsp://admin:password@ipaddress:2600.jpg",
                        "maxStreams": 3,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "vcodec": "libx264",
                        "audio": true,
                        "debug": false
                    }
                }

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Jawa-Z_22047.html
