### ISSUE TITLE
I cannot view video on WAN, I can on LAN

### ISSUE THREAD

**Issue by freebird317** [Sunoo/homebridge-camera-ffmpeg#960]
**Describe The Problem:**

I cannot view video on WAN, I can on LAN.  I was running a netgear router and all was working fine.  I turned my router in to an AP and stood up pfSense.  In Home I can only see video streaming if I am on LAN.

-xerror -rtsp_transport tcp -i rtsp://admin:5108338778!@192.168.1.211/cam/realmonitor?channel=1&subtype=0 -c:a aac -b:a 128k -c:v libx264 -b:v 2500k -preset superfast
**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] [verbose] Past duration 0.639992 too large
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] 
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] [verbose] Past duration 0.639992 too large
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] 
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] Stopped video stream.
[12/27/2020, 3:33:10 PM] [Camera-ffmpeg] [Right] FFmpeg exited with code: null and signal: SIGKILL (Expected)

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: I am not sure
* **NPM Version**: not sure
* **Homebridge Version**: 1.2.4
* **Homebridge Camera FFmpeg Version**: 3.0.3
* **Homebridge Config UI X Plugin Version**: not sure
* **Operating System**:  MacOS

**Comment by Sunoo** [comment]
I thought it was determined on the Reddit thread that it was related to your firewall?

**Comment by freebird317** [comment]
Wow fast response.

I am trying to find that out. :) Sorry I did not know you were the guy I was talking to on Reddit.

I know nothing of ffmpeg.

**Comment by Sunoo** [comment]
No worries! Happy to help where I can.

**Comment by freebird317** [comment]
I was thinking the problem might be with the encoding??  Is there another encoder I can use other than libx264?

Like is said i know nothing about FFmpeg, can you tell me if my config makes sense

"name": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Left",
                    "videoConfig": {
                        "source": "-xerror -rtsp_transport tcp -i rtsp://user:password@192.168.1.21/cam/realmonitor?channel=1&subtype=0 -c:a aac -b:a 128k -c:v libx264 -b:v 2500k -preset superfast",
                        "stillImageSource": "-i http://admin:5108338778!@192.168.1.212/cgi-bin/snapshot.cgi",
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "vcodec": "libx264",
                        "debug": true
                    }
                },
                {
                    "name": "Right",
                    "videoConfig": {
                        "source": "-xerror -rtsp_transport tcp -i rtsp://user:password@192.168.1.20/cam/realmonitor?channel=1&subtype=0 -c:a aac -b:a 128k -c:v libx264 -b:v 2500k -preset superfast",
                        "stillImageSource": "-i http://admin:5108338778!@192.168.1.211/cgi-bin/snapshot.cgi",
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "vcodec": "libx264",
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Comment by Sunoo** [comment]
You should remove `-c:a aac -b:a 128k -c:v libx264 -b:v 2500k -preset superfast` from the end of your source lines, not sure what you are trying to do with that.

If your camera outputs h264, you can try `copy`, or if you’re on a Raspberry Pi you can try `h264_omx`.

I don’t see why the codec would be related if it works on LAN though, since it would be the same for both.
