### ISSUE TITLE
Use additionalCommandline to output a second audio only stream?

### ISSUE THREAD

**Issue by LampaGJ** [Sunoo/homebridge-camera-ffmpeg#964]
**Describe The Problem:**

I have hacked together a baby monitor using a eufy Indoor Cam "2k" set to broadcast via RTSP, HOOBS running on a Raspberry Pi 4 4gb, and the Homebridge Camera ffmpeg plugin. What's nice about the eufy Indoor Cam is they encode at h.264 1920x1080 15fps which is already pretty ideal allowing ffmpeg to just pass the video through to HomeKit without so much as remixing (I believe) while still retaining on-device AI functionality (in this case, baby crying detection) via the iOS/iPadOS eufy Security App and its notifications. This allows active baby monitoring via video in the Apple Home app from anywhere without recording or any intermediation by a cloud service.

Additionally, I'm experimenting with an additional ffmpeg instance to route the audio from the camera to icecast2 in order to serve up an audio-only feed for background monitoring purposes. I already have this working by running the following command via ssh, but I believe running a second ffmpeg instance on top of what Homebridge Camera ffmpeg is already doing introduces significant latency (20s) to the audio by duplicating effort in pulling the original video and audio feed again as a second input for the Pi to process through as audio to icecast2.

I would like to be able to use the **additionalCommandline** feature of Homebridge Camera ffmpeg to specify outputting a second audio-only stream (or any arbitrary additional output such as writing to a .ts file on external storage attached to the Pi for private local video archiving) which would be routed to an icecast2 server running on localhost. This then serves up an m3u file allowing live audio monitoring ideal for use in the background (playing on an iPhone or again routed to a HomePod device, AirportExpress, or a Yamaha stereo via AirPlay). Again, the use case here is for a baby monitor, so using the audio-only version better allows for running in the background of any iOS/iPadOS or other device and a video feed.

**To Reproduce:**

My ffmpeg command for outputting the audio stream to icecast2 is pretty simple, all things considered:

`ffmpeg -rtsp_transport tcp -i rtsp://eufyIndoorCamIPaddress/live0 -vn -acodec copy -content_type 'audio/aac' -f adts icecast://source:hackme@localhost:8000/baby
`
This simply reads in the feed from the camera and passes through. I have attempted to specify in the Cameras configuration within HOOBS as simple as:

`"additionalCommandline": "-tune zerolatency -f adts icecast://source:hackme@localhost:8000/baby"
`

or as complicated as:

`-vn -acodec copy -content_type 'audio/aac' -f adts icecast://source:hackme@localhost:8000/baby
`

But neither works after the homebridge service restarts. However, the video feed to Apple Home app does continue to work. I'm guessing the issue here is that additionalCommandline specifies all additional items **before** the main output, so additional outputs would not be supported in this manner? Not clear to me though how the video and audio feed in home app would continue to work if the additionalCommndline items were actually having an effect.

**Logs:**

This is not a bug report but is instead a request for help.

**Homebridge Config:**

```json
[
    {
        "name": "Baby Monitor",
        "videoConfig": {
            "source": "-i rtsp://eufyIndoorCamIPaddress/live0",
            "maxStreams": 2,
            "maxWidth": 1920,
            "maxHeight": 1080,
            "maxFPS": 15,
            "vcodec": "copy",
            "audio": true,
            "debug": true,
            "additionalCommandline": "-tune zerolatency -f adts icecast://source:hackme@localhost:8000/baby"
        }
    }
]
```

**Screenshots:**

Screenshots are not applicable to this issue.

**Environment:**

* **Node.js Version**:  N/A or… 12.16.3?
* **NPM Version**: N/A
* **Homebridge Version**: HOOBS Core Version 3.2.6
* **Homebridge Camera FFmpeg Version**: 3.0.3
* **Homebridge Config UI X Plugin Version**: N/A 
* **Operating System**: HOOBS Core Version 3.2.6, Raspbian buster 4.19.97-v7l+

**Comment by Sunoo** [comment]
I see a few issues with what you’re trying to do:

1. `additionalCommandline` was removed in v3.0.0. You could pass these values in `encoderOptions`, but that isn’t intended for that sort of use.
2. The FFmpeg instance only runs while streaming video to HomeKit, not all the time. Additionally, multiple streams to HomeKit would mean multiple instances of FFmpeg. So your Icecast server would be receiving zero to multiple streams at once.
3. HOOBS has known issues with this plugin, and if the HOOBS developers do not correct them soon, future versions of this will no longer support it. I highly recommend switching to Homebridge, but you could also try putting pressure on the HOOBS developers.
