### ISSUE TITLE
Multiple Cameras in Hoobs

### ISSUE THREAD

**Issue by nicoryan** [Sunoo/homebridge-camera-ffmpeg#968]
Can you please help me with the correct json format to add multiple cameras in the json conf? I am using Hoobs. Below is my single camera json: 

[
    {
        "name": "Garage Interior",
        "videoConfig": {
            "source": "-i rtsp://admin:pass@ip/cam/realmonitor?channel=1&subtype=1",
            "maxStreams": 5,
            "maxWidth": 704,
            "maxHeight": 480,
            "maxFPS": 20,
            "maxBitrate": 768,
            "audio": true,
            "mapaudio": "0:1"
        }
    }
]

**Comment by Sunoo** [comment]
I don’t know HOOBS, but typically it would be something like:

```
{
"name": "Garage Interior",
"videoConfig": {
"source": "-i rtsp://admin:pass@ip/cam/realmonitor?channel=1&subtype=1",
"maxStreams": 5,
"maxWidth": 704,
"maxHeight": 480,
"maxFPS": 20,
"maxBitrate": 768,
"audio": true,
"mapaudio": "0:1"
}
},
{
"name": "Garage Interior",
"videoConfig": {
"source": "-i rtsp://admin:pass@ip/cam/realmonitor?channel=1&subtype=1",
"maxStreams": 5,
"maxWidth": 704,
"maxHeight": 480,
"maxFPS": 20,
"maxBitrate": 768,
"audio": true,
"mapaudio": "0:1"
}
}
```

No idea what the square brackets are for, guessing that’s some HOOBS nonsense.

**Comment by nicoryan** [comment]
@Sunoo Perfect, thanks!
