### ISSUE TITLE
Audio Not Working in Homebridge 1.3 beta

### ISSUE THREAD

**Issue by Sunoo** [Sunoo/homebridge-camera-ffmpeg#974]
I’m aware of the issue with audio apparently not working when using Homebridge 1.3 beta.

I have been able to recreate this issue, so I am looking into it. Though if anyone has any ideas, I’d love to hear them.

While I haven’t tested it myself yet, I’m told that this issue does not happen with the homebridge-ring plugin.

**Comment by SupImDos** [comment]
Hmm. I just installed the 1.3 beta onto my Macbook to test and troubleshoot this issue, and interestingly audio works perfectly fine. Its only on my Raspberry Pi 4 that I experience this issue.

Not sure if this helps.

**Comment by SupImDos** [comment]
What NodeJS version have you been testing with on the Pis?

I'll have to check properly in the morning, but I think from memory my Pi is on 14.x and my MacBook is on 15.x

Not sure why it would be, but might be worth ruling out the NodeJS version? Although I think Homebridge only recommends even versions anyway.

**Comment by Sunoo** [comment]
Both of the instances I tested were running on the latest version of 14. I’ll give 15 a try when I have a second, but I can’t think of a reason why that should be the issue. Definitely worth ruling out if possible though.

**Comment by SupImDos** [comment]
Appears a Ring user on Reddit also has this issue. May suggest its not this plugin specifically?

https://old.reddit.com/r/homebridge/comments/kol1el/testers_wanted_homebridge_v130_beta/giug3ur/

**Comment by Sunoo** [comment]
Yea, as far as we can tell, all camera plugins are potentially impacted, but we have had a few cases of people working.

**Comment by wayne-yates** [comment]
Sunoo, 

I am having an issue with the audio on the Homebridge Camera FFmpeg plugin. 

I have 2 cameras one that is working with audio and the other does not work. I have tried removing the plugin and re adding deleting the code and typing it out but nothing works have you got any other suggestions.

Thanks
<img width="699" alt="Screenshot 2021-01-20 at 14 00 10" src="https://user-images.githubusercontent.com/63819870/105184916-d2000180-5b27-11eb-86a1-5893f85aebdd.png">

**Comment by Sunoo** [comment]
@wayne-yates Your first camera has audio set to false.

**Comment by Sunoo** [comment]
To anyone still experiencing this, it should be resolved with Homebridge 1.3.0 beta 61.

**Comment by Sunoo** [comment]
Note that it's possible you may have to unpair Homebridge from HomeKit and pair it again under beta 61 or later to resolve the issue. Testing is being done now to see if it can repair itself without needing that step.

**Comment by Sunoo** [comment]
Okay, here's the verdict:

If you are using **unbridge** mode: Audio should start working again as soon as you upgrade to 1.3.0 beta 61 or later.

If you paired Homebridge on a version older than 1.3.0: Your audio likely never broke in the first place, and should continue to work. No changes needed.

If you paired Homebridge on a beta version of 1.3.0 that was 60 or lower: You will need to unpair your bridge, remove the accessory and persist directories from your Homebridge installation, and then pair it again on beta 61 or newer.
