### ISSUE TITLE
Camera switch and motion not enabled for notifications

### ISSUE THREAD

**Issue by ng-4r** [Sunoo/homebridge-camera-ffmpeg#983]
**Describe The Problem:**

I followed the instructions provided [here](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/switch.html), and motion and switch do appear in Apple Home App, but it is not possible to set notifications for them

**Homebridge Config:**

```json
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Raspberry",
                    "motion": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-re -f alsa -ar 44100 -ac 1 -i hw:1 -f v4l2 -video_size 1280x720 -i /dev/video0 -codec:v h264_omx -b:v 2048k",
                        "stillImageSource": "-f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Screenshots:**

Normally, options are like this ( from another accessory):
![IMG_1986](https://user-images.githubusercontent.com/10764178/103817377-ded02000-5066-11eb-9cec-441c7193ddb2.jpg)

But for both motion and switch from the camera are like this:

![IMG_1987](https://user-images.githubusercontent.com/10764178/103817387-e394d400-5066-11eb-970b-86b2a60a9123.jpg)

**Environment:**

* **Node.js Version**: v14.15.4
* **NPM Version**: 6.14.10
* **Homebridge Version**: v1.1.7
* **Homebridge Camera FFmpeg Version**: v3.0.3
* **Homebridge Config UI X Plugin Version**: v4.36.0
* **Operating System**: raspbian 10 (buster)

**Comment by Sunoo** [comment]
If the motion sensor appears, I can't think of a reason why the Home app wouldn't give you the notification options.

**Comment by ng-4r** [comment]
It’s really strange... even removing the plug-in and re-installing it didn’t change anything.

**Comment by ng-4r** [comment]
Okay, the voodoo of uninstalling the entire Homebridge instance and re-installing it along with all its plug-ins did the trick... really no explanation.
