### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by costispavlou** [Sunoo/homebridge-camera-ffmpeg#989]
Hi all, sorry if this has been asked before I tried searching but couldnt find an answer for that.
Is Alexa supported? Can I view its feed from homekit? If so, can you let me know how?
thank you!

**Comment by Sunoo** [comment]
I wasn’t aware of any Alexa-branded cameras, but as long as they have an RTSP feed or similar, it should be able to be added.

**Comment by costispavlou** [comment]
Hi sunoo thank you for your response!
Any chance you can point me how I can find the rtsp feed?

**Comment by Sunoo** [comment]
It would help to know what camera you actually have. I looked and do not see any cameras sold under the Alexa branding.

**Comment by costispavlou** [comment]
I’m referring to the echo spot or the show 5. I meant the camera that those devices have!

**Comment by Sunoo** [comment]
I don’t see any way of connecting to those cameras. My guess if there is a way, it would need a plugin custom made for the Alexa hardware.
