### ISSUE TITLE
Help AvertX Camera Homebridge

### ISSUE THREAD

**Issue by ras2008** [Sunoo/homebridge-camera-ffmpeg#992]
Hi, I am new to Homebridge and I would like to add my Avertx NVR to Homebridge. I spoke with the deliver about this plugin and he said it would work. My main quiestion is how do I connect homebrige to the nor the tell the nor to let Homebridge view the cameras. 

Thanks

**Comment by RemyTCO** [comment]
Any luck with that @ras2008 ?
