### ISSUE TITLE
Stream doesn’t load via remote access

### ISSUE THREAD

**Issue by Matzushub** [Sunoo/homebridge-camera-ffmpeg#994]
I was able to get this plugin to work on my raspberry Pi running homebridge just fine in my local network (iPhone, Apple TV as hub, raspberry and camera) as soon as I try to open the stream in the home app being outside from my own network the stream doesn’t load. The log of the PI shows me that homebridge isn’t even trying to start the stream. Any ideas?

I have another camera that is HomeKit certified and that stream works just fine in both situations.

**Comment by Sunoo** [comment]
If you’re seeing absolutely nothing in your logs, the attempt isn’t even getting to Homebridge. Check whatever device you’re using for a hub.
