### ISSUE TITLE
Reduce stream startup time by constantly running FFmpeg

### ISSUE THREAD

**Issue by rbswift** [Sunoo/homebridge-camera-ffmpeg#997]
**Is your feature request related to a problem? Please describe:**
I'm always frustrated waiting several seconds for the live stream to start from my cameras. All my cameras and my homebridge server are on a wired ethernet network with plenty of bandwidth.

**Describe the solution you'd like:**
I'd like a per-camera option to permanently establish the FFmpeg connection from homebridge to the camera if possible rather than to start this connection each time a live stream is requested by HomeKit as is currently the case.

**Describe alternatives you've considered:**
I have tried various switches and settings in ffmpeg to reduce the initial latency but none of these seem to have a significant effect.

**Additional context:**
Several HikVision cameras used. I would enable this for at least one or two of my cameras but not necessarily all.

**Comment by Sunoo** [comment]
I can’t speak to your specific setup, but typically the delay is on the HomeKit side. HomeKit is very picky and depending on specific encoding settings, it may take a while to start displaying. If you’re using the copy vcodec setting, you should try allowing transcoding, or vice-versa.

As a result of that, keeping a connection open to the camera wouldn’t help, and the endpoint used to stream to HomeKit changes each time as well anyways.

**Comment by rbswift** [comment]
Thanks for the feedback.

Understood. I've switched back to vcodec copy which is indeed much faster but has reintroduced the problem I was experiencing here: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/746. Would it be possible to reintroduce the additionalCommandline option please?

**Comment by Sunoo** [comment]
Use `encoderOptions`.
