### ISSUE TITLE
1

### ISSUE THREAD

**Issue by DobriyVasia** [Sunoo/homebridge-camera-ffmpeg#998]
[
    {
        "name": "Калитка",
        "videoConfig": {
            "source": "-rtsp_transport tcp -i rtsp://admin:12345@192.168.0.144:554/ch01.264?dev=1/live",
            "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:12345@192.168.0.144:554/ch01.264?dev=1/live -vframes 1 -r 1",
            "vcodec": "copy",
            "maxStreams": 2,
            "motion": true,
            "maxWidth": 2560,
            "maxHeight": 1920,
            "maxFPS": 15,
            "audio": true,
            "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
        }
    }
{
        "name": "1",
        "videoConfig": {
            "source": "-rtsp_transport tcp -i rtsp://admin:12345@192.168.0.145:554/ch01.264?dev=1/live",
            "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:12345@192.168.0.145:554/ch01.264?dev=1/live -vframes 1 -r 1",
            "vcodec": "copy",
            "maxStreams": 2,
            "motion": true,
            "maxWidth": 2560,
            "maxHeight": 1920,
            "maxFPS": 15,
            "audio": true,
            "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
        }
    }

]

**Comment by Sunoo** [comment]
Can you share what camera model this is for?

**Comment by DobriyVasia** [comment]
G.Craftsman 5Mp H.265



Отправлено из myMail для iOS


суббота, 16 января 2021 г., 20:08 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by DobriyVasia** [comment]
How do I prescribe 3-4 cameras in the app?


Отправлено из myMail для iOS


суббота, 16 января 2021 г., 20:08 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Sunoo** [comment]
> How do I prescribe 3-4 cameras in the app?

The same way you did two, just keep adding more.

**Comment by Sunoo** [comment]
Added: https://sunoo.github.io/homebridge-camera-ffmpeg/configs/G.Craftsman-5Mp-H.265.html
